### ISSUE TITLE
Diverging Tot term

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1017]
I managed to define a non-terminating term in `Tot`, which causes divergence in the normalizer and extracted OCaml code.

It seems the termination check is disabled when the "final" effect of a definition is `Div` (or some other non-total one), but this is not quite correct. The check should be disabled only when the *body* of the definition is marked to be non-total.

In other words, when defining a term of type `a -> Dv b` the check should be enabled, as this term is not yet marked as diverging. Hopefully the examples make it clearer. The `Tot` annotations can also be removed.

```
module Bug1017

(* Should not be accepted, the body is still in `Tot` *)
let rec loop (x : int) : Tot (int -> Dv int) = loop (x - 1)

(* Neither should this one. It also generates invalid OCaml: *)
(* > Error: This kind of expression is not allowed as right-hand side of `let rec' *)
let rec loop2 : Tot (unit -> Dv unit) = loop2

(* This one is OK, as it will only diverge when applied *)
let rec ok (u:unit) : Dv unit = ok ()

(*
 * Causes normalizer to loop. And to use an increasing amount of heap,
 * so I suspect GC is not kicking in (separate issue?)
 *)
let _ = assert_norm (loop 1 == ((fun x -> x) <: int -> Dv int))

(* This loops in extracted OCaml *)
let y : int -> Dv int = loop 42
```

**Comment by catalin-hritcu** [comment]
Thanks Guido for finding this critical bug in the termination checker. Should definitely fix, although, funny enough, this issue can't be use to prove `False`, can it?

As for the let rec issue:

> Error: This kind of expression is not allowed as right-hand side of `let rec'

it has already been filed in #450

**Comment by mtzguido** [comment]
Ah, didn't know about #450, thanks!

I also don't think this implies a contradiction, but I could be wrong :)

**Comment by mtzguido** [comment]
A related caveat is that `val` declarations seem to interfere with the decision to enable the check or not. In this code:

```
let t a = unit -> Dv a

val ff : unit -> t int
let rec ff (_:unit) (_:unit) : Dv int = ff () ()
```

The check is enabled (and thus `ff` rejected) but commenting out the `val` makes it succeed (as I think it should).

Only bringing this up as the fix might be in the same place in the compiler.

**Comment by nikswamy** [comment]
After a bunch of tweaking and lots of discussion with Guido ... the failure of the termination check is fixed. But, it involved imposing some syntactic restrictions. 

1. The definition of  a `let rec` must be a lambda literal. (cf #450)

2. If a `let rec` has an annotated type (e.g., either by a `val` or by an inline type annotation on the `let rec`), then this type must (after reduction to weak head normal form) be an arrow type of the form `x1:t1 -> ... -> xn:tn -> C`, for any computation type `C`. In this case, the definition must be a lambda term with exactly `n` binders. The termination check is enabled if `C` is an total effect.

A few notes:

   a. We are relying explicitly on the n-ary representation of function arrows and lambda terms. I.e., `x1:t1 -> x2:t2 -> C` has different behavior from `x1:t1 -> Tot (x2:t2 -> C)`. In the former case, we expect the definition to be a lambda term with exactly 2 binders; in the latter case, it must have just 1 binder. This is another instance of F\* treating n-ary binders differently from a sequence of curried arguments on unary `Tot` functions. It may be worth opening a separate issue to track and discuss n-ary binders vs. unary Tot functions.

   b. Note, the default computation type rule applies: i.e., the final computation type is `Tot` if left unspecified.

   c. This description applies to terms after desugaring. For example
           
```
 val f : t1 -> t2 -> s
 let f x y = e
```
is legal, since the `let` is just sugar for

```
 let f = fun x y -> e
```

d. When using ML-style type variables (e.g., ` 'a ` etc.) then the number of binders of the lambda term is counted after adding any implicit binders for the type variables. For example, the function below is legal, since although it is written with only one binder for the `list 'a` argument, we add an implicit binder for the type argument to both the `val` and the corresponding `let` definition.

```
val length: list 'a -> Tot nat
let rec length = function
   | [] -> 0
   | _::tl -> 1 + length tl
```


Some examples:

1. 

```
//Only function literals with arrow types can be defined recursively; got loop2 : uu___199989:unit -> Prims.Dv unit
let rec loop2 : Tot (unit -> Dv unit) = loop2
```

2.

```
//From its type uu___200013:int -> uu___200014:int -> Prims.Dv int, the definition of `let rec f1` expects a function with 2 arguments, but 1 argument was found
let rec f1 : int -> int -> Dv int = fun x -> f1 (x - 1)
```

3.

```
///Subtyping check failed; expected type (x:int{ x << x }); got type int
let rec f (x:int) : Tot (int -> Dv int) = f (x - 1)
```

Note, an eta-expansion does not help in this case, since because of the termination check applied to `f` when applied to 1 argument, in the body of its definition `f` is only defined on integers that precede `x` (and it is not the case that `x - 1 << x`, since integer ordering is not well-founded).

```
Subtyping check failed; expected type (x:int{ x << x }); got type int
let rec f (x:int) : Tot (int -> Dv int) = fun y -> f (x - 1) y
```

4. 

```
(* This one is OK, as it will only diverge when applied *)
let rec loop_ok (u:unit) : Dv int = loop_ok ()
```

5. 

```
//From its type uu___203662:unit -> Prims.Tot (t int), the definition of `let rec ff` expects a function with 1 argument, but 2 arguments were found

let t a = unit -> Dv a
val ff : unit -> t int
let rec ff (_:unit) (_:unit) = ff () ()
```

6. 

Like in 3, this fails the termination check, since `gg` is only defined on terms preceding `u:unit` (of which there are none).

```
///Subtyping check failed; expected type (u204030:unit{ u204030 << u203905 }); got type unit
let rec gg (u:unit) : t int = fun (_:unit) -> gg () ()
```

7.
This one is accepted 

```
let rec loop (x : nat) : Tot (int -> Dv int) =
  if x = 0 then fun x -> loop_ok ()
  else loop (x - 1)
```

**Comment by mtzguido** [comment]
Coming at this from another angle (and sorting out the mess in my head), to fix this we needed to pinpoint at each `let rec` definition exactly *where* the recursion is happening. In the original `loop` example. recursion is 1 argument in, which is in a `Tot` position, so it should have the check enabled. If it happened at position 2, we'd be in `Dv` and we disable it.

There are at least 3 (safe) ways to decide where the recursion is happening:
1- Collect all arguments up until a (non-`Tot`) effect. This would change the meaning of programs like Nik's example 7, which would be thunked and would not compute when applied to a single argument (even if that would be safe)

2- Collect all arguments up until *any* effect including Tot (which is what's implemented now). This is fine, but we're then distinguishing n-ary arrows from unary ones as Nik says. Also, certain programs are unexpectedly rejected, like:
```
val f : int -> Tot (int -> Dv int)
let rec f : int -> Tot (int -> Dv int) = fun x -> (fun y -> f x y)
```
This might just be because the abstraction on the right is collecting all the binders, since we used to think that was equivalent.

3- Allow the programmer to decide, by placing the recursions arguments on the left of the `:`. In this case we inspect the (immediate) declared effect and enable the check accordingly. This should be the most generic one, but would be hard to implement as after desugaring there's no trace of "left" and "right" arguments.


I think all 3 options are complete in the sense that one can work around whatever restrictions it has (by currying, say), but we decided for \#2 as \#3 would be a very big and invasive change. It did however make us ask if it's worth it to have n-ary arrows at all, or whether we should even expose them to users (two ways of being honest about them :) ). I might open up a meta-issue about that.

**Comment by tchajed** [comment]
I think #1182 is somewhat related. In particular, I'm a bit concerned about what we do with cases where `val f x : function` hides an effect in the definition of `function`. I want `f` to behave as an (n+m) arity function, with n parameters obvious in its definition (1 in this case) and another m parameters coming from `function`.
