### ISSUE TITLE
Not resolved reference warnings for FSharp.PowerPack with Mono

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1022]
Me and @cpitclaudel have recently (April 29) started getting many new warnings on Mono. While this doesn't seem to impact the build, it's still distracting.
```
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'FSharp.PowerPack' not resolved
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'FSharp.PowerPack.Linq' not resolved
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'FSharp.PowerPack.Metadata' not resolved
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'FSharp.PowerPack.Parallel.Seq' not resolved
```
Also tried running `make update-nuget` from `src/VS` (as suggested by @sishtiaq ), but it doesn't seem to change anything
before: https://gist.github.com/catalin-hritcu/7517b17e09f5aef2705f6362435c433c
after: https://gist.github.com/catalin-hritcu/9d1366570c4c670f74590d3c378f5fe8

**Comment by mtzguido** [comment]
Locally, I removed all mentions of Powerpack on my branch. Now I don't get the warnings and everything else seems to work. 

From the commit log [here](https://github.com/FStarLang/FStar/search?q=powerpack&type=Commits&utf8=%E2%9C%93) it seems Powerpack was used before but not needed anymore.

Should I just push its complete removal?

Related is the switch to msbuild, since xbuild is now deprecated. It seems to work fine, just that I'm not sure if it's installed in the build machine. I can also do that, if there's consensus.

**Comment by cpitclaudel** [comment]
> Should I just push its complete removal?

Yes, that'd be nice.

> Related is the switch to msbuild, since xbuild is now deprecated. It seems to work fine, just that I'm not sure if it's installed in the build machine. I can also do that, if there's consensus.

That would be nice too.

**Comment by mtzguido** [comment]
Great! Both of those are already in place in `guido_tactics`, which should be merged soon. I'm anyway gonna cherry-pick them and push to master today.

**Comment by mtzguido** [comment]
Done just now. (commits c2413966ed127b3a3dc8d0ae20a498c45f6df1ea and da97cbcb4870e4994bc9aca746d235296eb32f9e)
