### ISSUE TITLE
Badly positioned type error message for scrutinee of destructuring let

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1043]
Here's a concrete example:

```
module A

open FStar.List

let rec memP_append #a (x: a) (l: list a) :
  Lemma (List.memP x l ==>
         (exists (l1 l2: list a). l == l1 @ (x :: l2))) =
    match l with
    | [] -> ()
    | h :: t ->
      FStar.Classical.or_elim
        #(x == h)
        #(memP x t)
        #(fun _ -> exists (l1 l2: list a). l == l1 @ (x :: l2))
        (fun _ -> assert (l == [] @ (x :: t)))
        (fun _ -> let (l1, l2) = memP_append x t in ())
```

The error is located on the very last `()`; the message says this:

```
Expected type "Prims.unit"; got type "uu___unification_ 98884 a x l h t uu___43679 uu___43716 *
uu___unification_ 98888 a x l h t uu___43679 uu___43716"
```

Where does the `… * …` come from? And why is F* complaining about `()`?

**Comment by catalin-hritcu** [comment]
This is an ill-positioned error message. Here is a minimal example illustrating this:
```
let foo () : int =
    let (l1, l2) = "haha" in 42
```
produces the error:
```
Expected type "Prims.string"; got type "uu___unification_ 73566 uu___740442 uu___740451 * uu___unification_ 73569 uu___740442 uu___740451"
```
Which is fine if it pointed at the `"haha"` but it's actually pointing at the `42`! Strange stuff :)

Your original code has the same error, since memP_append returns `unit` not a pair, but again the error message is ill-positioned.

If I change the destructuring let to the corresponding match
```
let foo () : int =
    match "haha" with
    | (l1, l2) -> 42
```
the whole match gets blamed, which is already better but still not ideal.

**Comment by cpitclaudel** [comment]
Fixed in https://github.com/FStarLang/FStar/commit/7cb8fb8286bb8a40014238f9b8d5e0f3d08495f4
