### ISSUE TITLE
Example about max in tutorial breaks following lemma about factorial function; SMT encoding of assert and l_forall does not respect user-provided triggers

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1059]
The tutorial gives this example early on:

```

val max : int -> int -> Tot int
let max i1 i2 = if i1 > i2 then i1 else i2

let a = assert (forall x y. max x y >= x
                 && max x y >= y
                 && (max x y = x || max x y = y))

```

Unfortunately, that example breaks a later lemma:

```
module Factorial

open FStar.Mul

val max : int -> int -> Tot int
let max i1 i2 = if i1 > i2 then i1 else i2

let a = assert (forall x y. max x y >= x
                 && max x y >= y
                 && (max x y = x || max x y = y))

val factorial: x:int{x>=0} -> Tot int
let rec factorial n =
  if n = 0 then 1 else n * (factorial (n - 1))

val factorial_is_greater_than_arg: x:nat{x > 2} -> Lemma (factorial x > x)
let rec factorial_is_greater_than_arg x =
  match x with
  | 3 -> ()
  | _ -> factorial_is_greater_than_arg (x - 1)
```

```
./factorial.fst(16,57-16,74): (Error) could not prove post-condition
Verified module: Factorial (10720 milliseconds)
1 error was reported (see above)
```

This doesn't happen when running from the web UI — I was just following along in an Emacs buffer.

**Comment by anton-trunov** [comment]
I cannot reproduce this bug using a development version of Fstar (install via OPAM):
```
fstar.exe --version
F* 0.9.4.3
platform=Darwin_x86_64
compiler=OCaml 4.04.1
date=2017-06-11T17:36:11+03:00
commit=8ca4988f1
```

```
z3 --version
Z3 version 4.5.0 - 64 bit
```

**Comment by cpitclaudel** [comment]
This was from a master build for me (same Z3). IIRC @aseemr could reproduce it too (right?).

**Comment by aseemr** [comment]
This still fails for me with F* master.

**Comment by anton-trunov** [comment]
And now I can reproduce! It looks like I lost the body of `factorial_is_greater_than_arg` when copy-pasting the example. Sorry for the false alarm.

**Comment by catalin-hritcu** [comment]
This is an example of flakiness that does sometimes occur in F* with unrestricted quantifiers (without good patterns) and with non-liniar arithmetic. This example mixes both, so not so surprising that this is flaky.

**Comment by markulf** [comment]
Have you tried increasing resources, e.g.,
```#set-options " --z3rlimit 100"```?

**Comment by cpitclaudel** [comment]
I haven't. I think @aseemr was looking into this at some point :)

**Comment by nikswamy** [comment]
It works with enough rlimit, e.g., `--z3rlimit 30`. 

It is indeed a problem of introducing a quantifier into the context without a pattern which sends the search of the rails.

There are several issues going on here:

1. This is in the very early part of the tutorial. So, the early stumbling block is a problem. We don't want to get into triggers etc. at this stage.

2. The reason this quantified formula gets into the context is because we encode the definition of `Test.a` precisely to the solver, i.e., 

```
;;;;;;;;;;;;;;;;Equation for Test.a
;;; Fact-ids: Name Test.a; Namespace Test
(assert (! (= Test.a
              (Prims._assert (Prims.l_Forall Prims.int
                                             (Test_Tm_abs_f956ec11c12ffdd5041512ef6a45ef9f Prims.int))))
           :named equation_Test.a))
```

Maybe we shouldn't do this. More generally, for the SMT encoding, perhaps its worth putting in an optimization that encodes all pure terms of type `unit` as `Tm_unit` (as is the case here). That would side step this problem.

3. It turns out that in this example, even if you were to write 

```
let a = assert (forall x y.{:pattern (max x y)}
                    max x y >= x
                 && max x y >= y
                 && (max x y = x || max x y = y))
```

The SMT solver would still go off the rails. That's because of something discussed in issue #1208, in particular the forall-interp axiom, which doesn't preserve user-defined triggers in this case. So, we

**Comment by nikswamy** [comment]
The generic `forall-interp` and `exists-interp` are now gone, in favor of specific instantiations produced on an as-needed basis by the encoding.
