### ISSUE TITLE
Constructor that uses an assumed type causes Failure in positivity check

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1076]
The following code causes F* to throw a Failure (terminating unexpectedly in interactive usage);

`assume_type.fst`:
```
module Assume_type

assume val t:Type

type inductive =
  | Const0 : inductive
  | Const1 : t -> inductive
```

```
$ fstar.exe assume_type.fst
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Unexpected data constructor type when checking positivity")
```

Interestingly, using `assume type t` causes a non-fatal error about not having decidable equality on `t`.

I'm using F* compiled from source, currently at commit [cf96c5ace](https://github.com/FStarLang/FStar/commit/cf96c5acebc03965d2f5cbc34f779cacc225b209).

**Comment by aseemr** [comment]
Fixed in https://github.com/FStarLang/FStar/commit/514b865f7bcc32158ba011357e0a4cadfb3e97b1. The case for data constructor types was not handling the `Tm_uinst` case (I think it can be optimized by just returning `true` instead of descending into the base type, as the code is doing currently).

Note that the code above still does not type check with an error about decidable equality for `inductive`. Adding the `noeq` qualifier makes it work.
