### ISSUE TITLE
Failure("Unexpected data constructor type when checking positivity")

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1128]
```
type witness (n:nat) = n

type maybe_witness =
  | Nothing
  | Just: n:nat -> witness n -> maybe_witness

val bug: maybe_witness -> (option (m:nat & witness m))
let bug =
    function
    | Just n tn ->
        Some (Mkdtuple2 n tn)
    | _ -> None
```

**Comment by kyoDralliam** [comment]
Definitively this definition `type witness (n:nat) = n` ougth to be rejected (a natural number should not be accepted by such a type declaration...), will look into it.

**Comment by aseemr** [comment]
Related to it being parsed as a let binding?

```
$ fstar.exe --dump_module Test Test.fst
module Test
let Test.t n = n
module Test
let Test.t n = n
Verified module: Test (22 milliseconds)
All verification conditions discharged successfully
```

**Comment by kyoDralliam** [comment]
More or less... I don't think the let-binding is the issue (at least I see them as equivalent provided you are working with"types"). The problem is that we don't put any restriction on the let-binding ensuring that the aliased value is a type. I tried to enforce it but it fails in the standard library because we are writing things like `type set = TSet.set` instead of its eta-expanded version `type set a = TSet.set a`

**Comment by kyoDralliam** [comment]
The implemented fix is to forbid `type` declarations which are not abbreviations to types. In practice it entails that type declarations must now be explicitly eta-expand or having a type annotation : `type set a = TSet.set a` or `type set : Type -> Type = TSet.set`

**Comment by cpitclaudel** [comment]
Neat! Can you still write `type a: int = 1` though?

**Comment by kyoDralliam** [comment]
hmm... right you can write this. Should this be forbidden too ?

**Comment by cpitclaudel** [comment]
I don't know. It looks weird to me :)
