### ISSUE TITLE
Error message for 'apply' mentions only one term

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1174]
Here's an example:

```
assume val g1: Type0
assume val g2: Type0
assume val w1: g1
assume val w12: g1 -> g2

let test : unit =
  assert_by_tactic g2 (apply (quote w12);; exact (quote w1))
```

The error message is `user tactic failed: apply: cannot unify (CPC.Reflect.g2)`.  It would help to change it to `user tactic failed: apply: cannot unify goal with (CPC.Reflect.g2)`, since this might make it easier to guess that the goal was in fact `squash g2`.

**Comment by mtzguido** [comment]
Thanks Clément, just fixed this in my branch. Besides what you said, the error message for apply was particularly bad since it tries unify the goal with successively-more-instantiated versions of its argument, by applying to uvars each time around a loop. The error was only displayed on the last one, which is confusing if your goal is an arrow in itself (which happens only on synthesis, but still). I fixed that too now.

This is the new message for your example:
```
./A.fst(11,2-11,18): (Error) user tactic failed: apply: Cannot instantiate A.w12 (of type uu___658856:A.g1 -> Prims.Tot A.g2) to match goal (Prims.squash A.g2) (see also /home/guido/r/fstar/ulib/FStar.Tactics.Effect.fst(92,32-92,42))
1 error was reported (see above)
```

This will go into master when we resume merging to it.

**Comment by cpitclaudel** [comment]
Super, thanks much.
I really hope we get around to having structured error messages at some point :) It'll be much nicer on the UI side.
