### ISSUE TITLE
F* does not sufficiently normalize a recursive definition's type to identify its arity

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1182]
The definition `id3` can take 2 arguments if you unfold `func`. The body would typecheck, but a more restrictive check is being performed for a `let rec` with a `val` that doesn't peek inside the definition of `func` (even if it's marked `unfold`).

```fstar
module FunctionAlias

type func = nat -> Tot nat

val id1 (f:func) : func
let id1 f = fun n -> f n

let rec id2 f = fun n -> f n

val id3 (f:func) : func
let rec id3 f = fun n -> f n
(* Error: From its type f:FunctionAlias.func -> Prims.Tot FunctionAlias.func,
the definition of `let rec id3` expects a function with 1 argument, but 2
arguments were found *)
```

**Comment by WolframKahl** [comment]
A smaller example:
``` fsharp
type unOp 'a = 'a -> 'a

val twice : unOp 'a -> unOp 'a
let rec twice f x = f (f x)
```
Remove the `rec` and it is accepted.

**Comment by mtzguido** [comment]
I worked a bit on this, trying to do more normalization on types before the check. Both of your examples then go through, but we get several regressions in functions relying on their types *not* being ufolded. Such as this, from `FStar.Set`:
```
val as_set' : #a:eqtype -> list a -> Tot (set a)
let rec as_set' #a l = match l with
  | [] -> empty
  | hd::tl -> union (singleton hd) (as_set' tl)
```
since `set` is itself a function, this should fail after unfolding due to the check in #1017.

I think we should revisit that check, particularly since interfaces can hide the definition of a type and then the check is just a guess. I'll  work on it, but probably past March 16th, unless this is really blocking you guys.

Thanks for the examples!
