### ISSUE TITLE
Impossible: Multiple post candidates

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1195]
This module:

```
module Minimal

let dummy (a: Type) = unit -> M (either unit unit)

let return_dummy (a: Type) (x: a) : dummy a = fun () -> Inr ()

let bind_dummy a b (f: dummy a) (g: a -> dummy b) : dummy b = fun _ ->
  Inr ()

reifiable reflectable new_effect {
  EXCEPTION : (a:Type) -> Effect
  with repr     = dummy
     ; bind     = bind_dummy
     ; return   = return_dummy
}
```

produces this assertion failure:

```
Impossible: multiple post candidates uu___162548:Prims.unit ->
uu___162549:(uu___162550:FStar.Pervasives.either Prims.unit Prims.unit -> Prims.Tot Type0) ->
Prims.Tot Type0
```

cc @kyoDralliam who wrote this code

**Comment by kyoDralliam** [comment]
This should not be an assertion failure, I'm correcting it to an error. Also the error message is misleading because you don't have multiple candidates for the post condition but none.

The original problem at hand is that we do not have a principled way to define pre/post-conditions for arbitrary monads. What we are currently doing is a syntactic recipe which works for the simplest cases but does not have any clear generalisation (and does not handle the constrant monad as-is).

Otherwise, you can define a 'constant' monad but you need to trick DM4F a little since it is really syntactic. One solution is to provide your constant as abstract in another module (the abstraction is used in order to prevent the compiler from reducing your definition so that you can control the syntactic occurences of your types).

```F#
module Ignore

abstract
type t (a:Type) = unit

abstract
let const (a:Type) : t a = ()
```

```F#
module Minimal
let dummy (a: Type) = unit -> M (Ignore.t a)

let return_dummy (a: Type) (x: a) : dummy a = fun () -> Ignore.const a

let bind_dummy a b (f: dummy a) (g: a -> dummy b) : dummy b = fun _ ->
  Ignore.const b

reifiable reflectable new_effect {
  EXCEPTION : (a:Type) -> Effect
  with repr     = dummy
    ; bind     = bind_dummy
    ; return   = return_dummy
}
```

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by kyoDralliam** [comment]
I have a green on `kyod_1195` which should fix this issue. I'll merge it in master asap.

**Comment by mtzguido** [comment]
From what I can see this was merged already (and works). Please reopen if not!
