### ISSUE TITLE
Error: Expected a trivial pre-condition when normalizing stateful function

### ISSUE THREAD

**Issue by tchajed** [FStarLang/FStar#1206]
I'm not sure why this doesn't work. It fails with "Expected a trivial pre-condition", with the error location at `Some off` in `ser_id`. I couldn't find a way to trigger this without the record and the refinement (eg, changing `bslice` and `len` to assumed values with the appropriate types doesn't work).

```
module Expected_trivial

open FStar.Tactics
open FStar.HyperStack.ST

#reset-options "--max_fuel 1 --max_ifuel 1"

type bslice =
| BSlice : len:nat -> bslice

let serializer_ty  = buf:bslice -> Stack (option (off:nat{off <= buf.len}))
  (requires (fun h0 -> True))
  (ensures (fun h0 r h1 -> True))

let ser_id (s1: serializer_ty) : serializer_ty =
  fun buf -> match s1 buf with
  | Some off -> Some off
  | None -> None

assume val ser : serializer_ty

let normalize (#t:Type) (x:t) : tactic unit =
  dup;;
  exact (quote x);;
  norm [delta];;
  trefl

let ser' : serializer_ty =
  synth_by_tactic (normalize (ser_id ser))
```

**Comment by mtzguido** [comment]
Sorry for taking so long to answer this.

The precondition that is not trivial is:
```forall (i:Prims.int). i <= (let E.BSlice len = buf in len) == (i <= (let E.BSlice len = buf in len))```,
which indeed looks trivial, but the simplifier is not kicking in for it due to the `Tm_match` in it (printed as a `let` here).

This arises from the fact that the projector `BSlice?.len` is being unfolded, and `tc_pat` needs to perform a check that the type we're matching corresponds with the type of the scrutinee. If we just prevent that, this works better:
```
module E

open FStar.Tactics
open FStar.HyperStack.ST

#reset-options "--max_fuel 1 --max_ifuel 1"

type bslice =
| BSlice : len:nat -> bslice

let serializer_ty  = buf:bslice -> Stack (option (off:nat{off <= buf.len}))
  (requires (fun h0 -> True))
  (ensures (fun h0 r h1 -> True))

let ser_id (s1: serializer_ty) : serializer_ty =
  fun buf -> match s1 buf with
  | Some off -> Some off
  | None -> None

assume val ser : serializer_ty

let normalize (#t:Type) (x:t) : tactic unit =
  dup;;
  exact (quote x);;
  norm [delta_only ["E.ser_id"
                   (* ; "E.__proj__BSlice__item__len" *) // this causes the failure
                   ]];;


  trefl

let ser' : serializer_ty =
  synth_by_tactic (normalize (ser_id ser))
```
Then C-c C-s C-p on `ser'` gives
```
E.ser'
<input>(32,4-32,8)

Type
  buf:E.bslice ->
  FStar.HyperStack.ST.Stack
    (FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) })))
    (fun h0 -> Prims.l_True)
    (fun h0 r h1 -> Prims.l_True)

Definition
  let E.ser' buf =
    (let uu___806784 =
        E.ser buf
        <:
        FStar.HyperStack.ST.STATE
        (FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) })))
      in
      ((match uu___806784 with
          | FStar.Pervasives.Native.Some #uu___802434 off ->
            FStar.Pervasives.Native.Some off
            <:
            Prims.PURE
            (FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) })))
          | FStar.Pervasives.Native.None #uu___802729 ->
            FStar.Pervasives.Native.None
            <:
            Prims.PURE
            (FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) }))))
        <:
        FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) })))
      <:
      Prims.PURE
      (FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) }))))
    <:
    FStar.HyperStack.ST.STATE
    (FStar.Pervasives.Native.option ((off:Prims.nat{ Prims.b2t (off <= BSlice?.len buf) })))
```

There's a couple ways to fix that failing assertion.
1) allowing SMT on it, but this was explicitly forbidden so there might be a reason why it's not allowed
2) improve the simplifier, or actually `eq_tm` to take this case into account. But `eq_tm` is only supposed to check for equality of zero-order terms, and these two actually differ in a bound variable.

So surprisingly this is example is not related to the fact the functions are effectful, but it's likely you'll find such failures. Maybe it's enough to workaround it, though. (And maybe you'd like a way to *subtract* identifiers from the delta set, much as `--using_facts_from` and all those options that take a "forest").

**Comment by mtzguido** [comment]
This now works in my branch, since `eq_tm` can now compare terms with bound variables (by index). Merging to master soon.
