### ISSUE TITLE
Unexpected output from Z3 after duplicating a definition

### ISSUE THREAD

**Issue by victor-dumitrescu** [FStarLang/FStar#1222]
An example like the following
```
val x: a: int -> b: int -> Lemma (a + b = 0 ==> a = -b)

let x a b = admit ()

let x a b = admit ()

let z = assert (2 + 3 = 5)
```
when run in interactive mode, will generate this warning from Z3 when verifying the last `assert`:

```
Test: Unexpected output from Z3: (error "line 40452 column 3: Wrong number of arguments (5) passed to function (declare-fun Test.x (Term Term) Term)")
```

**Comment by s-zanella** [comment]
The function `x` is encoded correctly and the warning goes away when annotating the result type in the second definition:

```let x a b : Lemma (a + b = 0 ==> a = -b) = admit ()```

Add this to the list of quirks in #965.

**Comment by catalin-hritcu** [comment]
Could this be the same as #1150?

**Comment by aseemr** [comment]
This bug still remains after fixing 1150.

**Comment by aseemr** [comment]
This is really weird. For the second `let x`, its SMT declaration says that `x` is a function with arity 2 (perhaps from the `val`). And then, the actual let binding has 5 arguments, where the additional three arguments are generalized types for `a`, `b`, and `admit`. So, the duplication causes `let x` to be typed and generalized independently of the `val`.

My guess is with @s-zanella annotations, the type variables are instantiated properly, and hence the arity matches after that.

I think it should be fixed by not allowing duplicates, rather than in the smtencoding.

**Comment by mtzguido** [comment]
This might be a non-issue now since we reject duplicate definitions? Though I'm not sure if #965 is fully fixed or not.

**Comment by aseemr** [comment]
We are now rejecting duplicate top-level definitions. Things work fine in the absence of the duplicate definition. Closing this bug.
