### ISSUE TITLE
Surprisingly slow Z3 when writing tactics in direct style

### ISSUE THREAD

**Issue by cpitclaudel** [FStarLang/FStar#1269]
I haven't managed to get Z3 to accept the following:

```
module SlowZ3

open FStar.Tactics

let pattern_of_term tm : Tac int =
  let tm' = norm_term [] tm () in
  fail "??" ()
```

What gives?

Rewriting it this way works:

```
let pattern_of_term tm : Tac int =
  (t <-- norm_term [] tm;
   fail "??") ()
```

**Comment by cpitclaudel** [comment]
Discussed during the all-hands: the problem is that Z3 spends a lot of time proving that `Tac` is "stable" (that is, that binding to computations with effect `Tac` yields a computation with effect `Tac`). That's because `Tac` has trivial VCs, and Z3 reproves that binding two trivial VCs together yields a trivial VC.

We concluded that it'd be nice to add a `stable` keyword when defining an effect, which would do the stability verification once and for all and thereafter get rid of the VCs (like we currently do for `Tot`)

**Comment by mtzguido** [comment]
Making a note: I think another approach is changing how we check for triviality of WPs.

From looking at the VC, I think the current approach (which I can't follow in the code) is checking that `null_wp <= wp`, where `<=` is our "stronger" relation (or the modification introduced later, whose details I forget).

There's an equivalent formulation to that, namely another inductively-defined WP combinator called `sat`, which satisfies `sat wp <==> null_wp <= wp`. Further, I think that `sat` of the WPs generated here might even be trivial by simplification, or at least easier for the SMT.

Unsure on the priority scale for this one, but I could give this a try when it reached to top of the stack :)

**Comment by mtzguido** [comment]
Some support for the stable solution is now in-place. A composition of `Tac`s is now a `Tac`, but if in a long sequence of let-bindings there happens to be an arising `TAC` (esp. near the end) the generated VC might still be huge.

I still want to investigate the WP improvement, but at some other time since it's complicated.

Another option we thought of is having
```
effect TacF (a:Type) = TAC a (fun _ _ -> False)
```
which effectively turns all tactic VCs into `True` by normalization, causing instant verification. The downside is that we lose the guarantee of even basic type safety when it happens to rely on the SMT. In particular, type equality involving a variable is, so this succeeds when it should not:
```
let f (#a:Type) (x:a) : TacF unit = x
```
While that's bad, I think we can still keep this one as an option to the programmer.

**Comment by mtzguido** [comment]
After adding some (generic!) simplifications to F*, this is now much better. In particular, turning
`(forall x y z. p x y z) ==> E[p]`
into
`E[fun x y z -> True]`
justified by extensionality. 

Your example (adapted to the new library) will now go through without any use of SMT. Also things like:
```f#
let tau b tm : Tac term =
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    let tm = norm_term [] tm in
    match inspect (quote b) with
    | Tv_App l r -> tm
    | Tv_Type _ -> tm
    | Tv_AscribedT _ _ None -> tm
    | _ -> tm
```
For any amount of `norm_term` lines or whatever other `Tac`, are now trivial, and go through without SMT. I even *removed* the special-case stability of `Tac`, since that's pretty much a special case of this now. It's also very close to the idea of changing triviality checking to `sat wp`, instead of `null <= wp`, since this simplification actually turns the latter into something that normalizes to the former.

I also removed a bunch of `admit`s thanks to this, but not all. Coverage checks on matches without a default case are still tough sometimes. But that's a generic problem, so I think this is better left closed.

**Comment by cpitclaudel** [comment]
Great job!
