### ISSUE TITLE
ST example from tutorial not working

### ISSUE THREAD

**Issue by beta-ziliani** [FStarLang/FStar#1328]
In 2.3.2 of the [tutorial](https://www.fstar-lang.org/tutorial/) there is a simple example every ML user is familiar with:
````
open FStar.ST

val new_counter: int -> St (unit -> St int)
let new_counter (start: int) =
  let c = ST.alloc start in
  fun () -> c := !c + 1; !c
````

However, F* is not able to verify this example, throwing the error:
````
(Error) Failed to resolve implicit argument of type 'FStar.Preorder.preorder ((fun start -> (fun start -> (fun start -> (fun start -> Prims.int) start) start) start) start)' introduced in (*?u41*) _ start (see also Eff2(9,25-9,27))
````

**Comment by mtzguido** [comment]
Good to see you around here :)

This is already tracked in #1056, which has a fix for that inference failure. However, the example has an assertion failure which I'm not sure has had a proper diagnosis.

In general, the tutorial usually lags behind development as we don't yet have a way to automatically test it.

**Comment by aseemr** [comment]
Hi! The assertion failure is due to the imprecise encoding of impure arrows to the smt solver (#855). I need to fix it soon.

Regarding the inference failure, we should change the tutorial to use `open FStar.Ref` instead of `open FStar.ST`. This is also logged in the README here: https://github.com/FStarLang/FStar/blob/master/CHANGES.md (the second bullet under Standard Library).

**Comment by catalin-hritcu** [comment]
Closing as duplicate
