### ISSUE TITLE
Explicit and implicit dependency precedence and namespaces differ

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#1335]
I added `FStar.Monotone.Map` to `ulib`. As a consequence, `Map` in `FStar.Monotone.Seq` got resolved to `FStar.Map` (when implicit dependencies were used), e.g. when running `fstar FStar.Monotone.Seq.fst` and to `FStar.Monotone.Map` when explicit dependencies were used, e.g. when running `fstar FStar.Monotone.Map.fst FStar.Monotone.Seq.fst`.

There are multiple ways to trigger this switch form implicit to explicit dependency namespaces, e.g. by using `open FStar.Monotone.Seq` instead of using `module MS = FStar.Monotone.Seq` and this results in lengthy and confusing errors.

This might be related to an existing issue, or discussion, is it related to backward compatibility to F#? Lets fix this if there is no good reason to be bugward compatible?

**Comment by markulf** [comment]
A particular annoying aspect about this bug was that it initially made FStar regression go through and I could commit to `master` as `ulib` files are checked one at a time, while it really shouldn't have let me do this.

A temporary fix would be to add extraction of `ulib` to regression.

**Comment by nikswamy** [comment]
I've been looking at this briefly but I don't understand the issue. 

Can you provide a precise repro of the behavior that you find undesirable?

Thanks!

**Comment by markulf** [comment]
Thanks Santiago, in case we want to follow a policy of adding bug repros to regression I am happy to give it a try. Do we have a wiki describing the process, or is the Makefile in `examples/bug-reports/` self explanatory?

**Comment by s-zanella** [comment]
Let's first determine whether it is a bug or a feature.

**Comment by nikswamy** [comment]
I agree it is undesirable and is probably a bug. Investigating now ...

**Comment by nikswamy** [comment]
Ok, it's a bug because of a discrepancy in the implicit opens used in the dependence analysis vs. in the desugaring used by ToSyntax.

Desugaring always implicitly opens the namespace of the current module. This means that `A.a` in `module N.B` resolves to `N.A`. However, the dependence analysis was missing this implicit opening and resolving `A.a` just to module `A`.

I have a patch to the dependence analysis that implicitly opens the current namespace, bringing it in line with desugaring. 

Note, with this patch, if you really want to refer to module `A` from `N.B` you'll have to do something like 

```
module N.B
module IReallyMeanA = A
let b:int = IReallyMeanA.a
```

**Comment by nikswamy** [comment]
Seems like a long-standing bug that you've just stumbled upon recently. thanks for the report
