### ISSUE TITLE
cannot define my own fold on lists...

### ISSUE THREAD

**Issue by zeta1999** [FStarLang/FStar#1343]
```
module Bug01
open FStar.List

val fold: (#a: Type) -> (#b: Type)
  -> (f: a -> b -> a) -> a -> (l: list b) -> Tot a
let rec fold (#a) (#b) f acc l = match l with
  | h::t ->
    let acc2 = f acc h in
    foldl f acc2 t
  | [] -> acc
```
```
C:\Users\[...]>fstar.exe --verify_module Bug01 bug01.fst
[31;1m.\bug01.fst(9,17-9,18): (Error) Subtyping check failed; expected type (l:Prims.list b{ Prims.LexCons acc2 (Prims.LexCons l Prims.LexTop) <<
    Prims.LexCons acc (Prims.LexCons l Prims.LexTop) }); got type Prims.list b (see also .\bug01.fst(6,0-10,13))
[0m[31;1mVerified module: Bug01 (948 milliseconds)
[0m[31;1m1 error was reported (see above)
[0m
```
At very least the error message is moderately clear...

**Comment by mtzguido** [comment]
This is expected: by default, F* uses the lexicographic ordering of the arguments a termination metric. In this case, since the ones that vary are `acc` and `l`, it means that it will need to prove on each recursive call that `acc` decreases; or, if it stays the same, that `f` decreases.

In this case that's not true, since `acc` can vary in any way, but `l` is your "recursive argument". To make F* use `l` as the metric, you need to annotate a `decreases` clause.

```ocaml
module F
open FStar.List

val fold: (#a: Type) -> (#b: Type)
  -> (f: a -> b -> a) -> a -> (l: list b) -> Tot a (decreases l)
let rec fold (#a) (#b) f acc l = match l with
  | h::t ->
    let acc2 = f acc h in
    fold f acc2 t
  | [] -> acc
```

The error message is bad though, and we should improve it. See #418.

**Comment by zeta1999** [comment]
Just came to a similar conclusion a few minutes after you!
Thanks :-) 

val foldl: (#a: Type) -> (#b: Type)
  -> (f: a -> b -> Tot a) -> a -> (l: list b) ->
  Pure a
  (requires true)
  (ensures fun r -> True)
  (decreases l)
let rec foldl (#a) (#b) f acc l = match l with
  | [] -> acc
  | h::t -> foldl f (f acc h) t
