### ISSUE TITLE
Effect abbreviations are not properly checked

### ISSUE THREAD

**Issue by WolframKahl** [FStarLang/FStar#1370]
We are trying to define an effect that allows only one kind of exception to be thrown: 
``` fsharp
module Raising

open FStar.Pervasives
open FStar.Exn

// inferred type: Raises : ex:Prims.exn -> a:Type0 -> Prims.Tot Effect
effect Raises (ex:exn) (a:Type)  =
    Exn a (requires True)
        (ensures (function
                | (V _) -> True
                | (E e) -> e == ex
                | _ -> False
        ))

exception Bad
exception ReallyBad

val u : nat -> Raises Bad nat
let u i = if i > 10 
    then i 
    else raise Bad                  // expected to work
    // else raise ReallyBad         // expected to fail type checking
```
Checking this in the tutorial system produces:
````
Raising(18,8-18,29): (Error 12) Expected type "Type"; got type "Prims.exn"
Raising(20,9-20,10): (Error 188) Expected expression of type "Raising.Bad"; got expression "i" of type "Prims.nat" (see also Raising(19,6-19,7))
2 errors were reported (see above) 
````
I can see that the second error message might be a consequence, in a strange way, of the misunderstanding underlying the first.

But I cannot understand the first error message at all, especially since its range indicates the whole type expression `nat -> Raises Bad nat`, which should rather obviously be a `Type` and not a `Prims.exn`.

**Comment by mtzguido** [comment]
Hello Wolfram, thanks for the report!

There seems to be some part of the compiler that is assuming that the first argument to an effect is a type, if you flip them, you get past your original error:
```
module Raising

open FStar.Pervasives
open FStar.Exn

// inferred type: Raises : ex:Prims.exn -> a:Type0 -> Prims.Tot Effect
effect Raises (a:Type) (ex:exn) =
    Exn a (requires True)
        (ensures (function
                | (V _) -> True
                | (E e) -> e == ex
                | _ -> False
        ))

exception Bad
exception ReallyBad

val u : nat -> Raises nat Bad
let u i = if i > 10 
    then i 
    else raise Bad                  // expected to work
    // else raise ReallyBad         // expected to fail type checking
```
Then we get an error for the definition of `u` (with an incorrect range! You can verify it's in `u` by commenting it out.)
```
Raising.fst(11,27-11,34): (Error 19) could not prove post-condition
Verified module: Raising (271 milliseconds)
```
This is due to the fact that `raise` is underspecified (see `FStar.Exn` module). It has a **TODO** there saying we should refine its spec with the `Exn` monad, and if we do just that
```
assume val raise: e:exn -> Exn 'a (requires True) (ensures (fun r -> r == E e))
```
the updated file now has the behaviour you wanted.

I'll try to fix the first bit (it's wrong and annoying) and I'll investigate if there's any deep reason why the **TODO** was there instead of just being properly specified.

**Comment by mtzguido** [comment]
The underspec was simply an omission, and it's fixed now. You'll find it works in the tutorial console too.

There are still the error about the first argument and the incorrect range, so keeping open.

**Comment by WolframKahl** [comment]
Thank you very much!

**Comment by mtzguido** [comment]
Did some research. We indeed expect the first argument of an effect definition to be the *return type* of the computation. So this effect definition should fail, since the first argument is of type `exn`. However, what we should really be doing is checking that it's used appropriately, otherwise we permit unsoundness like this:
```
effect Ouch (a:Type) = Tot int
let x () : Ouch unit = ()
```
which succeeds. The assumption that the first argument == return type is so present that I couldn't find a way to get the int back out from `Ouch`. There's probably a way, though, and that opens Pandora's box to loss of type safety and proofs of false, so we should fix this.

The idea of improving the effect system, adding indices and making it more first class, has been circulating for a while. But for now, you're better off just flipping the arguments and remembering to play nice with the first one.

**Comment by mtzguido** [comment]
Even though I didn't prove false, I'm marking this as an unsoundness since this is very scary:
```
module Bug1370

effect Ouch (a:Type) = False

let x () : Ouch unit = () (* a proof of False? *)
```
Probably worth discussing at the all hands.

**Comment by mtzguido** [comment]
Part of the culprit is the logic in `solve_c`, which succeeds in subtyping `Tot unit` to `Ouch unit` only because `Ouch` is marked with the `Total` cflag. Removing the special-casing for `Total`, the definition of `x` fails. I'm not sure I know what each cflag exactly represents, so not touching for now.

**Comment by mtzguido** [comment]
We decided today to forbid this kind of effect declarations, by enforcing that the first argument on the LHS is used as the return type in the RHS. This case would fail since `a` is not `False`. Nik will work on it.

**Comment by nikswamy** [comment]
You're now forced to write:

```
effect Ouch (a:Type) = Tot False
```

making the computation type on the RHS explicit.

And then, further, this fails with

```
(Error 316) Result type of effect abbreviation `a` does not match the result type of its definition `Prims.l_False`
```

**Comment by nikswamy** [comment]
Can we close this now? @mtzguido

**Comment by mtzguido** [comment]
Yes, updating the test cases and closing soon.
