### ISSUE TITLE
Real infix operators don't work in some cases where backtick infix operators work

### ISSUE THREAD

**Issue by WolframKahl** [FStarLang/FStar#1371]
Below, I would expect everything to be accepted, but the commented-out variants are not accepted (in the on-line tutorial system):
``` fsharp
val o : #a:Type -> #b:Type -> #c:Type -> (b -> c) -> (a -> b) -> (a -> c)
let o #a #b #c g f = fun x -> g (f x)

val (~~) : #a:Type -> #b:Type -> #c:Type -> (b -> c) -> (a -> b) -> (a -> c)
let (~~) #a #b #c g f = fun x -> g (f x)

val f : int -> int
let f x = x

val g1 : int -> option int
let g1 = Some `o` f

(*
val g2 : int -> option int
let g2 = Some ~~ f
*)
(*
val g2 : int -> option int
let g2 = Some #int ~~ f
*)
(*
val h1 : int -> int
let h1 = f ~~ f
*)
val h2 : int -> int
let h2 = f `o` f

```
By the way, where is the lexical syntax of infix operators documented?

**Comment by mtzguido** [comment]
(Are the `~.` in your example meant to be `~~`?)

This is a precedence issue, `g2` is being parsed as `Some (~~ f)` instead of `(~~) Some f`. User-defined operators take their precedence from the first character of the operator: `~` in this case. It just so happens that `~` is a prefix operator, explaining why it's parsed like this. If you rename to `(++)`, you get the expected behaviour.

I don't think there's good documentation on this.

**Comment by WolframKahl** [comment]
(Sorry, the `~.` were indeed meant to be `~~` ─ fixed in the original post. I had suspected that the dot was part of the problem, due to the way spaces were added resp. not added in the error message.)

Thank you for the explanation!

Documentation is needed... Should I open a separate issue for that?

**Comment by msprotz** [comment]
how about https://github.com/FStarLang/FStar/wiki/Parsing-and-operator-precedence? feel free to fix/improve if need be!

**Comment by WolframKahl** [comment]
Ah! (Why didn't I find that when I searched for documentation of infix operators in F*?)

Thank you!
