### ISSUE TITLE
unexpected subtyping check fail

### ISSUE THREAD

**Issue by singhsanjana** [FStarLang/FStar#1400]
This is a snippet of my code that is throwig a subtyping check failed error

`module Ex02a

type type0 = (list nat)
type type1 = nat * (list type0)

let fn_aux (t1:type1)(t2:type1) : bool =
	match t1,t2 with
	| (_,[]),(_,[]) -> false
	| (_,[]),(_,_)  -> false
	| (_,_),(_,[])  -> false
	| (_,x::xs),(_,y::ys)  -> if (x = y) then true
	                            else false

let rec fn (q:type1)(p:type1) : bool =
    match q with
    | (x,[])     -> false
    | (x,y::ys)  -> if (fn_aux q p)
                    then true 
                    else (fn (x,ys) p)`

the error is:
`Ex02a(19,36-19,37): (Error 19) Subtyping check failed; expected type (p:Ex02a.type1{ %[ x, ys; p ] << %[ q; p ] }); got type Ex02a.type1 (see also Ex02a(14,32-15,4))
Verified module: Ex02a (1508 milliseconds)
1 error was reported (see above)`

I can't seem to understand how to proceed.

**Comment by nikswamy** [comment]
The error message is from the termination checker. 

It says that it cannot prove that the arguments to `fn` taken in lexicographic order are decreasing, i.e., it cannot prove that lexicographically ordered term `%[(x,ys);p]` is smaller than `%[q; p]`.

You can add an annotation to tell F* that the function terminates because the second component of `q` is indeed decreasing. Like so:

```
module Test

type type0 = (list nat)
type type1 = nat * (list type0)

let fn_aux (t1:type1)(t2:type1) : bool =
match t1,t2 with
| (_,[]),(_,[]) -> false
| (_,[]),(_,_) -> false
| (_,_),(_,[]) -> false
| (_,x::xs),(_,y::ys) -> if (x = y) then true
else false

let rec fn (q:type1)(p:type1) : Tot bool (decreases (snd q)) =
match q with
| (x,[]) -> false
| (x,y::ys) -> if (fn_aux q p)
then true
else (fn (x,ys) p)
```

**Comment by singhsanjana** [comment]
okay thanks.. I understand the problem now..
