### ISSUE TITLE
"let mutable" is broken 

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#1412]
At top-level it fails with 
```
ASSERTION FAILURE: Desugaring a let did not produce a let
F* may be in an inconsistent state.
Please file a bug report, ideally with a minimized version of the program that triggered the error.
```
An inner `let mutable` desugars to a non-existent `salloc` in `FStar.ST`:
```
(Error) Name "FStar.ST.salloc" not found
```

**Comment by msprotz** [comment]
it was originally written for JK who never used it; I'd be in favor of removing it since:
- it adds complexity in the compiler
- the usability of the feature is bad: you write "let mutable" but then you get errors about salloc
- you can always get the same thing, and understand what's going on, by writing salloc yourself

**Comment by s-zanella** [comment]
Removing it sounds good. As it is it just confuses people.

**Comment by nikswamy** [comment]
yes, let's just remove it, please.

**Comment by mtzguido** [comment]
`let mutable` is gone, and `mutable` is no longer a keyword (we can bring it back and fail on lexing.. if that's preferable)
