### ISSUE TITLE
Implicit resolution is poor when using erased implicits

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1418]
It's desirable to be able to use indexed types, and have the indexes be erased when extracting. For example, vectors can be defined as
```fsharp
module Vector

open FStar.Ghost

type vector (a:Type) : nat -> Type =
    | Nil : vector a 0
    | Cons: #l:erased nat
            -> hd:a
            -> tl:vector a (reveal l)
            -> vector a (reveal l + 1)
```

Inference fails when trying to use `Cons`, however:
```fsharp
let v1 : vector a 1 = Cons () Nil
```
```
(Error 189) Expected expression of type "Vector.vector (*?u5*) _ (FStar.Ghost.reveal (*?u6*) _)"; got expression "Vector.Nil" of type "Vector.vector (*?u8*) _ 0"
1 error was reported (see above)
```

The following succeeds, but fails if the `_` is changed to `Nil`:

```fsharp
val fold(#a #state:Type)(#l:erased nat):
    (state -> a -> state)
    -> state
    -> vector a (reveal l)
    -> Tot state (decreases (reveal l))
let rec fold #_ #_ #_ f s = function
    | Cons hd tl -> 
        fold f (f s hd) tl
    | _ -> s
```    

In order to have this sort of thing work correctly, the options I can see are to either automatically attempt to erase implicit, pure terms in the same way that implicit types are erased (so that the user doesn't need to use `erased` in code similar to the example given), or to make F*'s implicit resolution strategy controllable through tactics. 
Both would be somewhat desirable - it's very easy to generate inefficient extracted code accidentally if implicit type indexes are not erased, and having control over F*'s implicit resolution strategy would give Coq-style type classes "for free". 

If anyone else faces this issue, a partial workaround is to use an erased type as the index, and then define another type which erases the index, like so

```fsharp
type vector' (a:Type) : erased nat -> Type =
    | Nil : vector' a (hide 0)
    | Cons: #l:erased nat
            -> hd:a
            -> tl:vector' a l
            -> vector' a (hide (reveal l + 1))
    
type vector (a:Type) (n:nat) = vector' a (hide n)
    
let v1 : vector unit 1 = Cons () Nil

val fold(#a #state:Type)(#l:erased nat):
    (state -> a -> state)
    -> state
    -> vector' a l
    -> Tot state (decreases (reveal l))
let rec fold #_ #_ #_ f s = function
    | Cons hd tl -> 
        fold f (f s hd) tl
    | Nil -> s
```

**Comment by nikswamy** [comment]
> In order to have this sort of thing work correctly, the options I can see are to either automatically attempt 
> to erase implicit, pure terms in the same way that implicit types are erased (so that the user doesn't need 
> to use erased in code similar to the example given)

Implicits and erasure are orthogonal issues. Nothing prevents your code from being computationally dependent on an implicit argument. So, erasing it is not viable in general.

As for letting tactics control the way type inference works: it sounds like an interesting direction, but also quite challenging. At least in the current way things work in F*, I don't see a natural way to have tactics interpose on the strategy for inferring implicits. I've added it to a new issue on Meta-F* wish list: #1419

Finally, I like your `vector'` solution. Would you like to elevate the example to a wiki page describing a style for erased indices? If so, then I would suggest closing this issue.

**Comment by A-Manning** [comment]
> Nothing prevents your code from being computationally dependent on an implicit argument. So, erasing it is not viable in general.

That's not necessarily the case. It's not generally possible (or desirable) to erase implicits, however we can _attempt_ to erase implicits (of course, we could attempt to erase explicit arguments too). Where a function parameter is not used in the body of a function, it can be erased such that the type becomes generic (or Obj.t), and the parameter is replaced with a unit in extracted code, when instantiating implicits in order to invoke said function. As far as I understand this kind of erasure can be performed freely in pure code, and since it would improve performance of extracted code _and_ remove the need to handle erasure explicitly in many cases, I think it's worth considering.

> Would you like to elevate the example to a wiki page describing a style for erased indices?

A wiki page for erased indices is a good idea. The workaround I provided is fairly fragile and I would not advocate it as a general solution. In particular, the workaround fails if `vector' a l` is replaced with the equivalent `vector a (reveal l)` in the `val` declaration for `fold`. I'm not so sure why this is - adding an `unfold` qualifier to `vector` or triggering SMT patterns for `vector a (reveal l) == vector' a l` seems to have no effect. Do you have any suggestions regarding improving this workaround?

**Comment by aseemr** [comment]
The style is a bit heavy, in the following `Cons` branch works but `Nil` gives a typing failure: `Expected vector a (reveal l) but got vector' a (hide 0)`. My guess is we are not using SMT when checking the well-typedness of patterns, hence this fails, will need to see more.

```
let rec fold #a #state #l f s = function
    | Cons hd tl ->
        let l: erased pos = hide (reveal l) in
        fold #_ #_ #(elift1 #pos #nat (fun n -> n - 1) l) f (f s hd) tl
    | Nil #a  -> s
```

**Comment by aseemr** [comment]
My guess is this is the relevant code: https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.TcTerm.fs#L1595.

@nikswamy, is it unsound to use smt (and force the guard) there instead of using `teq_nosmt`?

**Comment by mtzguido** [comment]
Regarding controlling implicits through tactics, it's certainly feasible to do something in the same vein as Coq, Agda and Lean, which have a special kind of implicit which is to be solved by typeclass resolution, instead of unification. Having a single kind of implicit would be very weird in my eyes, and I think it would bring some pain. (For instance, would the tactics run after unification fails? I think that's only detectable at the top-level.)

Such special implicits could look something like `val f : ##(tau : t1) -> t2`, where if we need to instantiate `f` with an implicit, we call `tau` (in the proper context) to provide a witness of `t1`. Having typeclasses is then just adding some syntax to create record types and their members, and some default resolution tactic that searches the context for things marked as instances. Of course these arguments could also be given explicitly.

I'm unsure on whether allowing to annotate with whatever tactic can be accomplished (how would unification work?). But adding a "typeclass" kind, as other languages do, should be doable.

Also, note that doing typeclasses in this way hinders *canonicity*, which is the property that there is a single instance for a given class+type. Not having it means one can potentially have two (ways of building) instances for `Ord t`, which are reversed, and some program points use one and some the other. While this would be quite bad in languages like Haskell, it's usually not so bad in dependently-typed ones.

**Comment by mtzguido** [comment]
Related to #1844

**Comment by aseemr** [comment]
The original examples work as is now, my guess is because of automatic hide/reveal coercions. Adding a testcase for it and closing.
