### ISSUE TITLE
Support for parallel SMT solving ... make `--n_cores` great again

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#146]
I've got 8 hardware threads (4 cores) on my laptop, and 2/3(?) of the F\* checking time could run 8 times faster if parallelized. This could more than halve the time I need to wait.

**Comment by nikswamy** [comment]
Yes, indeed. This is very much on my TODO list and will not be hard to implement (although not trivial either).

**Comment by catalin-hritcu** [comment]
Nik implemented something on this with the `--n_cores` flag. It doesn't yet work with the ocaml build afaik. More importantly, some of the students in the SB class reported a **slowdown** as they added more cores. Is anyone successfully using this to speed things up?

**Comment by catalin-hritcu** [comment]
Tried a bit, and on `f-omega.fst` there is a significant speed-up using 4 cores (x2.5 times or so). On (the two variants of) lambda omega there is no noticeable change though. To put it in other words: inefficient proofs seem to benefit a lot more from this than efficient ones, which is probably unsurprising.

**Comment by catalin-hritcu** [comment]
I've just tried `--n_cores 4` for the native binary and `f-omega.fst` and it loops forever, so can I assume that the OCaml tool-chain still doesn't support `--n_cores 4`? What would it take to support?

**Comment by catalin-hritcu** [comment]
`--n_cores` still loops with the OCaml binary. At this point we're only getting parallelism for multiple F* files via `make -j`, which is still suboptimal for interactive development.

**Comment by catalin-hritcu** [comment]
Funny enough, now even the F# binary gets stuck after successfully verifying something with `--n_cores`:
```
[hritcu@detained pub]$ fstar.exe --n_cores 4 examples/bug-reports/bug152.fst                                             (git)-[catalin_private] 
Verified module: Bug152 (338 milliseconds)
All verification conditions discharged successfully
^C
```

**Comment by shaolintl** [comment]
Problem: using --n-cores m for m > 1 does not work on the ocaml compiler
When running with this flag option, the compiler hangs.
Reason: each thread was looping infinitely searching for jobs. Adding a small wait call solved this problem.

Does it help? No, since Ocaml has a single-threaded VM. Therefore, the current approach of using looping threads on a shared job list will not improve performance. There is talk of changing the VM to multi-threaded in 4.06 . This won' help us for now and might also cause a decrease in ocaml performance.

@catalin-hritcu @nikswamy 
Ocaml currently supports concurrency via starting new processes (without shared memory). I can probably support that using the Unix module (every call get its own process). Are we expecting ocaml-F* to work on Windows? Outside of cygwin? I think that Enrico Tassi has implemented it for Coq. This will diverge though from the F# interface and therefore will require more changes to the F* files.
One option is to push the entire n-cores code into the ocaml/F* files.
As Catalin has mentioned, it sometimes hangs, after SMT has finished, on the F# version.
What are your thoughts? Do you still want to include it in the coming release?

**Comment by msprotz** [comment]
Yes, F*-OCaml is the primary version for many of us. Cygwin is just our work environment to get make, sed and the like -- we use the native Windows toolchain of OCaml.

The solution as we discussed it is to use Unix (i.e. win32unix, the emulation of the Unix library module for the native Windows toolchain) to push all the --n-cores specific code into the F*/OCaml files. The right way to do it is indeed to start several processes.

@ad-l claims he has this code written somewhere already.

Thanks for looking into it!

Jonathan

**Comment by catalin-hritcu** [comment]
About the release, that's already on Monday, so we'll probably miss that.

**Comment by shaolintl** [comment]
Ok. I will just merge to master the small fix preventing --n_cores > 1 from hanging on ocaml (got CI green light) and wait for @ad-l feedback about how to proceed.

**Comment by shaolintl** [comment]
n-cores seems to work now, at least on my machine. The ocaml version probably doesnt work very well on native windows. I didnt try that but if there is a problem, I can try to look at that.

There is a blocking bug #846 since in some cases the "fresh" theory which is given to the SMT solvers lacks some declarations.

I did some small changes and it may be that the F# multi-core version works as well.

**Comment by catalin-hritcu** [comment]
@wintersteiger @shaolintl Can't yet try this because the OCaml version of F* seems broken on master. Still, I expect should be able to close this soon if it's able to do the whole F* test suite, right?

**Comment by shaolintl** [comment]
Yes, since this feature is optional, we think it would be best to let people use it and wait for feedback. If the whole test suite passes with this feature, it can certainly be closed.. I will also broadcast this feature on the main channel

**Comment by beurdouche** [comment]
Something that would be very nice to have is to have F* detect the max number of cores on the machine automatically if no argument is provided to the option :)

It would make our Makefiles portable and avoid us to hardcode a specific number

**Comment by catalin-hritcu** [comment]
This now works on all our `uregressions` test suite (with only one exception that I've filed here #926). Closing.
