### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by wintersteiger** [FStarLang/FStar#1523]
I don't expect this to work as the implicit `n` can't be inferred:

```
module Bug
open FStar.UInt
let _ =  assert (forall i. add_mod (lognot i) 1 = sub_mod 0 i)
```

But, it currently triggers an assertion violation:

```
(Error) ASSERTION FAILURE: (<input>(3,36-3,42)) CheckNoUvars: Unexpected unification variable remains: (*?u4330*) _
F* may be in an inconsistent state.
```

**Comment by mtzguido** [comment]
A smaller repro:
```f#
assume val f : #a:Type -> list a -> list a
let _ =  assert (l_Forall (fun i -> f i == f i)) // just what (forall i. f i == f i) desugars to
```
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("(A.fst(4,36-4,37)) CheckNoUvars: Unexpected unification variable remains: (*?u17*) _")
```
What I think is happening is that the typechecker is elaborating the assertion to:
```f#
l_Forall #?u1 (fun (i:?u2) -> eq2 #?u3 (f #?u4 i) (f #?u5 i))
```
and then solving each of them, via a new uvar
```f#
l_Forall #(list ?u17) (fun (i:list ?u17) -> eq2 #(list ?u17) (f #?u17 i) (f #?u17 i))
```
which is not being tracked in the internal guards.

**Comment by mtzguido** [comment]
I thought the culprit was here https://github.com/FStarLang/FStar/blob/b7f9e289a5ec788bddbe04d435d609dedc12e2dd/src/typechecker/FStar.TypeChecker.Rel.fs#L1695-L1706 where its ignoring the `implicits` returned by the call to `solve_t`. Adding those implicits to the worklist gives saner errors for both programs above, but memory usage explodes wildly. Also, other places seem to ignore them, so it might be that I'm interpreting incorrectly. Anyway, that tip might help :)
