### ISSUE TITLE
Functional equality vs. Opaque

### ISSUE THREAD

**Issue by parno** [FStarLang/FStar#1529]
We have, historically, found it handy to be able to selectively hide and reveal function definitions, without the need for an explicit interface or duplicating the arguments and body of the function (e.g., in a lemma).  At the moment, in F*, our approach is to use:

```
assume val make_opaque : #a:Type -> a -> a
assume val reveal_opaque : #a:Type -> x:a -> Lemma (x == make_opaque x)
```

However, this seems to produce some surprising, or at least counter-intuitive results.  I've tried to summarize some of them below, using F* commit `351dbdec0ec9f67fc2bbf57e787d14bdbd64bb22`.

In the example with `f`, asserting `==` fails with and without `assert_norm`.  Oddly `assert_norm` does work in the example with `g`, where the only difference, I think, is that F*/Z3 knows more about `f` than it does about `g`.  

The example with `h` suggests that we might be better off using `unfold` whenever we make something opaque, since both forms of equality and both forms of assertion seem to succeed.

Finally, the example with `m`, which is the only one that takes more than one argument, shows that `assert_norm` can prove equality, `feq` can't, unless you curry the first argument.  Without using `assert_norm`, I'm not sure how you get from the curried version to the full function equality.

Any thoughts or other suggestions for how to define opaque functions would be much appreciated.

```
module T

assume val make_opaque : #a:Type -> a -> a
assume val reveal_opaque : #a:Type -> x:a -> Lemma (x == make_opaque x)

let f (x:int) : int = 5

let f_opaque = make_opaque f

open FStar.FunctionalExtensionality

let test_f () =
  reveal_opaque f; 
  //assert (f == f_opaque);  // Fails #1
  //assert_norm (f == f_opaque);  // Fails #2 
  assert (feq f f_opaque);   // Succeeds
  assert (f == f_opaque);    // ==> Makes this succeed
  ()

//////////////////////////////////////////

assume val g (x:int) : int

let g_opaque = make_opaque g

open FStar.FunctionalExtensionality

let test_g () =
  reveal_opaque g; 
  //assert (g == g_opaque);  // Fails 
  assert_norm (g == g_opaque);  // Succeeds: Why, when #2 above fails?
  assert (feq g g_opaque);   // Succeeds
  assert (g == g_opaque);    // ==> Makes this succeed
  ()

//////////////////////////////////////////

assume val h (x:int) : int

unfold let h_opaque = make_opaque h

open FStar.FunctionalExtensionality

let test_h () =
  reveal_opaque h; 
  assert (h == h_opaque);       // Succeeds, thanks to the unfold above?
  assert_norm (h == h_opaque);  // Succeeds
  assert (feq h h_opaque);      // Succeeds
  ()

//////////////////////////////////////////

assume val m (x y:int) : int

let m_opaque = make_opaque m

let test_m (x:int) =
  reveal_opaque m;
  //assert (m == m_opaque);  // Fails
  //assert_norm (m == m_opaque);  // Succeeds
  //assert (feq m m_opaque); // Fails
  assert (feq (m x) (m_opaque x));  // Succeeds
  //assert (feq m m_opaque);   // Fails, even with line above uncommented
  ()
```

**Comment by aseemr** [comment]
Hi Bryan:

I can try to explain what's happening. Most of the time, for functions, their encoding to SMT is of the form `forall x. f x = <some term>` -- even when the source program contains code like `let f = g`. In some cases, F* does eta-optimization to encode them as `f = g`, but usually not a good idea to rely on it. Rather, `FunctionalExtensionality.feq` is the safest bet.

Consider the first example:

```
module Test

assume val make_opaque : #a:Type -> a -> a
assume val reveal_opaque : #a:Type -> x:a -> Lemma (x == make_opaque x)

let f (x:int) : int = 5

let f_opaque = make_opaque f
```

F* encodes `f_opaque` to smt as:

```
forall x. f_opaque x = (make_opaque f) x
```

So when we do this later:

```
open FStar.FunctionalExtensionality

let test_f () =
  reveal_opaque f; 
  assert (f == f_opaque)
```

The assertion fails because without functional extensionality, the formula `f = make_opaque f ==> f = f_opaque` (where the L.H.S. comes from the lemma) is not provable. Had F* eta-optimized the encoding of `f_opaque` to say `f_opaque = make_opaque f`, this would have succeeded.

The `assert_norm` case:

```
assert_norm (f == f_opaque)
```

is similar. It generates a query: `f = make_opaque f ==> (fun x -> 5) = make_opaque (fun x -> 5)`, which is even more pathological because `f` has been expanded to its lambda form.

Instead of normalizing it wholesale using `assert_norm, if we just normalize `f_opaque`:

```
assert (f == norm [delta_only [`%f_opaque]] f_opaque)
```

Then this goes through, since the query presented to smt is: `f = make_opaque f ==> f = make_opaque f`, as `f_opaque` is unfolded by the normalizer.

====

In the `g` case, `assert` fails for the same reason as `f`.

`assert_norm` succeeds, since it is morally same as selective normalization in the case of `f` (since `g` is `assume val`, it is not unfolded, so only `g_opaque` is unfolded).

====

In `h`, since we mark `h_opaque` as `unfold`, even with `assert`, F* inlines `h_opaque` and then it is same as `assert_norm` in `g` case.

====

In the `m` case, as you already guessed, we would need to invoke functional extensionality twice. But the following snippet doesn't work, since the first assertion is talking about a specific `x`:

```
let test_m (x:int) =
  reveal_opaque m;
  assert (feq (m x) (m_opaque x));
  assert (feq m m_opaque);
  ()
```

If instead, we quantify `x`, then it works fine:

```
let test_m () =
  reveal_opaque m;
  assert (forall x. feq (m x) (m_opaque x));  //x is quantified
  assert (feq m m_opaque);   //now this works
  ()
```

**Comment by aseemr** [comment]
Is smt context the main reason behind using `opaque`? If so, then something like following can also be used:

```
module Test

[@"opaque_to_smt"]
let foo (x:int) :list int = [x; x; x]

let test_f () :Tot unit =
  let f_local (x:int) = normalize_term (foo x)  in
  assert (List.Tot.length (f_local 2) == 3)
```

Since `foo` is `opaque_to_smt`, it won't be encoded to the solver, but it can selectively normalized using `norm` functions.

Ideally we could write:

```
module Test

[@"opaque_to_smt"]
let foo (x:int) :list int = [x; x; x]

let test_f () :Tot unit =
  let f_local = normalize_term foo  in
  assert (List.Tot.length (f_local 2) == 3)
```

So that we don't have to duplicate the arguments -- but this doesn't currently work, I will see why.

**Comment by aseemr** [comment]
We can make the style of the last snippet above work:

```
module Test

[@"opaque_to_smt"]
let foo (x:int) :list int = [x; x; x]

let test_f () :Tot unit =
  let f_local = normalize_term foo  in
  assert (List.Tot.length (f_local 2) == 3)
```

I have a local fix. Would that style be fine with you @parno.

**Comment by parno** [comment]
Hi Aseem,

Thanks for the detailed explanations!  Just to summarize, you're saying that the `==` examples (e.g., for `f` and `g`) fail because the encoding of `f_opaque`, for example, obscures the direct equality the `reveal` lemma tries to establish, and hence the only way to establish equality is via `feq`.  The `assert_norm` fails for `f` because the normalizer goes too far, while for `g`, it happens to do just the right amount because `g`'s definition is hidden.  The `h` case makes sense too; it just requires a quantification step to work through the `feq` steps.

Thanks also for the suggestion of using `opaque_to_smt` and `normalize_term` as an alternative to our approach to `opaque`.  I think that would work in some situations, but perhaps not all of the places where we currently use `opaque`.  For example, in the case of SHA, Jonathan's spec is, in some places, very recursive (e.g., https://github.com/project-everest/hacl-star/blob/fstar-master/specs/Spec.SHA2.fst#L166), and that plus some over-excitable triggers in `FStar.UInt` seem to lead to F*/Z3 being unable to prove basic facts if `ws` is anywhere in the context when fuel is non-zero.  To be able to make progress in the Vale context (where we sometimes need some fuel), we define an opaque version locally and then reveal it selectively.  The nice thing is that it doesn't require changing Jonathan's spec or any code that depends on it.

In places where we both define the function and make it opaque, you style should work nicely.

Thanks again!
-Bryan

**Comment by parno** [comment]
Cool, thanks!  I'll try to give it a shot.
