### ISSUE TITLE
On Linux, F# build of F* does not work with F# versions beyond 4.1.18

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1539]
I've recently tried various F# versions to build F* and version F# 4.1.18 worked, but the following more recent versions **did not work**:
- F# 4.1.23
- F# 4.1.34
- F# 4.5.0

The problem is always with FSharp.Core.dll not being properly found at runtime (and sometimes also compile time):
- [error message for F# 4.5.0](https://gist.github.com/catalin-hritcu/dce5cfa7f62dae7d753fbe5713e77ef8)

Some more information about my configuration:
- mono 5.14
- msbuild 15.8

**Comment by baronfel** [comment]
I did a bit of digging on my mono 5.12 ubuntu machine, and what I find when I run the build at a higher verbosity (`msbuild /verbosity:diag /p:Configuration=Release VS/FStar.sln`) is that the FSharp.Core dependency cannot be found during the build.  This doesn't break the build because it doesn't look like FStar has a direct dependency on FSharp.Core, rather it needs it as an extraction-dependency.

A few releases ago, FSharp.Core was removed from the Mono GAC.  I think to get this working again, you'll need to use FSharp.Core from Nuget(https://www.nuget.org/packages/FSharp.Core/) as you would any other dependency. That will require adding it to the dependency mechanism and then adding the old-style Reference-with-hintpath Xml nodes to the project(s) that requires it.

**Comment by baronfel** [comment]
I can verify that this fixes the problem. Steps to resolve:

* Add `FSharp.Core` to the packages.config (which apparently is hosted in src/parser/packages.config?). You are free to pick whichever version you like, but the last-working seems to have been 4.1.18 per this bug report, and anyway when this is fixed you can more easily upgrade versions)
* Add the following stanza to all fsproj files (both to ensure that this FSharp.Core is used at build-time and to ensure that this FSharp.Core is copied to the output directory). If this is not done it is possible to use the system FSharp.Core (ie the one colocated with the compiler) instead of this package-referenced one, and thus get out-of-sync.

```xml
<Reference Include="FSharp.Core">
  <HintPath>..\VS\packages\FSharp.Core.4.1.18\lib\net45\FSharp.Core.dll</HintPath>
  <Private>True</Private>
</Reference>
```

This should resolve the build issues and continue to make FSharp.Core.dll present in the bin directory alongside the built fstar.exe binary.

In addition, I would encourage you to migrate if possible to the newer-sdk project files, which use the `dotnet` CLI to build.  In that scenario you retain the ability to build for net45 targets, but gain much easier package management and smaller, less error-prone project files overall.

**Comment by baronfel** [comment]
For reference, I think this issue is the root cause: https://github.com/fsharp/fsharp/issues/768

**Comment by catalin-hritcu** [comment]
@baronfel Many thanks. It would be great if you could send a pull request with the proposed fixed. This will require some serious testing from the whole team.

As for migrating to "newer-sdk project files", hope that more knowledgeable team members can comment on this, for instance: @aseemr @nikswamy @wintersteiger @BarryBo
