### ISSUE TITLE
Wrong verification in tutorial

### ISSUE THREAD

**Issue by fstiffo** [FStarLang/FStar#1546]
The following code returns `All verification conditions discharged successfully` in the tutorial:
```
module Ex03a
//factorial-types

open FStar.Mul

(* What are some other types you can give to factorial?
   Try writing them and see if F* agrees with you. *)


val factorial: nat -> Tot (y:int{y>=0})    
let rec factorial n = 
  if n = 0 then 1 else n * (factorial (n - 1))
```

**Comment by mtzguido** [comment]
Hi Francesco, thanks for the report. Can you say why you think this is wrong? It seems correct to me.

**Comment by fstiffo** [comment]
`Tot (y:int{y>=0})` is compatible with a function that returns values all >= than 1?

**Comment by catalin-hritcu** [comment]
> `Tot (y:int{y>=0})` is compatible with a function that returns values all >= than 1?

It might not intuitively be "the best" specification for this function, but it's a correct specification.

In general, there is no such thing as "the best" specification anyway, at least not in terms of pre- and post-conditions. Since one could strengthen (or weaken) both the pre- and post-condition to obtain something incomparable.
