### ISSUE TITLE
Unsoundness or at least unexpected behaviour when admitting a function used in refinement

### ISSUE THREAD

**Issue by SECtim** [FStarLang/FStar#1556]
Using the following F* version (the docker nightly):
```
F* 0.9.7.0~dev
platform=Linux_x86_64
compiler=OCaml 4.05.0
date=2018-10-04T09:44:36+0000
commit=d8787574f4a7488d19a5a2bdd05781064e9c827f (dirty)
```

The following module type checks without errors, though the implementation of `client` (last line) obviously shouldn't (see the refinement on its return type):

```fstar
module SomeBug

type id = int

type role =
  | Client: role
  | Server: role
  
val id_to_role: id -> role
// If I put some implementation here (like "if e = 0 then Server else Client"), the type check fails as expected
let id_to_role e = admit()

// If I remove the refinement on server_entity or client_entity, the type check fails as expected
type server_entity = e:id{id_to_role e = Server}
type client_entity = e:id{id_to_role e = Client}

type client_data =
  | ClientData:
      server: server_entity ->
      client_data

type client_state =
  | ClientState:
      client_dataset: list client_data
// If I remove this length refinement, the type check fails as expected
        { List.Tot.length client_dataset > 0 } ->
      client_state

val client:  
  id: client_entity ->
  input_state: client_state ->
  optional_output: option (int) {False}

let client id input_state  =
  Some 1 // or None, doesn't matter
```

We first suspected the `admit()` might somehow disable all refinements (if that's the case, at least a clear warning should be issued), but the following module does NOT type check (as one would expect):
```fstar
module FailsAsExpected

type id = int

type role =
  | Client: role
  | Server: role

val id_to_role: id -> role
let id_to_role e = admit()

val test: cid: id{id_to_role cid = Client} -> oop: option int {False}
let test id = Some 1
```

In any case: If the admit somehow leads to ignoring refinements on a completely different function, this is unexpected to say the least - and if it is intentional, I think a warning would be appropriate.

**Comment by aseemr** [comment]
Hi @SECtim:

An inconsistency is introduced in the logic as soon as types `server_identity` and `client_identity` are defined:

```
val id_to_role: id -> role
let id_to_role e = admit()

type server_entity = e:id{id_to_role e = Server}
type client_entity = e:id{id_to_role e = Client}

let foo (x:server_entity) (y:client_entity) :squash False = ()
```

The reason is that, F* encodes a definition of `id_to_role` as `admit`, which is a constant symbol. And then, the refinements on the types `server_identity` and `client_identity` are saying that `Server = admit` and `Client = admit`, meaning `Server = Client`. This is a contradiction to the distinctness of data constructors `Server` and `Client`.

In general, `admit`, `assume`, `magic` etc. are unsafe and can lead to such behaviors (unexpected proofs of `False` in a different function, for example).  It is hard to track and contain such things in the logic.

As for the warning, they are highlighted in red color in the emacs editor. We could emit a warning on the command line too, but I don't know if that helps too much.

I am closing this issue for now. But happy to discuss more if needed.

Thanks!

**Comment by SECtim** [comment]
Thank you very much for your explanation, makes sense.
I understood "admit" as a way of telling F* "assume that this function may output everything that is allowable from its type" - but never thought about how this could be implemented (and thus whether my intuition was correct, which it obviously isn't).

**Comment by aseemr** [comment]
You could use `assume val id_to_role :id -> role` for that. And then, it is more like we don't know anything about this function. With this, the `False` proofs don't go through.
