### ISSUE TITLE
Lightweight indexed effects

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#1573]
In the past @nikswamy and @kyoDralliam tried to implement indexed effects (https://github.com/FStarLang/FStar/wiki/Indexed-effects, https://github.com/FStarLang/FStar/tree/nik_indexed_effects, https://github.com/FStarLang/FStar/tree/indexed_computation_types), but that turned out to be too complex and invasive. A lighter-weight proposal by @danelahman is currently under discussion. Hope that Danel can briefly explain his proposal and provide some pointers, so that we can track this feature here.

**Comment by danelahman** [comment]
Apologies for only now noticing this assignment.

In short, the idea stemmed from the observation that the WPs in F* form a monad, but (in theory) there is nothing forcing one to work with only the WPs we derive in the DM4F style. One natural option is to apply the reader monad transformer to our existing WPs, essentially extending the WP-calculus with a notion of environment. And one thing this additional environment turns out to be good for is encoding indexed effects.

For a nice example, one can look at [examples/indexed_effects/IMST.fst](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IMST.fst) for a state-and-preorder indexed monotonic state monad encoded in this style:

- [line 16](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IMST.fst#L16) contains the usual ST WP extended with two additional indices, one for the state type and one for the preorder
- [line 113](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IMST.fst#L113) demonstrates how one can encode the state-and-preorder indices and the standard ST WP in terms of our extended WP 
- [line 142](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IMST.fst#L142) then contains a small example monotonic counters program written using this encoding

Another nice example is that of allowed exceptions indexed exception effect in [examples/indexed_effects/IEXN.fst](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IEXN.fst). Again, the idea is to apply a suitable reader monad transformer to the standard exceptions WP calculus.

**Comment by danelahman** [comment]
In principle one can also include some amount of subtyping on such effect indices. However, one needs to be careful with that. For example, (to my knowledge) one of the original motivations for indexed effects was the state-and-preorder indexed effect, with the hope that perhaps we can also sub-type the preorder index. 

To this end, in [examples/indexed_effects/IMSTsub.fst](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IMSTsub.fst) I demonstrated that it is indeed possible to subtype (at least proposition/predicate like) the encoded effect indices. Unfortunately, I also demonstrated that subtyping the preorder index is inconsistent with the witness-recall mechanism, see [line 161](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/IMSTsub.fst#L161).

**Comment by danelahman** [comment]
Finally, in addition to using the reader monad structure to encode indices, one can play a similar game by applying the writer monad transformer to the standard WPs and get a [graded monads](https://dl.acm.org/citation.cfm?doid=2535838.2535846) style effect-indexing (where the index of sequential composition is the monoidal composition of the indices of the sub-computations). 

Some initial exploration in this direction can be found in [examples/indexed_effects/GEXN.fst](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/GEXN.fst) and [examples/indexed_effects/GMST.fst](https://github.com/FStarLang/FStar/blob/master/examples/indexed_effects/GMST.fst).

**Comment by nikswamy** [comment]
We now have full-blown indexed effects with @aseemr's work on layered effects.

I'm closing this as an issue, though it's still of course an interesting alternate direction.
