### ISSUE TITLE
Bug when combining pattern matching and lambda functions

### ISSUE THREAD

**Issue by jaybosamiya** [FStarLang/FStar#1616]
```
let rec bug x =
  match x with
  | _ -> (fun y -> y)
```

gives

```
ASSERTION FAILURE: Changing a fixed uvar! ?31

F* may be in an inconsistent state.
Please file a bug report, ideally with a minimized version of the program that triggered the error.
```

**Comment by mtzguido** [comment]
Still present, and scary.

**Comment by mtzguido** [comment]
This happens since the unifier needs to solve a problem of shape `?30 = ?30` and goes into the generic flex-flex case, which will compute solutions for both sides and set them, hence setting `?30` twice.

This patch to succeed early in cases like this fixes the problem. But this should probably be fixed in the `solve_t_flex_flex` function, and I'm not sure if this is actually correct. Maybe @nikswamy knows?
```diff
diff --git a/src/typechecker/FStar.TypeChecker.Rel.fs b/src/typechecker/FStar.TypeChecker.Rel.fs
index d2c1f7c0bd..da70e31f1f 100644
--- a/src/typechecker/FStar.TypeChecker.Rel.fs
+++ b/src/typechecker/FStar.TypeChecker.Rel.fs
@@ -2760,6 +2760,9 @@ and solve_t' (env:Env.env) (problem:tprob) (wl:worklist) : solution =
                solve env (attempt [base_prob] wl)
         else fallback()
 
+      | Tm_uvar u1, Tm_uvar u2 when U.term_eq t1 t2 ->
+        solve env (solve_prob orig None [] wl)
+
       (* flex-flex *)
       | Tm_uvar _,                Tm_uvar _
       | Tm_app({n=Tm_uvar _}, _), Tm_uvar _
```

With the patch we get this error instead:
```
B.fst(4,4-5,27): (Error 112) From its type x: _ -> Prims.Tot (_: _ -> Prims.Tot _), the definition of `let rec f` expects a function with 4 arguments, but 3 arguments were found
```
(2 args are implicit)

There is a similar early-success in the unifier using physical equality of both sides. 
```f#
if BU.physical_equality problem.lhs problem.rhs then solve env (solve_prob orig None [] wl) else
```
So I suppose we are doing this already many times, and this example just shows a case that slips past the physical equality optimization.

**Comment by mtzguido** [comment]
This was actually a lot trickier. The root of the problem was a uvar-uvar case where the uvars had a substitution accumulated. The code for flex-flex:
```fstar
      (* flex-flex *)
      | Tm_uvar _,                Tm_uvar _
      | Tm_app({n=Tm_uvar _}, _), Tm_uvar _
      | Tm_uvar _,                Tm_app({n=Tm_uvar _}, _)
      | Tm_app({n=Tm_uvar _}, _), Tm_app({n=Tm_uvar _}, _) ->
        let f1, wl = destruct_flex_t t1 wl in
        let f2, wl = destruct_flex_t t2 wl in
        solve_t_flex_flex env orig wl f1 f2
```
Was calling destruct twice. The first call, on the uvar `?1[s]` was creating a new `?2` and solving `?1` to some application of `?2`. Now the second call was again on `?1`, but it calls compress so it was seeing an application of `?2`, again with a substitution on it (since the subst gets propagated). Now it was also generating a new variable `?3` and solving `?2` to `?3` (without applying, since there was no need), and then `solve_t_flex_flex` would explode since it is called on `?2` and `?3`, with `?2` already solved.

In the case where the substitutions matched on both sides (like this one), the second call was being silly since the substitution was trivial (it mapped every x to itself), so it could have finished early without setting anything, which would have fixed this issue.

However, if the substitutions differed, that was not enough. My solution is to first ensure the uvar on the left is not affected by a substitution, then do it for the right uvar, and only after that;s done destruct the problem into its components. It does a few more passes on the term, but doing all at once would have caused some duplication, and this is tricky code so I'd rather do this. Posting a PR for review.
