### ISSUE TITLE
Issue with ALL_FST_FILES and ALL_UNCHECKED_FST_FILES

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#1688]
F* currently emits two variables `ALL_FST_FILES` and `ALL_UNCHECKED_FST_FILES` in the output of dependence analysis. `ALL_FST_FILES` contains all the files that were scanned and `ALL_UNCHECKED_FST_FILES` contains all those scanned files for which the corresponding `.checked` file doesn't exist -- this is just whether the `.checked` file exists or not, a file `A.fst` will _not_ be included in this list even if the existing `A.fst.checked` is stale.

The makefiles then use the variable `ALL_UNCHECKED_FST_FILES` to build the projects, something like:

```
verification: $(addprefix $(CACHE_DIR)/,$(notdir $(addsuffix .checked,$(ALL_UNCHECKED_FST_FILES))))

%.checked: | .depend.$(IMPL_CHOICE) $(CACHE_DIR) $(OUTPUT_DIR)
	$(FSTAR) $< && \
	touch $@
```

This works fine for clean builds where there are no already existing `.checked` files. But it is a problem for incremental builds. Consider for example a setting with some already existing stale checked files. If we verify again and run the dependence analysis first, F* will not emit the corresponding `.fst` files in `ALL_UNCHECKED_FST_FILES`, and so, they will not be re-built.

Earlier (when we had the copy semantics of `.checked` files), the makefile rules like above used to have the variable `ALL_FST_FILES` instead. But with no copy semantics (i.e. re-using the existing `.checked` files) that doesn't work. Here is an example:

Consider the case when we have already built `ulib` and are now generating `.depend` for a file `A.fst`, with `cache_dir` as `dir`. The output `.depend` would look something like:

```
<some_path>/FStar/ulib/prims.fst.checked: ...
... //other ulib files similarly

dir/A.fst.checked:  A.fst
  <some_path>/FStar/ulib/prims.fst.checked
  ... //etc.

ALL_FST_FILES = prims.fst \
  ... //other ulib files
  A.fst
```

Note that the `prims.fst.checked` has the prefix path for `FStar/ulib` and not `dir`. 

If in the makefile rule above, we now replace `ALL_FST_UNCHECKED_FILES` with `ALL_FST_FILES`, `make` would now try to build `dir/prims.fst.checked`, and F* would fail with `Error 5: no file specified`, since there is no rule defined for `dir/prims.fst.checked` and so the makefile variable `$<` would be empty.

This used to work before we got rid of the copy semantics since the `.depend` would have rules like `dir/prims.fst.checked: ...`, and F* would copy the checked files from `ulib` to `dir`.

Opening this issue for further discussions. cc @nikswamy, @protz, @s-zanella.

**Comment by msprotz** [comment]
So this basically means that projects need a way to express which .checked files are part of *their* build and should be rebuilt.

There are various ways of doing that. For instance, in HACL*, I list all the fst and fsti files in all the source directories, then append .checked: this is the list of all the stuff I want to generate.

Another way to do it is to take ALL_FST_FILES then filter-out the ones that appear in --already_cached; for instance, in HACL*, I could do: `$(filter-out FStar.% LowStar.% C.%,$(ALL_FST_FILES))`, since I expect these to be checked already, and the files that are part of my build are "the rest".

The latter can be done either within a Makefile, or, programmatically, by having F* emit ALL_FST_FILES *minus* the ones covered by --already_cached.

The question is: what style do we want to encourage? I'd be in favor of removing the variable and forcing projects to list all the files they want to verify via wildcards. Reduces the risk of "forgetting" to verify a newly-added file.

**Comment by nikswamy** [comment]
How about this variation, which elaborates on the previous comments:

1. fstar --dep full emits a variable ALL_FILES_TO_CHECK which is computed by subtracting from ALL_FST_FILES those files that are covered by --already_cached  (see Jonathan's remark above) and adding in all .fsti files that are also not covered by --already_cached. (Note, some .fsti files may lack .fst and we shouldn't forget to verify them also).

2. For any file covered by --already_cached, fstar --dep full *should not* emit a dependence rule for A.fst.checked (Aseem notices this behavior). These entries seem redundant ... and removing it would help reduce clutter in are (very large) .depend files.

Now, in some other makefile that uses a .depend produced by fstar, we can do something like what Aseem suggests

```
verification: $(addprefix $(CACHE_DIR)/,$(notdir $(addsuffix .checked,$(ALL_FILES_TO_CHECK))))
```

WDYT?

**Comment by nikswamy** [comment]
Another attempt after a phone call with Aseem.

Consider the following scenario:

Let's say we have

```
1/A.fst
1/cache/A.fst.checked

2/B.fst (which depends on A.fst)
2/cache
```

And we run

`fstar --dep full --include 1 --include 1/cache --include 2 --include 2/cache B.fst --cache_dir 2/cache`

This will emit:

```
1/cache/A.fst.checked: 1/A.fst

2/cache/B.fst.checked: 2/B.fst 1/cache/A.fst.checked
```

Now, according to my previous comment, the `ALL_FILES_TO_CHECK` variable would contain `1/A.fst 2/B.fst`. But, this is not usable, since under our current style of makefiles, we would use a single recipe for producing .checked files of the form

```
%.checked:
   fstar --cache_dir 2/cache --include 1 --include 1/cache --include 2 --include 2/cache $<
```

And using this recipe is not usable for producing `1/cache/A.fst.checked`


So, here's a revised proposal.

The main goal of emitting these variable that aggregate all files in the project is to make it convenient for a makefile author to ensure that all the files in their project are verified. As such, rather than emitting a variable that contains all the source files, how about emitting a variable that aggregates all the checked files that need to be produced which can then be used directly in a makefile recipe. i.e., something like this:

fstar --dep full emits:


```
ALL_CHECKED_FILES_TO_PRODUCE: 1/cache/A.fst.checked 2/cache/B.fst.checked 1/cache/C.fsti.checked ...
```

Then in a client Makefile that includes this .depend, we can do

```
verification: $(ALL_CHECKED_FILES_TO_PRODUCE)
```

And have a recipe to produce .checked files like so, which uses a new F* option `--cache_file <filename>` which provides the full path to the checked file that should be emitted, rather than just the directory.

```
%.checked:
    fstar $(INCLUDE_PATHS) $< --cache_file $@
```

In this style, the --cache_dir option is only provided during the dependence analysis. Other invocations of F* use --cache_file.

This style also has the advantage of ensuring that any .checked files that are present during the dependence analysis never get regenerated in a different location.

**Comment by nikswamy** [comment]
Yet another variation, this time thanks to a conversation with Jonathan.

---

The scenario in my previous comment should be considered anomalous. We found a .checked file for A.fst in a place that we didn't expect to find it. It should either be in the cache_dir, or there shouldn't be one at all.

So, if during dependence scanning we find a .checked file in a location that is unexpected (i.e, the module is not marked --already_cached and the .checked file is in a directory that doesn't correspond to the expected output location for this run, i.e., not in the cache_dir (or not alongside the file in case no cache_dir is set), then we raise a fatal error.

We will still emit an ALL_CHECKED_FILES variable, that mentions all .fsti.checked and .fst.checked files that need to be produced by the build.

Client makefiles can use this variable to ensure that they build and verify their entire project.

**Comment by nikswamy** [comment]
Ok, in trying this on miTLS, it's too aggressive to make finding a .checked file in an unexpected location a fatal error. I've made it a warning that can either be escalated to an error or silenced

**Comment by msprotz** [comment]
What's the issue in miTLS? We could take a look at it if it helps flipping this to an error by default

**Comment by nikswamy** [comment]
I have an everest green with this fix.

Making Warning 321 fatal is a nice long-term goal. But we're quite far from it right now. There are 199055 such warnings in an everest build with probably a dozen makefiles to blame. Let's fix it progressively.

```
(Warning 321) Did not expected Spec.Loops to be already checked, but found it in an unexpected location C:\cygwin64\home\everest\everest\kremlin\kremlib\Spec.Loops.fst.checked instead of obj\Spec.Loops.fst.checked
...
(Warning 321) Did not expected FStar.Pervasives.Native to be already checked, but found it in an unexpected location C:\cygwin64\home\everest\everest\FStar\bin\..\ulib\FStar.Pervasives.Native.fst.checked instead of ..\secure_api\out\runtime_switch\cache\FStar.Pervasives.Native.fst.checked
...etc.
```
