### ISSUE TITLE
Ill-kinded type error reported when assertion inside function definition fails inside stateful code

### ISSUE THREAD

**Issue by R1kM** [FStarLang/FStar#1704]
The following code fails with an Ill-kinded type error, instead of an assertion failure inside the inner lemma's precondition

```module Test

module HS = FStar.HyperStack
open FStar.HyperStack.ST

let f (u:unit) : Stack unit
 (requires fun _ -> True)
 (ensures fun _ _ _ -> True)
 =
 let aux () : Lemma
   (requires (assert (False); True))
   (ensures True)
   = () // Ill-kinded type error reported here, instead of assertion failure in the requires
 in ()
```

**Comment by catalin-hritcu** [comment]
Thanks for reporting. It seems that some amount of SMT encoding is happening even after an SMT query failed.
```
$ fstar.exe --debug Bug1704 --debug_level SMTEncoding bug1704.fst
[...]
Z3 says: unknown
Z3 says: unknown
Z3 says: unknown
Z3 says: unknown
bug1704.fst(10,1-14,6): (Info) SMT solver says: unknown because (incomplete quantifiers) (fuel=8; ifuel=2; )
bug1704.fst(10,1-14,6): (Info) SMT solver says: unknown because (incomplete quantifiers) (fuel=4; ifuel=2; )
bug1704.fst(10,1-14,6): (Info) SMT solver says: unknown because (incomplete quantifiers) (fuel=2; ifuel=2; )
bug1704.fst(10,1-14,6): (Info) SMT solver says: unknown because (incomplete quantifiers) (fuel=2; ifuel=1; )
@@@Encoding sigelt [@ (FStar.Pervasives.Comment "")]
visible let  f  : u690: Prims.unit -> FStar.HyperStack.ST.Stack Prims.unit = fun _ ->
  (let aux _ =
      ()
      <:
      Prims.Lemma Prims.unit
        (assert Prims.l_False;
          Prims.l_True)
        Prims.l_True
        []
    in
    ())
  <:
  FStar.HyperStack.ST.Stack Prims.unit
bug1704.fst(13,5-13,7): (Error 19) Ill-kinded type (see also bug1704.fst(11,21-11,28))
Verified module: Bug1704 (694 milliseconds)
1 error was reported (see above)
```
@aseemr might better know what's happening.

**Comment by aseemr** [comment]
Thanks @R1kM for the report!

Here is a minimal example:

```
module Test

let foo () : unit
 =
 let bar () : Lemma
   (requires (assert False; True))
   (ensures True)
   = admit ()
 in
 admit ()
```

The behavior is explainable. For the `requires` clause of the lemmas, F* tries to prove that they are of type `Tot Type0`. In this case, that generates a VC: `forall (u:unit). False` (from `assert False`), which is added to the VC of the lemma. And the label that F* adds to the VC is `Ill-kinded type`. Note also that `see also` part of the error message points to the `assert False`. In some sense this is more informative than `assertion failure` since it says that the type in question is `ill-kinded`. Would you prefer something like "Ill-formed type`?

I am closing this issue, but please reopen if you would like to see this changed somehow. Thanks again!
