### ISSUE TITLE
F# support library build issue

### ISSUE THREAD

**Issue by YezhouLiu** [FStarLang/FStar#1780]
Hi guys,

When I tried to build F# support library under ulib/fs folder, I got below errors.
Could you help me to have a look at it?

I'm using the released version of F* - fstar_0.9.6.0_Windows_x64.zip

D:\Fstar\ulib\fs>make
fsc --mlcompatibility -r:FSharp.Compatibility.OCaml.dll --nologo  --nowarn:0086 -a prims.fs st.fs all.fs io.fs
prims.fs(14,21): error FS0039: The type 'Z' is not defined.
prims.fs(14,40): error FS0039: The type 't' is not defined.
prims.fs(14,44): error FS0039: The type 't' is not defined.
prims.fs(14,21): error FS0039: The type 'Z' is not defined.
prims.fs(14,40): error FS0039: The type 't' is not defined.
prims.fs(14,44): error FS0039: The type 't' is not defined.

If I need to execute F* code (with F#), is it a must for me to build the support library first?

Many thanks,
Steve

**Comment by catalin-hritcu** [comment]
Generally the support for F# is quite a bit behind:
https://github.com/FStarLang/FStar/issues?q=is%3Aissue+is%3Aopen+fsharp+label%3Aarea%2Ffsharp-vs-ocaml
We can't even properly extract and build the "hello world" example:
https://github.com/FStarLang/FStar/issues/1087

@A-Manning might be able to give you a more precise answer

**Comment by mateuszbujalski** [comment]
I've a fix to make the ulib/fs compile again. I'm planning to set up a pull request for that, however before I do I wanted to ask some questions.

Currently there's an (outdated) makefile for compiling this library. On the other hand, the fstar compiler provides a solution file for working with .net. What's the preferred build tool for this? 

In general compiling ulib/fs requires a .net development environment, so a solution file could work fine. It would also make nuget dependencies easier to handle (currently there's just one dependency though). On the other hand I don't know the project very well and most likely I'm not aware of various restrictions (e.g. CI, other users?).

**Comment by nikswamy** [comment]
If it could be integrated with the .sln file, that would be great. Thanks!

**Comment by nikswamy** [comment]
We could just have an additional fsproj added in the sln file for building the library

**Comment by mateuszbujalski** [comment]
I thought that I should keep ulib and the F* solution separate. If you say that building them together is fine, that makes it a lot easier actually :) 

Few more questions:
1. Is it ok to update solution and projects to VS2019 and migrate to SDK projects? 
2. Since the project is meant to be cross-platform, I was wondering about setting a target framework to .netstandard1.1 (roughly equivalent to the net4.5 used currently). I don't think F* relies on any platform specific .net APIs, so it should be straighforward. Would there be a problem with that?
3. Are there any requirements around F# version used? I don't think there is any point in upgrading it as the syntax and features are restricted with what F* allows anyway. So I believe the best approach would be to target the lowest FSharp.Core possible.

**Comment by nikswamy** [comment]
Upgrading to VS2019: We discussed this recently and it is a problem. @tahina-pro Can you explain the difficulties, please?

For 2 and 3, yes, lowest possible dependences make sense

**Comment by nikswamy** [comment]
Thanks @mateuszbujalski!
