### ISSUE TITLE
Verification of Input & Output functions

### ISSUE THREAD

**Issue by jamesbarne** [FStarLang/FStar#1791]
Does F* supports any functionality that ties to the verification of input and output functions like ```fscan```, ```getchar``` in C (for KreMLin extraction)? 
Or is the practice to write an assumption of ```"input"``` instead.

**Comment by ad-l** [comment]
There is very little currently, so you have to write an `assume val` of your input function and plug in a C implementation. `FStar.IO` has a few functions like `read_line` but I'm not even sure which are implemented in kremlib. Because we distribute Low* code to many platforms we cannot write any platform-specific implementations in kremlib - although it may be OK to add libc functions like getchar

**Comment by catalin-hritcu** [comment]
@andricicezar recently started working on an IO library for ML extraction (https://github.com/FStarLang/FStar/compare/guido_effects...andricicezar:andrici_casestudy_dijkstra), but it will be a while until this is ready and it will anyway not help you with C extraction.

**Comment by aseemr** [comment]
Closing this issue.
