### ISSUE TITLE
Recursion through the store

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#1833]
It appears our friend Peter Landin made an unexpected visit. @kyoDralliam found that one can encode Landin's knot like quite straightforwardly like this:
```fstar
module Landin

open FStar.ST

let t' : Type0 = unit -> St unit

let knot () : St t' =
  let r = alloc #t' #(fun _ _ -> True) (fun () -> ()) in
  r := (fun () -> !r ()) ;
  !r
```
Now, `St` is not a `total` effect, but *that doesn't make a difference*. This is accepted even if marked as `total` (there is no `let rec` here to trigger the termination check anyway). We believe the real issue is accepting `t'` in `Type0`, when it has an implicit `heap : Type u#1` inside of it.

It appears that in DM4F we are computing the universes more properly, since this fails if added to `FStar.DM4F.Heap.ST`:
```fstar
let t' : Type0 = nat -> STNull nat
```
I think I remember we were unfolding the definition of `STNull` (passing via `ST`, `STATE` and the **user-defined** `STATE_h`) into its underlying representation when computing universes. 

Now, the `St` in the example comes from the **primitive** `STATE_h` effect (unrelated to the dm4f one), and has no repr. But perhaps its the `heap` index which should bump the universe level.

**Comment by aseemr** [comment]
Hi Guido, if I mark `ST` (and `GST`) as total in `FStar.ST`, then this fails (in fact `FStar.ST` itself doesn't typecheck). It has to do with how we compute the universe of a computation type. For non-total effects, we compute the universe of their computations to always be `Type0`, and so the example in your snippet succeeds. For total effects, we require that the effect must have an underlying `repr` that we can delegate the universe computation to. And so, when I mark `ST` total, I get the error about missing `repr`. Since DM4F effects always have a `repr`, this works as expected there.

**Comment by mtzguido** [comment]
Thanks Aseem, that makes sense, and sorry for the false alarm. My attempt was marking `STATE_h` as `total`, which doesn't make a difference, but I guess that's expected since `GST` is a `new_effect`?

**Comment by aseemr** [comment]
No worries :). Yeah, `ST` is also a `new_effect`, so we could try by just marking it `total`, but then F* raises a valid complaint that `GST`, a non-total effect, cannot be lifted to `ST`. So to get to the missing `repr` error, I had to mark `GST` also as `total`.
