### ISSUE TITLE
Stack overflow while trying to type-check the following program

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1840]
Hi,

The following program sends F* into a stack overflow.

Thanks,

Jonathan

```
module SO

open FStar.Tactics

let resolve' (): Tac unit =
  // dump "blah"
  let rec try_binders (bs: binders): Tac unit =
    match bs with
    | [] -> fail "found no suitable type class"
    | b :: bs ->
        let b, _ = inspect_binder b in
        try exact (pack_ln (Tv_BVar b))
        with | TacticFailure _ -> try_binders bs
  in
  try_binders (binders_of_env (cur_env ()))
```

**Comment by msprotz** [comment]
CC @mtzguido

**Comment by msprotz** [comment]
(note that the solution is to just not use a local let-rec)

**Comment by catalin-hritcu** [comment]
Could this be related to #1103 maybe? There are more problems with nested let recs though, like #851.

**Comment by mtzguido** [comment]
The problem here was a loop between the normalizer and the SMT encoding. When reifying the body of `try_binders`, the normalizer is called on it with `zeta` enabled. The normalizer does not loop, but the SMT encoding descends on the result, which includes another `try_binders` call, so this will loop. My fix was to disable `zeta` for this reification.

**Comment by msprotz** [comment]
Thanks Guido!
