### ISSUE TITLE
Add a new warning for unused rec keywords

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#1880]
There's a nice OCaml warning:
```
jonathan@genepi:/tmp $ echo "let rec f x = 0" > test.ml
jonathan@genepi:/tmp $ ocamlc -w A !$
ocamlc -w A test.ml
File "test.ml", line 1, characters 8-9:
Warning 39: unused rec flag.
```

I just got bitten by a definition that was marked with `rec` for no good reason, hence requiring a unit of 1 fuel, which puzzled me because knowing the body of the function, I assumed it was readily available to the solver (it was not, because I had fuel 0).

Since the consequences of superfluous rec keywords are more dire in F*, I would advocate for a warning in F* too.

Thanks,

Jonathan

**Comment by mtzguido** [comment]
I implemented this, it warns whenever a recursively-defined binding is not used in its body. There's a choice to be made for mutual recursion though, consider:
```fstar
let rec f x : Dv int = f (x + 1)
    and g x : Dv int = f x + f x
````

So `g` can be taken out of the recursive block, do we warn here? My current implementation does:
```
T.fst(4,8-4,9): (Warning 328) Global binding T.g is recursive but not used in its body
```
I think the warning makes sense since having `g` not recursive negates the need for `fuel`, as you found, but this seems like a style I would otherwise use otherwise at times, and then the warning would be annoying. OCaml seems to not warn in this case. Any prefrerences?

**Comment by msprotz** [comment]
I'm in favor of warning for the reason that the user is making their lives unnecessarily difficult, by gating reasoning about `g` over fuel 1 when it doesn't have to be this way. But I'll let others chime in.

Thanks! That's super useful and a big usability improvement.

**Comment by nikswamy** [comment]
This is nice, thanks Guido! Can we close the issue?

**Comment by mtzguido** [comment]
Fine by me!
