### ISSUE TITLE
Structures with proof information lose the proof

### ISSUE THREAD

**Issue by mariari** [FStarLang/FStar#1906]
It seems that when we construct a type with some kind of refinement or proof constraint, that this information goes away when we construct said type.

An example can be seen below.
```fstar

module Map = FStar.OrdMap

type total_order (a:eqtype) (f: (a -> a -> Tot bool)) =
   (forall a1 a2. (f a1 a2 /\ f a2 a1)  ==> a1 = a2)  (* anti-symmetry *)
 /\ (forall a1 a2 a3. f a1 a2 /\ f a2 a3 ==> f a1 a3)  (* transitivity  *)
 /\ (forall a1 a2. f a1 a2 \/ f a2 a1)                (* totality      *)

let string_cmp s1 s2 =  String.compare s1 s2 <= 0

(* The F* defn just calls down to OCaml, since we know comparison in OCaml is total
 * just admit it
 *)
val string_cmp_total : unit -> Lemma (total_order string string_cmp)
let string_cmp_total () = admit ()

type ti_globals = Map.ordmap string int (string_cmp_total (); string_cmp)

val empty_globals_wokrs_1 : ti_globals
let empty_globals_works_1 = Map.empty #string #int #(string_cmp_total (); string_cmp)

// val empty_globals_fail : ti_globals
// let empty_globals_fail = Map.empty

val string_cmp_total_smt : unit -> Lemma (total_order string string_cmp) [SMTPat (string_cmp)]
let string_cmp_total_smt () = admit ()

val empty_globals_works_2 : ti_globals
let empty_globals_works_2 = Map.empty


val string_cmp' : Map.cmp string
let string_cmp' = string_cmp_total (); string_cmp

type ti_globals' = Map.ordmap string int (string_cmp')

val empty_globals_works_3 : ti_globals'
let empty_globals_works_3 = Map.empty

```
empty_globals_fail errors with the follow error message
```
(Error) Subtyping check failed; expected type OrdMap.cmp string; got type s1: string -> s2: string -> Prims.Tot bool; The solver found a (partial) counterexample, try to spell your proof in more detail or increase fuel/ifuel
Related location (C-c C-' to visit, M-, to come back): /home/redacted/.opam/4.07.0/lib/fstar/FStar.OrdMap.fst(27,44-27,59)
```

For this specific error, the error points to the `empty_globals_fail` itself, however on my own more complicated example, it points to the `string_cmp` in

```fstar
type ti_globals = Map.ordmap string int (string_cmp_total (); string_cmp)
```

the first working example shows that we can fill in the proof data that was forgotten

the second working example shows that if we have an SMT pattern it can fill it in for us.

The third working example shows that if we refine the type itself when defining it, it will also fill in the proof information for us.

**Comment by aseemr** [comment]
Hi, thanks for the report. This is the expected behavior, and you have already figured the ways this code can be made to work!

In the code, `string_cmp` has the type `string -> string -> bool`. Whenever `string_cmp` is used as a comparator for `OrdMap`, it incurs a proof obligation that `string_cmp` is a `total_order`. As you have observed, this is not provable without an assumption (e.g. `string_cmp_total`). So we need to have this assumption in the context whenever we have to prove `total_order` on `string_cmp`.

`empty_globals_works_1` explicitly invokes the lemma, which adds the assumption to the context, and hence the proof works. Adding an smt pattern adds a "hint" in the smt encoding that allows Z3 to prove the assumption by itself.

However the best solution is the `string_cmp'` ... i.e. annotate the type to specify that it is a total order, after which we don't need any smt pattern or explicit lemma invocations.

Hope that helps, please let us know if you still have questions.
