### ISSUE TITLE
Support for writing user-defined relations in decreases clauses

### ISSUE THREAD

**Issue by Kachoc** [FStarLang/FStar#1916]
The following minimal example leads to an unexpected failure:

```fstar
module Bug1

open FStar.All

val is_special_lex_t : lex_t -> GTot Type0
let rec is_special_lex_t x =
  match x with
  | LexTop -> True
  | LexCons y z ->  y == LexTop /\ is_special_lex_t z

type special_lex_t = x:lex_t{is_special_lex_t x}

(*
 * Evaluation of the below code generates the following error:
 * [> (Error) Unexpected output from Z3: (error "line 144750 column 49: unknown function/constant Prims.LexCons_uu___")
 *)
val preserve_is_special_lex_t : x:lex_t -> Lemma (is_special_lex_t x ==> is_special_lex_t (LexCons LexTop x))
let preserve_is_special_lex_t x =
  assert_norm(is_special_lex_t (LexCons LexTop x)); // the problematic line
  admit()
```

**Comment by nikswamy** [comment]
This can probably be easily fixed in the SMT encoding.

But, I wonder if a more stringent restriction on lex_t will serve us all better. I don't think we intended for any legitimate usage of `lex_t` as a data type with pattern matching etc. 

Instead, how about we revise `prims` so that we have

```
assume 
val lex_t : Type u#a

assume
val let lex_nil : lex_t u#a

assume 
val lex_cons (#a:Type u#a) (x:a) (tl:lex_t u#b) : lex_t u#(max a b)
 
assume
val lex_cons_precedes (#a #b:Type) (x:a) (y:b) (tl1 tl2:lex_t)
 : Lemma (x << y \/ (x === y /\ tl1 << tl2) ==> lex_cons x tl1 << lex_cons y tl2)
               [SMTPat (lex_cons x tl1 << lex_cons y tl2)]
```

This would forbid any sort of pattern matching on lex_t. 

It would make the axiom we introduce for the lex ordering evident in the prims source file (rather then buried in the .smt2).

WDYT? @aseemr @mtzguido others?

**Comment by mtzguido** [comment]
This new version of `lex_t` sounds fine to me.

But it got me thinking, perhaps we can postulate the axiom that `<<` distributes over constructors; i.e. that if for some `j` we have `a_j << b_j`, then 
```
   C a_0 ... a_(j-1) a_j a_(j+1) ... a_n
<< C a_0 ... a_(j-1) b_j b_(j+1) ... b_n
```
and then `lex_t` is just heterogeneous lists without any special support. And matching on it should be fine. (I haven't looked into this issue, but I suspect it's some special handling of `lex_t` that causes the problem.) Perhaps that's a bit heavy though, since it's a different axiom for every new constructor.

Anyhow, no strong feeling, so the `assume` solution looks good to me!

**Comment by mtzguido** [comment]
We've discovered today `lex_t` is pretty broken. We're repurposing this issue to remove most of the special handling of lex tuples.

There was an example from Son and Jay which constructed an infinite descending chain like this:
```fstar
LexTop >> LexCons 1 LexTop >> LexCons 1 (LexCons 1 LexTop) >> LexCons 1 (LexCons 1 (LexCons 1 LexTop)) >> ...
// or
%[] >> %[1] >> %[1;1] >> %[1;1;1] >> ...
```
relying on the fact that (at the time) `LexCons _ _ << LexTop` for any `_`. (In their example `1` was actually `LexTop` too, but I don't think that's central). The example can be found [here](https://github.com/FStarLang/FStar/blob/c681cccfc2af79606389bb9d0e95300f4d1e5d86/tests/bug-reports/BugLexTop.fst) and was fixed by removing the axiom about `LexTop` here 92e50f9b5ba34afe97b2cc09ba66dfa090438825.

However, we can still build an infinite descending chain with the *other* case of the lexicographic ordering, namely decreasing the head instead of the tail. Note that the following succeeds:
```fstar
LexCons 10 anything1 >> LexCons 9 anything2
// or:
%[10; (* ... anything1 ... *)] >> %[9; (* ... anything2 ... *)]
```
In particular, we can chose `anything2` to be a longer lex tuple, and generate a chain:
```fstar
LexCons 10 LexTop >> LexCons 9 (LexCons 10 LexTop) >> LexCons 9 (LexCons 9 (LexCons 10 LexTop)) >> ...
// or
%[10] >> %[9;10] >> %[9;9;10] >> ...
```
We can get a proof of false from this:
```fstar
let rec nines_and_tens (n:nat) : lex_t =
  match n with
  | 0 -> LexCons 10 LexTop
  | n -> LexCons #int 9 (nines_and_tens (n-1))

let rec decrease1 (n:nat) : Lemma (nines_and_tens (n+1) << nines_and_tens n) =
  match n with
  | 0 -> ()
  | n -> decrease1 (n-1)

let rec falso (n : nat) : Lemma (ensures False) (decreases (nines_and_tens n)) =
  decrease1 n;
  falso (n+1)
```

Note this is actually well known: the lexicographic ordering on *lists* is not well founded, but it is for tuples of any given *fixed* length.

We chatted with @nikswamy about alternatives, including indexing `lex_t` by its length, making `<<` homogenous, and some more, but the current plan is roughly:
- Remove `lex_t` as a type/primitive
- `(<<)` should only be for structural inclusion, remove all lexicographic rules
- There is another relation `(<<)_lex : (a * b) -> (a * b) -> prop` defined as the lexicographic ordering wrt `(<<)`. Nested tuples can be used to simulate a list, but the length will be equal. Desugaring would be used so we can still write things as usual.

This means lexicographic ordering only happens at the *top* and is not mixed with structural inclusion, we're not confident the two are compatible when mixed, particularly since `tuple2` would have both principles, which sounds very fishy to me.

Note that if the lexicographic precedes were to be made heterogeneous, we can code up the same example:
```fstar
(10, 10) >> (9, (10, 10)) >> (9, (9, (10, 10))) >> ...
```

(This is all pretty fresh, we will update as we work on it.)

**Comment by nikswamy** [comment]
This is indeed badly busted.

I think the intention for the use of lex orderings in decreases clauses much more closely matches the revised proposal of having lex orderings "at the top". Trying to encode this using a list-like lex_t type was a mistake, an embarrassing mistake. Surprised that it has lingered for so long.

**Comment by VincentCheval** [comment]
Hello,

Would it be still possible to keep some instance of the list-like lex_t but on special cases ?

For instance, if your lists are ordered in decreasing order w.r.t. (<<) then the lexicographic order on lists of different size is well funded (corresponds to the multiset ordering typically). 

I'm not saying this out of interest. I'm gonna write some proofs that relies on multiset ordering for the termination and it seems that I'm not gonna be able to encode this in your recent proposal.

Best
Vincent

**Comment by VincentCheval** [comment]
Hello,

I had some thought this weekend on lex_t. I don't know if I'm gonna talk non-sense or youalready thought about it and discarded it but it was a good opportunity for me to learn more about FStar (I finally started to understand constructive proofs...I think)

So, in the post of @mtzguido, you mentioned:
> - Remove lex_t as a type/primitive
> - (<<) should only be for structural inclusion, remove all lexicographic rules
> - There is another relation (<<)_lex : (a * b) -> (a * b) -> prop defined as the lexicographic ordering wrt (<<). Nested tuples can be used to simulate a list, but the length will be equal. Desugaring would be used so we can still write things as usual.

I was wondering why you could not completely remove the function `(<<)_lex` but having a function `(<<)_wf` for well founded types (as defined in FStart.WellFounded) as (<<)_wf : (a -> a -> Tot bool) -> a -> a -> prop (the first argument being for the relation on which `a` is well founded. This way, we don't need to have only lex orderings "at the top" as mentioned by @nikswamy and we can combined them as we want provided we can prove they are well founded.


You could have a predicate `is_well_founded` that requires the existence of well_founded type w.r.t. a relation  (In my example, I on worked with boolean relations because I still have trouble manipulating the relation (a -> a -> Type). For instance I don't know if the `p_rel` is a hack on my side to try to have some constructive proofs working with FStar.WellFounded 

```
type p_rel (#a:Type) (rel:(a -> a -> Tot bool)) (x:a) (y:a) = (_:unit{ rel x y })

let is_well_founded (a:Type) (r:a -> a -> Tot bool) = exists (f:well_founded a (p_rel #a r)). True
```

We can have typically generic functions that show that tuple of well funded types are well funded too and that also allows a use to generate its own founded type that can be use in the `decreases` as follows using the following function that generates the accumulator (I did not put it as a ghost first because I was only working on proofs but for computational functions, I thought it was important to have it as ghost so that it's transformed in unit)

```
val generate_accu_ghost
  (#a:Type) (#r:(a -> a -> Tot bool))  (rwf:well_founded a (p_rel #a r))
  (x:a)
  (m:erased (acc a (p_rel #a r) x))
  (y:a { r y x}) :
  Tot (m':erased (acc a (p_rel #a r) y) { reveal (m') << reveal (m) })
let generate_accu_ghost #a #r rwf x m_x y =
  let h : (p_rel #a r) y x = assert(r y x) in
  match reveal (m_x) with
    | AccIntro m_next ->
        let m_y = m_next y h in
        FStar.WellFounded.axiom1_dep (m_next y) h;
        FStar.WellFounded.axiom1_dep m_next y;
        hide (m_y)
```

Then in a normal function, that would go like this:

```
assume type a_t:eqtype (* I restricted myself to eqtype because it's easier to manipulate but could be extended. *)
assume val rel_a : a_t -> a_t -> Tot bool
assume val rwf_a : well_founded a_t (p_rel #a_t rel_a)

let rec my_function (x:a_t) (m_x:erased (acc a_t (p_rel #a_t rel_a) x)) : Tot nat (decreases (reveal m_x)) =
	
    ...
   
    (* When we need to call the induction on some y *)
    let m_y' = generate_accu_ghost #a_t #rel_a rwf_a x m_x y in
    my_function y m_y'
 
    ...
```
And to call the function on some `z`: `my_function z (hide (rwf z))`


I ideally, I would have preferred if I did not need to pass the `m_x` as argument of the function but with my poor knowledge of FStar, I did not manage to do otherwise. In any case, I checked and the following dummy example 
```
let main_function (y z:a_t) =

  let rec my_function (x:a_t) (m_x:erased (acc a_t (p_rel #a_t rel_a) x)) : Tot nat (decreases (reveal m_x)) =
    if rel_a y x
    then
      let m_y' = generate_accu_ghost #a_t  #rel_a rwf_a x m_x y in
      my_function y m_y'
    else 0
  in
  my_function z (hide (rwf_a z))
```
is extracted into 
```
let (main_function : a_t -> a_t -> Prims.nat) =
  fun y ->
    fun z ->
      let rec my_function x m_x =
        if rel_a y x then my_function y () else Prims.int_zero in
      my_function z ()

```
So other than the fact that there is always an additional "unit" argument in the function, it's not too bad. 

Of course, you could also have an axiom that says something like:

```
assume val axiom_well_founded (a:Type) (rel:a -> a -> Tot bool) (rwf:well_founded a (p_rel #a rel)) (x y:a): Lemma
  (requires (rel x y))
  (ensures (x << y))
```
And with it the problem of additional unit disappear.


Hope this can be useful and that I'm not making a fool myself... specially cause I was some warnings when I compile:
```
(Warning 242) Definitions of inner let-rec proof1 and its enclosing top-level letbinding are not encoded to the solver, you will only be able to reason with their types (Also see: WellFounded.fst(21,10-21,16))
(Warning 242) Definitions of inner let-rec proof1 and its enclosing top-level letbinding are not encoded to the solver, you will only be able to reason with their types (Also see: WellFounded.fst(74,10-74,16))
(Warning 242) Definitions of inner let-rec my_function and its enclosing top-level letbinding are not encoded to the solver, you will only be able to reason with their types (Also see: WellFounded.fst(102,10-102,21))
(Warning 242) Definitions of inner let-rec my_function and its enclosing top-level letbinding are not encoded to the solver, you will only be able to reason with their types (Also see: WellFounded.fst(121,10-121,21))
```
I hope it does not make everything I did irrelevant 🙁 


---

I added below my full file I you want to have a look. It also contains a proof that tuples of natural number is well founded  (was my try on simple case) and a proof that tuple of two well founded types is also well founded.

```
module WellFounded
open FStar.Ghost
open FStar.WellFounded

noeq type acc (a:Type) (r:(a -> a -> Type)) (x:a) : Type =
  | AccIntro : next:(y:a -> r y x -> Tot (acc a r y)) -> acc a r x

type well_founded (a:Type) (r:(a -> a -> Type)) = x:a -> Tot (acc a r x)

(* Example of tuple of natural number *)

let rel_nat_pair ((x,y):(nat*nat)) ((x',y'):(nat*nat)) : Type0 =
  if x < x'
  then true
  else if x = x'
  then y < y'
  else false

let well_founded_nat_pair (t:nat*nat) : Tot (acc (nat * nat) rel_nat_pair t) =

  let rec proof1 (x:nat) : Tot ((y:nat) -> Tot (let t = (x,y) in acc (nat*nat) rel_nat_pair t)) (decreases x) =

    let rec proof2 (y:nat) :  Tot (let t = (x,y) in acc (nat*nat) rel_nat_pair t) (decreases y) =
      let t = (x,y) in
      let next (t':(nat*nat)) (h:rel_nat_pair t' t) =
        FStar.Squash.return_squash #(rel_nat_pair t' t) h;
        let x' = (Mktuple2?._1 t') in
        let y' = (Mktuple2?._2 t') in
        if x' < x
        then proof1 x' y'
        else proof2 y'
      in
      AccIntro next
    in
    proof2
  in
  proof1 (Mktuple2?._1 t) (Mktuple2?._2 t)

(* The generation of ghost accumulator *)

type p_rel (#a:Type) (rel:(a -> a -> Tot bool)) (x:a) (y:a) = (_:unit{ rel x y })

val generate_accu_ghost
  (#a:Type) (#r:(a -> a -> Tot bool))  (rwf:well_founded a (p_rel #a r))
  (x:a)
  (m:erased (acc a (p_rel #a r) x))
  (y:a { r y x}) :
  Tot (m':erased (acc a (p_rel #a r) y) { reveal (m') << reveal (m) })
let generate_accu_ghost #a #r rwf x m_x y =
  let h : (p_rel #a r) y x = assert(r y x) in
  match reveal (m_x) with
    | AccIntro m_next ->
        let m_y = m_next y h in
        FStar.WellFounded.axiom1_dep (m_next y) h;
        FStar.WellFounded.axiom1_dep m_next y;
        hide (m_y)

(* Generalisation  *)

assume type a_t:eqtype
assume type b_t:eqtype
assume val rel_a : a_t -> a_t -> Tot bool
assume val rel_b : b_t -> b_t -> Tot bool
assume val rwf_a : well_founded a_t (p_rel #a_t rel_a)
assume val rwf_b : well_founded b_t (p_rel #b_t rel_b)

let is_well_founded (a:Type) (r:a -> a -> Tot bool) = exists (f:well_founded a (p_rel #a r)). True

let rel_pair ((x,y):(a_t*b_t)) ((x',y'):(a_t*b_t)) : Type0 =
  rel_a x x' || (x = x' && rel_b y y')

let well_founded_pair (t:a_t*b_t) : Tot (acc (a_t * b_t) rel_pair t) =

  let rec proof1 (x:a_t) (m_x:erased (acc a_t (p_rel #a_t rel_a) x)): Tot ((y:b_t) -> Tot (let t = (x,y) in acc (a_t*b_t) rel_pair t)) (decreases (reveal m_x)) =

    let rec proof2 (y:b_t) (m_y:erased (acc b_t (p_rel #b_t rel_b) y)) :  Tot (let t = (x,y) in acc (a_t*b_t) rel_pair t) (decreases (reveal m_y)) =
      let t = (x,y) in
      let next (t':(a_t*b_t)) (h:rel_pair t' t) =
        FStar.Squash.return_squash #(rel_pair t' t) h;
        let x' = (Mktuple2?._1 t') in
        let y' = (Mktuple2?._2 t') in
        if rel_a x' x
        then
          let m_x' = generate_accu_ghost #a_t #rel_a rwf_a x m_x x' in
          (proof1 x' m_x') y'
        else
          let m_y' = generate_accu_ghost #b_t #rel_b rwf_b y m_y y' in
          proof2 y' m_y'
      in
      AccIntro next
    in
    (fun (y:b_t) -> proof2 y (hide (rwf_b y)))
  in
  let x = Mktuple2?._1 t in
  let y = Mktuple2?._2 t in
  proof1 x (hide (rwf_a x)) y

(* Dummy example *)

let main_function (y z:a_t) =

  let rec my_function (x:a_t) (m_x:erased (acc a_t (p_rel #a_t rel_a) x)) : Tot nat (decreases (reveal m_x)) =
    if rel_a y x
    then
      let m_y' = generate_accu_ghost #a_t  #rel_a rwf_a x m_x y in
      my_function y m_y'
    else 0
  in
  my_function z (hide (rwf_a z))

(* The axiom I would like to add *)

assume val axiom_well_founded (a:Type) (rel:a -> a -> Tot bool) (rwf:well_founded a (p_rel #a rel)) (x y:a): Lemma
  (requires (rel x y))
  (ensures (x << y))

(* Dummy example *)

let main_function2 (y z:a_t) =

  let rec my_function (x:a_t) : Tot nat (decreases x) =
    if rel_a y x
    then
      begin
        axiom_well_founded a_t rel_a rwf_a y x;
        my_function y
      end
    else 0
  in
  my_function z

```

**Comment by mtzguido** [comment]
Hi Vincent, thanks for the comments.

Let's chat in more detail later today, but my idea was that keeping the restricted `<<_lex` would make it easier to migrate old code, which is vastly using lex tuples (of fixed length) and not WF orders. We should anyway support any well founded order via accessibility predicates, as in your encoding, by using a singleton lex tuple. Ideally we would in the longer run define the lex tuples as a WF order themselves and make everything uniform, but that involves some work (some of which you did!).

Also note that this axiom
```fstar
assume val axiom_well_founded (a:Type) (rel:a -> a -> Tot bool) (rwf:well_founded a (p_rel #a rel)) (x y:a): Lemma
  (requires (rel x y))
  (ensures (x << y))
```
is inconsistent as stated, since there's no constraint that this WF order is consistent with `<<`, or more generally since several incompatible WF orders can exist on the same type.
```fstar
let onetwo = x:nat{x == 1 \/ x == 2}
let rel (x y : onetwo) : bool = x > y
let acc2 : acc onetwo (p_rel rel) 2 = AccIntro (fun x _ -> match x with)
let acc1 : acc onetwo (p_rel rel) 1 = AccIntro (fun (x:onetwo) _ -> assert (x == 2);
                                                        match x with | 2 -> acc2)
let wf12 : well_founded onetwo (p_rel rel) =
  fun x -> match x with
        | 1 -> acc1
        | 2 -> acc2

let bad () : Lemma (2 << 1) =
 axiom_well_founded onetwo rel wf12 2 1

let falso () : Lemma False =
  let rec inner (x:onetwo) : Lemma False =
    if x = 1
    then (bad (); assert (2 << 1); inner 2)
    else inner 1
  in
  inner 1

```

**Comment by VincentCheval** [comment]
Hi,

> Also note that this axiom
> 
> ```fstar
> assume val axiom_well_founded (a:Type) (rel:a -> a -> Tot bool) (rwf:well_founded a (p_rel #a rel)) (x y:a): Lemma
>   (requires (rel x y))
>   (ensures (x << y))
> ```
> 
> is inconsistent as stated, since there's no constraint that this WF order is consistent with `<<`, or more generally since several incompatible WF orders can exist on the same type.

Yes I agree. That's why in my explanation I put `x <<_wf(rwf) y`
```fstar
assume val axiom_well_founded (a:Type) (rel:a -> a -> Tot bool) (rwf:well_founded a (p_rel #a rel)) (x y:a): Lemma
  (requires (rel x y))
  (ensures (x <<_wf(rwf) y))
```
But I could not write that directly in this version of fstar 😊

**Comment by aseemr** [comment]
Hi all, I started some work today on fixing this unsoundness with the tuples idea that @mtzguido proposed above. The wip is in the `_aseem_1916` branch. Still early, will report progress as it goes on.

**Comment by aseemr** [comment]
I have been working on it a bit last couple of days. The main idea is to separate `<<` and `<<_lex`, where the former includes `nat` ordering and subterm ordering for inductives, and the latter includes the lexicographic ordering.

A homogenous `<<_lex : a & b -> a & b -> prop` is too restrictive practically. First, we generate `<<_lex` terms with different types for various reasons (refinements, hash-consing, GADTs where the subterm has different indices, etc.). If our SMT encoding only allows reasoning for homogenous `<<_lex`, these examples fail. Secondly, our `<<` relation is heterogenous, so restricting `<<_lex` to be homogenous means we can't exploit the full `<<` in say the type `b` above.

So could we make `<<_lex` heterogenous, while ensuring that the lex tuples arity is same in the two types. Essentially, the following theory:

```
val precedes (#a #b:Type) (x:a) (y:b) : Type0
val precedes_lex (#a #b:Type) (x:a) (y:b) : Type0
val eq_lex_tuple_arity (a b:Type) : Type0

val precedes_trans (a b c:Type) (x:a) (y:b) (z:c)
  : Lemma
      (requires precedes x y /\ precedes y z)
      (ensures precedes x z)
      [SMTPatOr [
        [SMTPat (precedes x y); SMTPat (precedes x z)];
        [SMTPat (precedes y z); SMTPat (precedes x z)]
      ]]
       
val precedes_lex_axiom (#a #b #c #d:Type) (x1:a) (y1:b) (x2:c) (y2:d)
  : Lemma
      ((precedes_lex (x1, y1) (x2, y2)) <==>
       ((precedes x1 x2 /\ eq_lex_tuple_arity b d) \/
        (eq3 x1 x2 /\ precedes_lex y1 y2)))
      [SMTPat (precedes_lex (x1, y1) (x2, y2))]

assume Eq_lex_tuple_arity_base : eq_lex_tuple_arity unit unit

val eq_lex_tuple_arity_induction (a b c d:Type)
  : Lemma
      (requires eq_lex_tuple_arity b d)
      (ensures eq_lex_tuple_arity (a & b) (c & d))
      [SMTPat (eq_lex_tuple_arity (a & b) (c & d))]
```

So the lex tuples chain is built as `(a, (b, (c, d)))`. We peel off the left component everytime and check the precedes relation on it, while making sure that if precedes is valid, the arity of the tuples on the right is the same.

A second issue is that, so far in our encoding the precedes relation `<<` is also untyped. For any two terms `x` and `y`, when we generate `precedes _ _ x y`, we set the type arguments `_` to `lex_t`. I am trying to fix this too, i.e. make `precedes` typed in the smt encoding.

This also turns out to be tricky practically. Consider `list a`. For subterm ordering, we generate an axiom that (roughly):

```
forall hd:a, tl:list a. precedes #(list a) #(list a) tl (Cons hd tl)
```

Note that the type parameters to `<<` are `#list a`. This means that if we get a query that instead tries to compare the list at, say, a refinement type, this axiom will not apply. And this case also comes up a lot.

So I have relaxed the emitted `<<` axioms to be more general in the types, we now emit something like:

```
(assert (! 
         (forall ((@x0 Term) (@x1 Term) (@x2 Term) (@x3 Term) (@x4 Term))
                 (! (implies (and (HasTypeZ (Prims.Cons @x0
                                                                               @x1
                                                                               @x2)
                                                            @x4)
                                          (HasTypeZ @x2 @x3))
                                  (Valid (Prims.precedes @x3
                                                                      @x4
                                                                      @x2
                                                                      (Prims.Cons @x0
                                                                                          @x1
                                                                                          @x2))))
                    

                    :pattern ((Valid (Prims.precedes @x3
                                                                       @x4
                                                                       @x2
                                                                       (Prims.Cons @x0
                                                                                           @x1
                                                                                           @x2))))
```

Essentially saying that as long as we can prove the some typing for `tl` and `Cons hd tl`, those types can be used in `precedes`.

With these changes, I can verify most of `ulib` without any code changes (getting some failures in the `Printf` modules that go away if I add explicit `decreases`, need to investigate further).

That's the status so far. Feedback would be most welcome (cc @nikswamy , @mtzguido )

**Comment by nikswamy** [comment]
hi @aseemr 

As we were discussing the other day, part of the problem here is that we intended for the `decreases %[...]` to be a kind of syntactic sugar, but we ended up exposing it as the lex tuple type with axioms about it etc, allowing writing recursive functions over lex tuples etc. which is much more permissive than the sugar we had in mind, and ultimately unsound.

What do you think about really treating `decreases %[..]` as sugar with no special axioms about lex tuples at all. 

I.e., when typechecking a recursive function `f: (x0:t0 -> .. -> xlast:tlast -> Tot t (decreases %[e0; ...; en])`,  we add the recursively bound function to the context, after its arguments (as usual), with the type below, where the substitution `s=[x0/a0]...[xlast/alast]`

```
a0:t0, ..., alast:tlast, f : x0:t0 -> xlast:tlast{ s(e0) << e0 \/ (s(e0)== e0 /\ (s(e1) << e1 \/ (s(e1)==e1 /\ ...)))} -> t
```

i.e., rather than doing anything special with lex tuples in the SMT encoding etc. , we just expand the interpretation of the lexicographic ordering in the refinement precondition of the recursively bound `f`.

**Comment by aseemr** [comment]
Thanks Nik, this is a nice idea, it relates to our discussion about allowing programmers to write only the decreases clauses, in which case the requirement for arity check is also not there since it is not directly exposed to the programmers. I will try this.

But hope the second part of my comment about making the `<<` relation typed seems fine?

**Comment by aseemr** [comment]
The unsoundness is now fixed in master, https://github.com/FStarLang/FStar/pull/2218#issuecomment-775745331. Repurposing this PR to allow writing user-defined relations in the decreases clauses.

**Comment by aseemr** [comment]
See #2307 for supporting user-defined well-founded relations. @VincentCheval if you have examples that you would like to try, would be happy to discuss.
