### ISSUE TITLE
Understanding implicit error message

### ISSUE THREAD

**Issue by mkolosick** [FStarLang/FStar#1929]
I'm currently trying to use F*'s implicit parameters, and ran
into an error that I don't understand. The simplified code I have is:
```
module Incr

type sint (n:int) =
  | SInt : x:int{x = n} -> sint n

val sincr : #n:int -> f:(int -> sint n) -> sint (n + 1)
let sincr #n f = match (f 0) with
  | SInt x -> SInt (x + 1)

val stest1 : sint 11
let stest1 = sincr (fun x -> SInt 10)
```

I get the error message:
```
Incr(11,29-11,33): (Error 66) Failed to resolve implicit argument ?6 of type Prims.int introduced for flex-flex quasi:	lhs=Instantiating implicit argument in application	rhs=Instantiating implicit argument in application (see also Incr(11,29-11,36))
```

My guess is that this is related to higher-order unification failing, but I'm wondering what is failing/what the error means?

If I give the lambda term a type:
```
val foo : int -> sint 10
let foo x = SInt 10

val stest2 : sint 11
let stest2 = sincr foo
```
then everything goes through, (why I think that this is related to a combination of inference and implicit instantiation).

**Comment by mtzguido** [comment]
Two things are being combined here for inference to fail.

Your `sincr` application needs to return an `sint 11`, so F* infers that `?n + 1` has to be `11`, where `?n` is the implicit for `sincr`. Notably this does not get simplified to `?n = 10`. This is only true since `+` has an inverse, but the unifier it has no special treatment of `+` for this.[1]

Now, the body of the abstraction, `SInt 10` has to be at type `sint ?n`. One can certainly expect this will unify `n` to `10`, but that information comes only from a refinement type, namely the fact that `10` must have type `x:int{x = ?n}`. F* will not use this information for inference, however, hence the failure. (This would also require some primitive treatment on equality, since this could very well `<=` instead.)

I'm not confident this style of constraining via refinements will scale up well, but there's a neat way of fixing your problem here. Define `sincr` instead as:

```fstar
val sincr : #n:pos -> f:(int -> sint (n-1)) -> sint n
let sincr #n f = match (f 0) with
  | SInt x -> SInt (x + 1)
```

This makes inference behave better backwards, since `n` will be fully unified with the expected type instead of just having a `?n + 1 = ?expected_n` constraint. Not sure F* can do better in general here, but others might know better.

[1] This would instead work well if one were using a unary representation of naturals, as is common in Coq, and one wrote `S n` for the return type.

**Comment by mkolosick** [comment]
Thanks!
