### ISSUE TITLE
Lemma for non-informative values

### ISSUE THREAD

**Issue by W95Psp** [FStarLang/FStar#2064]
Hi,

I've looked into F*'s repo, and I'm unable to find a way to prove, say:
```
let noninformative (t: Type) (observation: G.erased t -> Tot Type0) (x y: t)
  : Lemma (observation x == observation y)
  = ()
```

Such a lemma seems reasonable to me.

More generally, it would be nice that, for any type declaration decorated with the attribute `erasable`, F* generates a "noninformativeness" lemma. I've looked a bit in `/src/`, but I have no clue where such a thing could take place.

**Comment by mtzguido** [comment]
Careful, as stated this is not true since `Type0` is also non-informative, so `observation` could reveal the `erased t`. Having this lemma would entail a contradiction:
```fstar
module G = FStar.Ghost

let noninformative (t: Type) (observation: G.erased t -> Tot Type0) (x y: t)
  : Lemma (observation x == observation y)
  = admit ()

let observation (i:int) (x : G.erased int) : Type0 =
  G.reveal x == i

let falso () : Lemma False =
  noninformative int (observation 2) 2 3
```

If the codomain of `observation` were informative, as in:
```fstar
let noninformative' (t: Type) (observation: G.erased t -> Tot int) (x y: t)
  : Lemma (observation x == observation y)
  = admit ()
```
then I think this is consistent, buy only by a meta argument: I don't think it's provable internally.

**Comment by W95Psp** [comment]
Oh right, I haven't thought about that indeed!
Yes, that makes sense; I'll axiomatize such a lemma for my use case.

Thanks for the answer, I guess I can close.
