### ISSUE TITLE
Can't build the project: Unknown assertion failed

### ISSUE THREAD

**Issue by farao** [FStarLang/FStar#2134]
Hi, I'm trying to build the current version of the repo, simply exeuting "make" on a current arch linux installation. At some point, I'm getting
```
LowStar.Vector.fst(463,2-475,26): (Error 16) Unknown assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel
LowStar.Vector.fst(497,2-503,17): (Error 16) Unknown assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel
```
How do I increase the fuel there? (or can this be resolved by other means?)

**Comment by mtzguido** [comment]
Hi, thanks for the report! This shouldn't ever happen since our commits to master need to pass CI before being accepted. I just checked locally and I had a successful build.

Can you say more about your setup? Specifically about your z3 version: is it 4.8.5?

**Comment by farao** [comment]
No, z3 is on version 4.8.8 (from arch linux repo), but I figured that such a minor version difference shoulnd't make a difference - or does it? Other than that: which tools/versions make up the setup and could be interesting? Ocaml version is 4.06.1.

**Comment by mtzguido** [comment]
Unfortunately it does :). Our canonical "blessed" version, which we use to check our projects, is 4.8.5. Most other versions, except if too old, should also "work", but may present small differences which causes some proofs to not be found with the default fuel/rlimits, due to heuristics and random-like behavior in the solver. You can use the everest script (https://github.com/project-everest/everest) so set everything up as expected.

As for OCaml, we're currently supporting 4.09.1, so you could also hit a problem there. The everest script should also set it up.

If you switch to 4.8.5, everything should just work. Otherwise, you could conceivably just increase the rlimits on these proofs to make them work, but it'll involve some debugging pain, and an upgrade of our library would mean you'd have to do it again.

**Comment by mtzguido** [comment]
Closing... please let us know if you still can't build!
