### ISSUE TITLE
Verification profiling

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#220]
I think it would help a lot to have a simple way to see were most time is spent in a proof.

The closest thing we have now is `--print_types`: if one stares at the output carefully enough one can spot top-level definitions that take a long time to type-check compared to the rest. So for a start we could maybe make `--print_types` also print the checking time in a way that can be sorted afterwards?

In general, we would need more than this, like the time that is spent on each proof obligation for instance, again in a way that is easy to sort. Also a way to run experiments repeatedly while printing the average and variance, this maybe while focusing on part of a file, like a single definition.

**Comment by catalin-hritcu** [comment]
Another useful thing to print is the fuel that was needed to make verification succeed.

**Comment by nikswamy** [comment]
The last point, about the fuel needed, is useful in another context. 
There's another thread here (somewhere) ... where I mention that one way to avoid relying on timeouts in our regression suite is to replay verification with exactly the fuel needed for each obligation (and infinite timeout). This should make our suite more robust to variations in machine speed etc.

**Comment by s-zanella** [comment]
I think that using `--hint_info` (even when no using hints at all) provides everything @catalin-hritcu wanted.

We discussed having a script that parses logs that use `--hint_info` to print statistics that summarize the verification times of individual proof obligations: https://github.com/project-everest/everest-ci/issues/88.

Should this be a separate script, or should it be integrated in F*, so that we get a per-module summary?

**Comment by catalin-hritcu** [comment]
`--hint_info` does indeed solve my original problem. Let's track the rest somewhere else if needed.
