### ISSUE TITLE
sladmit and interaction with allocation

### ISSUE THREAD

**Issue by nikswamy** [FStarLang/FStar#2282]
This program fails to verify:

```
let test (x:unit) 
   : SteelT unit emp (fun _ -> emp)
   = let v = Steel.Reference.alloc x in
      let s = Steel.Reference.alloc x in
      sladmit()
```

**Comment by R1kM** [comment]
This was due to the special handling of sladmits, using specific admit_pre/post annotations.
This special handling is actually of little use, it only helps in the very specific case where two sladmits are used in succession, but is not helpful when they are separated by another computation.
Furthermore, it both increases the complexity of the tactic, and decreases its performance: it induces another linear traversal of the bag of constraints, even when no sladmit is present.

I just removed this special handling from the steel branch, which makes this program verify as expected.
