### ISSUE TITLE
ASSERTION FAILURE: Name not found: pure_return

### ISSUE THREAD

**Issue by dominique-unruh** [FStarLang/FStar#2299]
F* kindly asked me to file a bug report with the following words:
```
(Error) ASSERTION FAILURE: Name not found: pure_return
F* may be in an inconsistent state.
Please file a bug report, ideally with a minimized version of the program that triggered the error.
```
I am attaching an example file that I minimized as far as I managed without understanding what is going on: [Bug2.txt](https://github.com/FStarLang/FStar/files/6546122/Bug2.txt)
(Extension is .txt because github wanted it so. It is an .fst file.)

I used the latest "weekly" build from April 22. (https://github.com/FStarLang/binaries/blob/master/weekly/fstar_202104220032_13e688dda1_Linux_x86_64.tar.gz)

**Comment by aseemr** [comment]
I pushed a "fix" to the master. There were a couple of issues:

* `pure_return` is marked `unfold`, meaning that it is expected to be reduced by the typechecker before sending the query to smt. In the case of tactics, this unfolding has to be done by the tactic. The error message now says that the symbol is marked `unfold`, so smt expected it to be reduced already. In your example, we can add a `norm [delta_qualifier ["unfold"]]` step in the tactic (`l_to_r ...; norm [delta_qualifier ["unfold"]]`)
* Then there was a bug in the typechecker due to which this still left instances of `pure_return` that appeared under a blocked `match`. I fixed the bug here: https://github.com/FStarLang/FStar/commit/36d6c1db7157769e10d6e7f7a677f6cb8dcb4e01. So now, your example works once we add the `unfold` step.

Thanks for the report!

**Comment by dominique-unruh** [comment]
I will try it out when it reaches the weekly builds. 

One question: Do I understand right after running a tactic, there are two cases: no unfold-symbols are there, and then `norm [delta_qualifier ["unfold"]]` does nothing. Or there are unfold-symbols, and then there will always be an error without a final `norm [delta_qualifier ["unfold"]]`? So what is the rationale of not doing this automatically before sending the subgoals to SMT?
