### ISSUE TITLE
Add warning when match arms are unreachable

### ISSUE THREAD

**Issue by klinvill** [FStarLang/FStar#2380]
Currently no errors or warnings are raised when writing something like:
```
let is_zero_or_one(n: ℕ) : bool =
  match n with
  | 0 → true
  | _ → false
  | 1 → true
```

It would be nice if there was a warning message if there's an unreachable branch in a match statement (like what Rust does). A warning message would also make it slightly easier to detect when nested match statements aren't properly enclosed in parentheses (e.g. the below example currently results in the error message `(Error 19) Patterns are incomplete; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel`)

```
type a =
  | A

type b =
  | B : a -> b
  | Unused_B

let unfold_b (x: option b) : option a =
  match x with
  | Some(x_b: b) ->
    match x_b with
    | B x_a -> Some(x_a)
    | _ -> None
  | _ -> None
```

**Comment by nikswamy** [comment]
This is an old request, one that we have discussed quite a lot. But, it is hard to implement this feature accurately for F*, since pattern coverage in F* is a semantic check. In order to detect that a given branch is unreachable would require several expensive calls to the SMT solver (e.g., asserting false in each branch), which would most of the time not succeed.

So, despite this being a seemingly very reasonable request, we're not going to fix this any time soon. Thanks for raising it.

**Comment by nikswamy** [comment]
See https://github.com/FStarLang/FStar/issues/71
