### ISSUE TITLE
Bad error message when misusing functions

### ISSUE THREAD

**Issue by gancherj** [FStarLang/FStar#2493]
Consider the below:
```
let bad a : a = fun (x:nat) -> 
    let x : a = admit() in 
    x
```

This gives me the error
`(Error 19) assertion failed; The SMT solver could not prove the query, try to spell your proof in more detail or increase fuel/ifuel
user-error: No secondary locations for this issue`.

Would it be possible to catch these sorts of simple typing errors without asking Z3?

**Comment by nikswamy** [comment]
Because F* is extensional, it is possible that we have an equation in scope telling us that `a == b -> c`. So, type conversions involving variables do, in general, get sent off to SMT when they can't be solved by the unifier. In this case, of course, we have a query like `a = nat -> a`, which has no solution, but that's quite a special case. 

But, I hear you: it would ben nice to have a simple way of trapping obvious errors like this.

**Comment by gancherj** [comment]
A possible solution is parametricity -- `a` is universally quantified, so we should somehow know that we have no equations in scope about it. But this probably more subtle than I believe :)

**Comment by nikswamy** [comment]
Consider:

```
let bad (_:False) a : a = fun (x:nat) -> 
    let x : a = admit() in 
    x
```

**Comment by nikswamy** [comment]
I hope the discussion here explains why F* behaves as it does on the example shown. Closing.
