### ISSUE TITLE
Inference of bool to Type conversion

### ISSUE THREAD

**Issue by markulf** [FStarLang/FStar#263]
It is currently hard to see when the bt2 coercion is necessary and when it can be avoided using inference. It would be nice to improve inference.

Lets collect pointers to examples in which type checking fails without bt2 here.

`examples/algorithms/gc.fst`
`examples/crypto/millionaires.fst`
`examples/crypto/wysteria.fst`
`examples/security/statefulEnc-multi-frame.fst` [some could be removed](https://github.com/FStarLang/FStar/commit/b43ce7348929a65ff149beeafebcdd98493da72e)
...

Most cases are of the form `(fun m0 -> b2t (m0 = m))` and one could also write `(fun m0 -> m0 = m /\ True)`.

**Comment by catalin-hritcu** [comment]
Good idea. I've also had to introduce some `b2t`s of the first kind when working on #199.

**Comment by nikswamy** [comment]
Thanks for starting this issue. 

The insertions of `b2t` underneath lambdas is currently problematic. 

The issue is that given a lambda term, the first phase of desugaring has to stratify it, deciding whether it is a type or a term lambda. It does this purely based on the stratum it picks for the body. For example, given `fun x -> body`, if `body` is deemed to be an expression, then this is desugared to an `Exp_abs`; otherwise, if `body` is deemed to be a type, then this is desugared as a `Typ_lam`.

The insertion of `b2t` happens at a later phase, during type-checking. 

However, once stratification has picked `fun x -> body` to be an `Exp_abs`, then the later phase cannot insert a `b2t` on `body` even if it is needed, since that would require changing the stratum of the term and promoting it to a `Typ_lam` ... which it cannot do. 

A related problem is illustrated by the following code:

```
val f: a:Type -> x:a -> Tot a
let f a x = x
```
This code fails to check because stratification elaborates the definition of `f` while taking `a` to be a term variable rather than a type variable. Instead, if stratification considered the user-provided `val` declaration, it could figure out that `a` should be a type variable. Currently, you have to write:

```
val f: a:Type -> x:a -> Tot a
let f (a:Type) x = x
```

Or, 

```
val f: a:Type -> x:a -> Tot a
let f 'a x = x
```

Or

```
val f: a:Type -> x:a -> Tot a
let f x = x
```

The last variant takes advantage of the convention that type variables are implicitly introduced in a let-binding if the user omits them.

The solution to both these problems is probably:

1. Make stratification smarter. Currently, it is purely based on syntax and name binding. We could try to make use of some type information to stratify. 

2. More radical and an enormous change: move to an unstratified syntax.

**Comment by markulf** [comment]
Any progress on this? Is it still useful to collect this data?

**Comment by nikswamy** [comment]
```
i:int -> Pure int 
  (requires (b2t (0 <= i)))
  (ensures (fun j -> b2t (0 <= j)))
```

These `b2t`s seem unnecessary, yet the user must write them

**Comment by nikswamy** [comment]
"More radical and an enormous change: move to an unstratified syntax."
This is now done. 

And commit 6fd3dfc59f6be74445e4a84d090ca02fbc1b8f40 fixes my most recent report.
