### ISSUE TITLE
See which type was infered by F*

### ISSUE THREAD

**Issue by ckeller** [FStarLang/FStar#27]
fstar.exe could have an option that prints the types infered by F*, when none is given by the user (this option is -i for ocaml)

**Comment by catalin-hritcu** [comment]
I agree this would be nice, but I think the default style we've adopted at the moment is writing an explicit type annotation to each top-level definition. It would be nice to have this feature not just for top-level definitions though, but for variables in arbitrary contexts. Like writing `printType e` in the middle of a term and getting the type of `e` output (this might need to be protected by a flag, because we would be doing console IO in the middle pure computations).

**Comment by catalin-hritcu** [comment]
It seems that F* already has something like this. Some of my students, who apparently looked carefully at all the flags of F*, discovered the `--log_types` flag. They said it doesn't always work well, but was quite efficient at debugging proofs.

**Comment by catalin-hritcu** [comment]
It seems that `--log_types` only prints the type of top-level lets. While that's useful, it's clearly not enough for devising proofs interactively.

**Comment by catalin-hritcu** [comment]
Closing this, since `--log_types` is exactly what Chantal was asking for originally. Filed separate issue for printing the proof context and goal (#219).
