### ISSUE TITLE
Failed to prove trivial lemma - Problem with conjunction in assume?

### ISSUE THREAD

**Issue by ngrimm** [FStarLang/FStar#283]
I defined an xor function and gave some simple properties 
```
assume val xor : bytes -> bytes -> Tot bytes
let xor_laws = assume(forall a b. xor a b = xor b a /\ 
                                  xor (xor a b) a = b) 
```
I tried to prove a trivial lemma
```
val test2 : unit -> Lemma (forall a b. xor (xor a b) b = a) 
let test2 () = ()
```
which failed. 
I can prove the same lemma using a trivial helper  lemma and explicitly applying it
```
val test1 : unit -> Lemma (forall a b. xor (xor a b) b = xor (xor b a) b)
let test1 () = ()

val test2' : unit -> Lemma (forall a b. xor (xor a b) b = a) 
let test2' () = test1 ()
```

Surprisingly, if I split up the xor_laws into two seperate assumptions instead of using a conjunction, I can show the lemma without any helper lemma.

```
let xor_sym = assume(forall a b. xor a b = xor b a) 
let xor_inv = assume(forall a b. xor (xor a b) a = b)
```

**Comment by nikswamy** [comment]
the `assume` doesn't behave as you expect it to. It's signature is given in Prims as

```
assume val _assume : p:Type -> unit -> (y:unit{p})
```

The compiler provides sugar so that when you write `assume p` it is translated to `Prims._assume p ()`.

Now, your `xor_laws` is just a program in the `ALL` monad. F\* will ignore the definition of `xor_laws` when reasoning about the rest of the program, and only rely on its type. In this case, there is no invocation of `xor_laws` anywhere in your program, so its type is irrelevant. 


OTOH, if you wrote at the top level:

```
assume XOR_Laws: forall a b. xor a b = xor b a /\ ....
```

then this is indeed an axiom injected in the context for the rest of the program.

FWIW, I plan to change the signature of `_assume` to :

```
assume val _assume : p:Type -> Pure unit (require (True)) (ensures p)
```

However, that would not change the behavior you're observing.

**Comment by ngrimm** [comment]
Thanks for the explanation, it seems I had a different idea about what the `assume` was doing.

However, then I don't really understand how the Lemma can be proved if I write 
```
let xor_sym = assume(forall a b. xor a b = xor b a) 
let xor_inv = assume(forall a b. xor (xor a b) a = b)
```
instead of 
```
let xor_laws = assume(forall a b. xor a b = xor b a /\ 
                                  xor (xor a b) a = b) 
```

**Comment by nikswamy** [comment]
Meanwhile, I've changed the definition of `_assume` to be 

```
assume val _assume : p:Type -> unit -> Pure unit (requires (True)) (ensures (fun x -> p))
```

**Comment by nikswamy** [comment]
This will require you to write the `assume XOR_Laws:..` style. 

I've also changed `bug283.fst` to reflect this.
