### ISSUE TITLE
Z3 version check breaks if Z3 prints deprecation warnings

### ISSUE THREAD

**Issue by Johanmyst** [FStarLang/FStar#2869]
Hi!

I'm posting this in reference to [this slack channel discussion thread](https://everestexpedition.slack.com/archives/C0N6E651T/p1680168783992769?thread_ts=1680088855.443969&cid=C0N6E651T).

When building FStar (also through Opam), [the version of Z3 is checked here](https://github.com/FStarLang/FStar/blob/0be0ac02de5c57410cc918ae436610d91843ac5f/src/smtencoding/FStar.SMTEncoding.Z3.fst#L43). This check simply takes the output of `z3 -version` and if the output starts with the correct string, the check passes.

However, if Z3 prints anything else before the version number (such as deprecation warnings), this check fails. For example, when using the OpenMP library provided by LLVM version 15 (version 13 does not print this warning; I haven't checked version 14), this deprecation warning is printed: `OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead`. Because this warning is printed **before** Z3's normal output (even though it **is** correct), the version check fails and the build breaks.

Replacing the version check from `BU.starts_with` to `BU.contains` should likely fix this issue ([defined in this module](https://github.com/FStarLang/FStar/blob/0be0ac02de5c57410cc918ae436610d91843ac5f/src/basic/boot/FStar.Compiler.Util.fsti)).

Kindly,

Johannes

**Comment by mtzguido** [comment]
Hi Johannes, thanks for the report!

The Z3 version check should really just raise a warning. Is the build breaking because of that, or during the Z3 test that F* does on startup?

If it's the latter, changing that line won't help, but maybe the solution is just to not put Z3's stderr into the same pipe as its stdout. (I imagine this warning goes to stderr... I'm building clang to check but maybe you can easily confirm too.)

**Comment by mtzguido** [comment]
Hi Johannes. This should now work, even with the warning, with the above PR merged. We are however working on upgrading a newer Z3 version (4.12), but that will take some time.
