### ISSUE TITLE
assert(True) by admit(); likely a silly bug but the code insists I report it

### ISSUE THREAD

**Issue by briangmilnes** [FStarLang/FStar#2899]
While working on some sequence proving tests of printing, I threw in an admit for a place holder.

let can_not_assert_by_admit = assert(True) by admit()

(Error 228) user tactic failed: ‘Tactic got stuck! Please file a bug report with a minimal reproduction of this issue.
FStar.Tactics.Result.Success u#0 #Prims.unit (Prims.admit u#0 #Prims.unit ()) "(((proofstate)))"‘
(Warning 266) Not an embedded unit: Prims.admit u#0 #Prims.unit ()

**Comment by nikswamy** [comment]
This is another confusing thing, sorry. 

What's happening here is that this is inferred to be something like:

```
assert (True) by (admit #(unit -> Tac unit) ())
```

In other words, you're asking F* to prove `True` by running a tactic, but not specified what the tactic should be, since the *tactic* itself is admitted.

The tactic that admits the current goal is called tadmit. 

So, this would work for any `p`.

```
assert p by tadmit()
```

Perhaps we could catch this kind of mistake and print a warning that says something like "you're using admit in a tactic context : Tac unit ... perhaps you meant tadmit"?

Wdyt @mtzguido?

**Comment by mtzguido** [comment]
I improved these error messages a bit, by trying to find the actual subterm that blocks reduction and reporting only that. Further, if there's a mention of `admit` within it, the users gets a tip:
```f*
let test0 = assert(True) by admit()
```
```
Bug2899.fst(7,12-7,18): (Error 228) user tactic failed: `Tactic got stuck!
Reduction stopped at: FStar.Tactics.Result.Success (Prims.admit ()) "(((proofstate)))"
The term contains an `admit`, which will not reduce. Did you mean `tadmit()`?`
```
Closing this for now.. but we could extend this logic with other common cases.
