### ISSUE TITLE
unused variables prevents reduction in proofs

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#300]
https://github.com/FStarLang/FStar/commit/56e85b05003fd08134ad9b8bfd4c756513f7ac44

**Comment by mtzguido** [comment]
Tried to reproduce, but the code is stale and I'm getting universe failures on it. Further, some tiny tests show that this kind of definition does reduce. Also, it seems to me that the example on stackAndHeap.fst should have failed since there's no way to resolve for `a`.. but this was long ago so who knows :).

Closing, if you find a repro please reopen!
