### ISSUE TITLE
incorrect error about incomplete pattern matching

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#301]
I tried to get rid of the use of projectors in lib/seq.fst
The body of length is currently defined using a projector:
https://github.com/FStarLang/FStar/blob/33304dc820d360f47bdbc9e6592c440454fd9329/lib/seq.fst#L32

In the next line, in comments, there is an simple alternate body which does pattern matching instead of projectors. When using that body,, I get a strange error about incomplete pattern matching.

**Comment by nikswamy** [comment]
Odd. Can you add a `val` declaration for `length`? Does that suppress the problem?

**Comment by aa755msr** [comment]
It is already there:
https://github.com/FStarLang/FStar/blob/33304dc820d360f47bdbc9e6592c440454fd9329/lib/seq.fsi#L23

**Comment by nikswamy** [comment]
This is because all the fuel parameters have been set to zero. 
The result is that F\* forbids Z3 from applying any inversions on inductive data types. The pattern matching requires F\* to prove that `is_MkSeq s` , which requires and inversion and fails. 
OTOH, calling `mkSeq.length` succeeds because its type is `seq a -> Tot nat`---note, it does not have a refinement guarding its pre-condition, because when generating the projector type we notice that it is a single-constructor datatype and so we don't need to guard it with a pre-condition. The same special handling of single-constructor datatypes is not present in the match rule, hence the discrepancy. 

Moral of the story: if you're setting fuel parameters explicitly, then you better be prepared to understand gory implementation details.

Using these options makes it work (allows 1 inversion):
#set-options "--initial_fuel 0 --max_fuel 0 --initial_ifuel 1 --max_ifuel 1"

**Comment by aa755msr** [comment]
Perhaps the error message could be : "incomplete pattern matching, or ran out of fuel"

**Comment by markulf** [comment]
We got a similar problem, but in our case even having `--max-ifuel` greater than 0 did not help, we had to set `--initial_ifuel 1` to get a more sensible error message.
