### ISSUE TITLE
strange error about implicit pattern variable

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#309]
type  poly2 (x : Type -> Type)  =
| Poly2 :  t:Type -> x t -> poly2 x

<input>(3,2-3,7): Implicit pattern variables in (Poly2 (U16767 x projectee _7_52529) _7_52528) could not be resolved against expected type (poly2 x); please bind them explicitly
#fail

**Comment by nikswamy** [comment]
This error comes up because we generate a projector for Poly2 which involves introducing a match. 

The generation of projectors for fancy inductives with implicit and higher-kinded type variables is not quite right. I've noticed failures in wysteria/theory.fst already. So, this is another case where it's not working well. 

Logging it as a bug.

As a workaround, you can disable projector generation for this file by adding the --__temp_no_proj flag. And then writing and using your own projectors.

**Comment by nikswamy** [comment]
can't repro with --universes... closing.
