### ISSUE TITLE
Coding-style of the extracted code

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#313]
How much cost would it represent to have a code generation in OCaml to have an usual coding style ?
Is there a tool for doing that in OCaml (that could eventually be used separately from F*) ? I know the Go language has this feature.

Vaguely related to #310.

**Comment by jkzinzindohoue** [comment]
What do you mean by having an "usual coding style" ?

The OCaml backend produces code in a very predicatable manner, and while it could be cleaner, the generated code is readable, at least if you write the F* code.
This applies to the fragment directly typable in OCaml at least. I do not know how the new extraction features behave.

**Comment by beurdouche** [comment]
> What do you mean by having an "usual coding style" ?
> 
> The OCaml backend produces code in a very predicatable manner, and while it could be cleaner, the generated code is readable, at least if you write the F* code.
> 

Exactly : “readable”. 

Can we claim we have a proof of semantic preservation between the F* code and the OCaml generated code ? Not yet right ?
This means a user building a critical system in F* has to review the generated code manually.

Typically there is no indentation in the generated code which is terrible for it’s code review.

**Comment by prosecco** [comment]
camplp4 pa_o.cmo pr_o.cmo X.ml > X-pretty.ml

**Comment by jkzinzindohoue** [comment]
There are a couple of things which could be improved. The indentation is one, the systematic introduction of useless variable for "unit" returning computations is an other. There is also a systematic parenthesizing which is a bit annoying for reading.
I will camlp4 later on this week to see how things look after prettifying.

We cannot claim that we have a proof of semantic preservation through the OCaml generation. If the code was written in the OCaml fragment, you should really get something like that though, because it is mostly a type erasure. I am going to take a closer look to those things later this week as well

**Comment by beurdouche** [comment]
Thanks @prosecco, I tested it and this is very cool =)
I am not sure we should use it by default though because once we have the proof of semantic preservation between X.fst and X.ml it is one more piece that will alter the generated code and we won't be able to prove that is preserves the semantic between X.ml and X-pretty.ml
Though we should clearly state that it exists and eventually make it available as an option ;)

BTW : 
```
Camlp4 was part of the official OCaml distribution until its version 4.01.0. Since then it has been replaced by a simpler system which is easier to maintain and to learn: ppx rewriters and extension points.
```

**Comment by beurdouche** [comment]
Related to #36

**Comment by catalin-hritcu** [comment]
@victor-dumitrescu has rewritten the pretty printer for OCaml, so if this is not fixed please reopen.
