### ISSUE TITLE
extraction of record values created using constructors.

### ISSUE THREAD

**Issue by aa755msr** [FStarLang/FStar#321]
`type point = {x:int ; y:int}`

`(Mkpoint 1 2)` extracts to `(MkPoint 1 2)` in Ocaml, where as `{x= 1; y= 2}` extracts to `{x= 1; y= 2}`.
Both should extract to `{x= 1; y= 2}`.

Reason : Even though records are sugar for inductive types in F*, type definitions of F* records are extracted to record type definitions in OCaml. So there is no `MkPoint` constructor in OCaml.

**Comment by nikswamy** [comment]
We should fix this discrepancy. 

But perhaps it should be fixed by forbidding the user from writing (Mkpoint 1 2) in the source language. After all, Mkpoint is an encoding detail for records and need not be visible to the user. The one place where this may be painful is when the user wants to partially apply a record constructor---in that case, she'd have to write something like `(fun y -> {x=17; y=y})` herself. But that's not so bad.
