### ISSUE TITLE
Next F* binary release

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#322]
It has been almost the same amount of commits between the beginning of the project and the last release than between the last release and now =) ...

But maybe we should wait until the extraction mechanism is entirely replaced ?

**Comment by catalin-hritcu** [comment]
We're planning a new release until ICFP, which starts in 10 days or so.

**Comment by catalin-hritcu** [comment]
The planned day for this release is Friday, 28 August.
I've started a list of things to do for the next binary release (to be updated in place, feel free to add/remove/discuss things):
- make sure the build scripts still work and see if they can be improved
- decide on a proper versioning scheme; I propose 0.9.0 for this release (and then to count 0.9.1, 0.9.2, ... until one day we're ready for 1.0.0); also add version flag (#328)
- make `--codegen OCaml-experimental` the default + remove the code for the old `--codegen OCaml`
- improve documentation and tutorial
- switch to Z3 4.4, since it has a more permissive license, making it easier to legally redistribute Z3 binaries (#327)
- round of bug fixes -- CH: we can do a round through the open issue and search for bugs that directly impact users (e.g. #125, #153, #183, **#246**, #250) and which are relatively easy to fix
- parallel SMT solving for the native binary (#146)
- extraction to F# (#94) -- CH: we can't block 0.9.0 on such a large task, so this might have to wait for 0.9.1 (post ICFP)

**Comment by jeb2239** [comment]
Thank you very much!

**Comment by veikkoeeva** [comment]
:+1:
