### ISSUE TITLE
Reduce terms using normalizer

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#357]
On 20 April 2015 Nik was writing on fstar-priv-club about adding a `reduce` primitive:

> 1. Explicitly triggering computations in the type-checker
>    (a) Should be able to prove this directly without calling SMT

```
 assert (reduce (quicksort (fun x y -> x < y) [3; 2; 1]) = [1; 2; 3])
```

I think this would be very nice to have, so I'm creating separate a issue for it.

In order to be useful in proofs we would need ways to finely control the reduction (as in Coq and SSReflect, although I'm not sure whether their design is optimal).

**Comment by catalin-hritcu** [comment]
Some discussion on reduction also happened in #267.

**Comment by nikswamy** [comment]
FYI, this now works via Z3 (cf #427) in just a few milliseconds.

From Ftar.List.Tot:
```
let test_sort = assert (sortWith (compare_of_bool (<)) [3; 2; 1] = [1; 2; 3])
```

However, it is still not recommended to use Z3 to normalize larger terms. 

For instance:

```
let test_sort = assert (sortWith (compare_of_bool (<)) [1; 2; 3; 4; 5; 6; 7] = [7; 6; 5; 4; 3; 2; 1])
```

takes around 15 seconds with fuel 20, and 8 elements times out even with 200 seconds.

**Comment by nikswamy** [comment]
Also, for the record: here's a discussion from slack

Meanwhile:

[12:34]  
retaining
```let rec pow2 (x:nat) : Tot pos =
  match x with
  | 0  -> 1
  | _  -> 2 `op_Multiply` (pow2 (x-1))
```

[12:34]  
is a better way to go

[12:35]  
since with this definition, the solver can easily recover pow2_lem whenever it needs it

[12:35]  
OTOH, the converse direction is not so easy: although we can prove pow2_lem, providing for Z3 to use automatically requires writing an SMTPat for it. And there is no good pattern to use without entering a matching loop.

[12:36]  
So, the style I recommend is using the recursive definition of pow2 above

[12:36]  
and then proving this lemma:

[12:36]  
 ```val pow2_values: x:nat -> Lemma 
  (let p = pow2 x in 
   match x with 
   | 0  -> p=1
   | 1  -> p=2
   | 8  -> p=256
   | 16 -> p=65536
   | 31 -> p=2147483648
   | 32 -> p=4294967296
   | 63 -> p=9223372036854775808
   | 64 -> p=18446744073709551616
   | _  -> True)
#reset-options "--initial_fuel 100 --z3timeout 200 --max_fuel 100 --initial_ifuel 0 --max_ifuel 0"
let pow2_values x = ()
```

[12:36]  
which takes 85seconds on my machine

[12:37]  
and providing pow2_values with an SMTPat of `pow2 x` so the solver knows many common values of `pow2 x` for free

[12:38]  
of course, with better support for F* proofs by normalization, that 85 seconds should be much faster

protz [12:41 PM]  
and with proof by normalization we will have to remove --use_native_int

[12:41]  
otherwise with that sort of functions that'll just overflow

nik [12:43 PM]  
and with --use_hints, the proof of pow2_values goes through in 10seconds

**Comment by nikswamy** [comment]
`assert_norm` is getting close to what we want. 

There are still some limitations: 

1. We currently reduce only
    Const.op_Addition
    Const.op_Subtraction
    Const.op_Multiply
    Const.op_Division 
    Const.op_LT        
    Const.op_LTE
    Const.op_GT 
    Const.op_GTE
    Const.op_Modulus

Adding binary boolean operators is easy and unary operators is easy; will do that soon.

2. We don't yet reduce decidable equality `( = )`. Given that we compile this to the platform's polymorphic equality, it's not exactly clear yet how best to do this on given the syntax of terms. Discussing with @aseemr  ...

**Comment by nikswamy** [comment]
Also: note that the normalization of primitive arithmetic is only sound in the OCaml version of F*.

F# support will come soon.

**Comment by jkzinzindohoue** [comment]
Looks very promising !
Can you give some intuition about how this works ?
For instance is there a maximum number of iterations ? What happens if I try an assert_norm query on a diverging function ?
Also what hypothesis are usable by the normalizer ? For instance if I write a 'cut' before an 'assert_norm' should I expect it to be used ?

**Comment by s-zanella** [comment]
An annoying limitation is that while top-level definitions are unfolded during normalization, this doesn't seem to be the case for local `let` definitions.

This works:
```F#
let l = [1;2]
let foo = assert_norm (List.Tot.length l == 2)
```

This doesn't:
```F#
let bar = 
  let l = [1;2] in
  assert_norm (List.Tot.length l == 2)
```

Any idea why?

**Comment by nikswamy** [comment]
This is indeed annoying. I think the reason is that the generated VC is roughly of the form:

```forall l. l = [1;2] ==> normalize_term (List.Tot.length l == 2)```

The normalizer does not attempt to rewrite the term based on equality hypotheses, so the proof cannot complete within the normalizer.

We have talked about adding qualifiers to local lets, e.g., 

```
let bar = 
   unfold let l = [1;2] in
   assert_norm (List.Tot.length l == 2)
```

Which would force `l`'s definition to be inlined instead of using the equality hypotheses.

Another more general strategy is to use a rewriting tactic. See https://github.com/FStarLang/FStar/wiki/F%2A-tactics
This is beginning to become quite a real possibility in the timeline of a couple of months.

Meanwhile, adding the unfold qualifier on local lets could be an easy stop gap.

**Comment by s-zanella** [comment]
I now remember you explaining this to me, sorry for asking it again. It's documented now :)

I naively tried to use `unfold` hoping it would work for local lets. That would be a nice temporary solution.

**Comment by s-zanella** [comment]
Until we have `unfold` for local `let` definitions, @jkzinzindohoue found a workaround using `unfold` and `normalize` that works for the example that motivated the discussion:

```F#
unfold let p (#a:Type0) (init:list a) : GTot Type0 =
  normalize (0 < L.length init) /\ normalize (L.length init < UInt.max_int 32)

unfold let q (#a:Type0) (len:nat) (buf:buffer a) : GTot Type0 =
  normalize (length buf = len)

(** Concrete getters and setters *)
assume val createL: #a:Type -> init:list a -> StackInline (buffer a)
  (requires (fun h -> p #a init))
  (ensures (fun (h0:mem) b h1 ->
     let len = L.length init in
     len > 0
     /\ ~(contains h0 b)
     /\ live h1 b /\ idx b = 0 /\ length b = len
     /\ frameOf b = h0.tip
     /\ Map.domain h1.h == Map.domain h0.h
     /\ modifies_0 h0 h1
     /\ as_seq h1 b == Seq.of_list init
     /\ q #a len b))

let test (u:unit) : St unit =
  push_frame();
  let x = createL [0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y] in
  assert (length x = 20);
  pop_frame()
```

**Comment by s-zanella** [comment]
Probably nicer workaround, found by @nikswamy:

```F#
assume val createL: #a:Type -> init:list a -> StackInline (buffer a)
  (requires (fun h -> 0 < L.length init /\ L.length init < UInt.max_int 32))
  (ensures (fun (h0:mem) b h1 ->
     let len = L.length init in
     len > 0
     /\ ~(contains h0 b)
     /\ live h1 b /\ idx b = 0 /\ length b = len
     /\ frameOf b = h0.tip
     /\ Map.domain h1.h == Map.domain h0.h
     /\ modifies_0 h0 h1
     /\ as_seq h1 b == Seq.of_list init
     ))

let test (u:unit) : St unit =
  push_frame();
  let l = [0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y; 0y] <: Tot (list _) in
  assert_norm (L.length l = 20);
  let x = createL l in
  pop_frame()
```

**Comment by nikswamy** [comment]
Function application in F* is, in general, monadic application. i.e., you can apply a function to a computation and the computation will be sequenced and the function will be applied to the result of that computation.

There is an important special case of the application rule that specifically handles the application of a function to a `Tot` argument. Consider `f e`, where `f : x:t -> C` and `e: Tot t`. In this case, the result computation type is just `C[e/x]`, without any monadic application involved. 

Let bindings of `Tot` terms `let x = e in e'` is equivalent to `(fun x -> e') e)`. So, if you can prove (e.g., by adding an annotation) that `e` has computation type `Tot _`, then F* will substitute `e` for `x` in the type of `e'`, just as it does for function application.

In particular, this behavior is useful in conjunction with `assert_norm`

**Comment by nikswamy** [comment]
There's been a LOT of work on normalization with multiple strategies including interpretation, normalization-by-evaluation and native compilation. 

This issue was very influential!

But I don't think it adds much value remaining open. 

This wiki page has some useful content:
https://github.com/FStarLang/FStar/wiki/Using-SMT-fuel-and-the-normalizer

It would be nice to have a tutorial chapter on using the normalizer. Adding that to #1566
