### ISSUE TITLE
Wrong precedence of infix operators

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#358]
Some infix operators, like /\ and \/, have a strange precedence.
Examples from `fstar --print_implicits --dump_module Prims`
```F#
datacon Prims.And : (#p:Type -> #q:Type -> Tot ((p -> q -> Tot p) /\ q))
type Prims.l_iff p:Type q:Type : Type = (p ==> ((q /\ q) ==> p))
datacon Prims.Left : (#p:Type -> #q:Type -> Tot ((p -> Tot p) \/ q))
datacon Prims.Right : (#p:Type -> #q:Type -> Tot ((q -> Tot p) \/ q))
```
What are exactly the consequences of this? 
Parenthesizing to enforce the expected precedence in prims.fst doesn't break any of the unit-tests.

**Edited**: nothing wrong with the type of constructors, but the precedence is still wrong.

~~The type of the "constructors" is very odd; can they be applied at all?~~

~~Similary, it's possibly to write types like~~
```F#
type op_Amp_Hat (p:Type) (q:Type) =
  | C : p -> q &^ q
```
~~with similarly weird constructors `C : ( -> Tot (op_Amp_Hat (p -> Tot q) q))`~~

**Comment by s-zanella** [comment]
This one should be easy to fix, isn't it?

**Comment by catalin-hritcu** [comment]
Partial fix, so probably Github shouldn't have closed this

**Comment by s-zanella** [comment]
Github is too smart (or dumb). 
A long term fix should give precedence to other infix operators (or at least `/\,\/,==>`) over `->`.

**Comment by vkanne-msft** [comment]
@nikswamy can you kindly verify this ?

**Comment by s-zanella** [comment]
AFAIK, this hasn't been fixed:
```F#
module M
type t (p:Type) (q:Type) =
  | T: p -> q -> p /\ q
```
fails with `Expected a constructor of type M.t; got Prims.l_and`

**Comment by msprotz** [comment]
This hasn't been fixed by my patch... the logical operators have been left unchanged. Probably worth a discussion to see if we want to make them bind tighter than the arrow, but this tricky, because in your bug report you want both:

```
p -> q -> p /\ q
```

and

```
p /\ e1 == e2
```

to parse, i.e. `/\` binds tighter then the arrow, but `==` binds tighter than `/\`.

Right now, the precedence (from looser binder to tighter binding) is as follows:

DISJUNCTION, CONJUNCTION, OPINFIX0, OPINFIX1, OPINFIX2, ARROW, OPINFIX3, OPINFIX4

`==` is an OPINFIX0 (OPINFIX0C, precisely)

Fixing the bug the way you describe requires making `/\` an OPINFIX3, which means it now binds tigher than `==`... looks like we can't have both at the same time...

**Comment by msprotz** [comment]
Ok, chatting with @nikswamy , we realized that I was wrong and that, theoretically, we could make the arrow bind more loosely while keeping the current hierarchy. There were a bunch of other problems, including the fact that 'p = q' is a type, that has lower precedence than the arrow, and that:

let x: t = e

now becomes a problem, because t can be an arrow, or anything with a higher precedence than an arrow, including p = q, and then you have a shift/reduce conflict on let x: p = q = e

After doing a bunch of bugfixing, this appears to be solved.

**Comment by msprotz** [comment]
https://github.com/FStarLang/FStar/wiki/Parsing-and-operator-precedence
