### ISSUE TITLE
Skip comments in interactive mode

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#361]
A file like
```F#
module F
(*
#endif
*)
```
fails to typecheck with the --in flag because the `#endif` inside the comment is interpreted as the interactive mode *command* #end. This kind of comments is common in miTLS, so it would be nice if the interactive mode ignored them.

**Comment by cpitclaudel** [comment]
I'm not sure how I feel about this, actually. Consider the following situation: the buffer has 

    let a = 1 (* Blah | blah *)

with `|` indicating the position of the point. They press `C-c RET` in Emacs; F* will return a parse error, because it receives:

    let a = 1 (* Blah 
    #end

If it ignores the #end instead, then it has no way to know when the message actually end, except to wait for a proper termination; which means that Emacs will think that it's done sending and that F* is processing the buffer section, whereas F* will think it has not yet received all the text.

For comments, the IDE can strip them before sending. But for multi-line strings that won't work, and so the same problem will appear. The only safe option here is to ensure that the data and control are separate in the protocol (it would solve other issues as well, with encoding for example. We fixed this in Dafny by using a different protocol, which base64-encodes everything in the message (see https://github.com/boogie-org/boogie-friends/blob/master/emacs/inferior-dafny.el#L68 for docs)

**Comment by s-zanella** [comment]
This is definitely not worth the trouble of modifying the protocol, that can wait. For the time being, a "Fly Past Comments" option à la ProofGeneral is more than enough if it's not too hard to implement. 

To complicate things further, note that the following is perfectly valid F*: `val f : #pop:Type -> unit`

The snippet below shows other niceties of mixing data and control: it type checks from the command line and assumes False, but it fails to type check `absurd` in Emacs.

```F#
(*--build-config
    options:--log_types --print_implicits --verify_module M;
    other-files:
--*)
module M


(** The above two empty lines are important **)
type t (#a:Type) (#b:Type) (#c:Type) = a

type pop  = False
type push = unit

type True = t
         #pop
         #push
         #pop

assume val nice : True


let absurd : False = nice
```

**Comment by cpitclaudel** [comment]
I don't think fly past comment does this in PG (instead, it does not record control points after comments), but stripping out comments is relatively easy :)

**Comment by cpitclaudel** [comment]
Done on the Emacs side!

**Comment by s-zanella** [comment]
Thanks!
