### ISSUE TITLE
Inconsistency: bad simplification of constructivized logical connectives

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#380]
Here's an example: 

``` F#
val f : p1:(True \/ True) -> p2:(True \/ True) -> Lemma (p1 = p2)
let f p1 p2 = ()

val absurd : unit -> Lemma False
let absurd () = f (Left T) (Right T)
```

**Comment by catalin-hritcu** [comment]
Ouch!

**Comment by aseemr** [comment]
It seems that when encoding ```f```, the SMT encoding is optimizing ```True \/ True``` to just ```True``` (https://github.com/FStarLang/FStar/blob/master/src/tosmt/term.fs#L200), hence proving ```p1 = p2```. This contradicts the distinct constructor axiom for ```Left``` and ```Right``` in ```absurd```.

**Comment by catalin-hritcu** [comment]
Such simplifications should be done only in a proof-irrelevant context like `x:t{_}` or `requires _`, but not for top-level types (context `_`).

**Comment by aseemr** [comment]
A similar optimization is also done in the normalizer (https://github.com/FStarLang/FStar/blob/master/src/tc/normalize.fs#L244). Commenting out these simplifications gives the right behavior of failing ```f```.

**Comment by catalin-hritcu** [comment]
@aseemr  Can you run the regression and see if there is a noticeable slowdown without this simplification? Maybe I'm naive, but I don't really expect the SMT solver to stumble on such simple things.

**Comment by s-zanella** [comment]
Still reproducible with `--universes` and quite worrisome.

**Comment by nikswamy** [comment]
ah, oversight. My planned fix was to have defined in prims

```
type l_and p q = squash (c_and p q)
type l_or p q = squash (c_or p q)
```
etc. 
Just as we already do for `l_Forall` and `l_Exists` etc. 

In this case, the simplifications done by normalization (which are only on l_and, l_or, etc.) are restricted to occur in proof-irrelevant portions of the term only.

This rules out your counterexample. But, I have regressions in FStar.SquashProperties, unsurprisingly, which is written against the old types. Will fix and push.

**Comment by nikswamy** [comment]
I now realize that my earlier fix was incomplete. 

The idea of the previous fix was that by defining `/\, \/` etc. to be squashed types, then simplifying `p /\ True` to `p` is fine ... **but only if `p` is squashed too!** 

It's a common error on my part to implicitly think of `p` and `q` as props in `p /\ q`. We've had several attempts to turn make `/\ : prop -> prop -> prop` etc, but so far haven't succeed. 

Is it worth trying again, @catalin-hritcu ? Can you remind me of the state of play on our previous attempt at using `prop` more systematically?

**Comment by catalin-hritcu** [comment]
@nikswamy  The high level status is "it's complicated". I took some notes though and I have a branch where I attempted that, so could swap back in and discuss this at some point.

**Comment by nikswamy** [comment]
Context from slack:

A (slightly convoluted) proof of false in F* https://github.com/FStarLang/FStar/issues/987 ; I suspect the normalizer to simplify incorrectly something @nik @aseem @guido
 

17 replies
catalin [12 hours ago] 
Reminds me of this https://github.com/FStarLang/FStar/issues/380

kyod 
[11 hours ago] 
Indeed the problem is quite similar but I don't know about the fix

nik 
[6 hours ago] 
hmm, interesting. wonder when this was introduced ... the normalizer has had a bunch of changes in the last few months

nik [6 hours ago] 
including, e.g., a change a couple of weeks ago related to how we reduce primitive operators

nik 
[6 hours ago] 
if anyone has time to look at this before I do, some bisection of the history would help narrow down the cause

guido [5 hours ago] 
bisecting now

nik 
[5 hours ago] 
i also wonder if #380 has recurred

nik [5 hours ago] 
i don't think we have this sort of example among our negative tests (though I could be wrong) ... we really should

guido [5 hours ago] 
Bisect correctly points to this: 12706846e69f55404f104d5e4a61652a45cb96ba. But I don't get it..

kyod [4 hours ago] 
It seems that using the debug_level Simplification is relevant

kyod [4 hours ago] 
Basically all the code of https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.Normalize.fs#L587 is only valid when the second operand is prop-like

nik 
[2 hours ago] 
strange: that commit looks pretty irrelevant

nik 
[3 minutes ago] 
@kyod ... see my remark in #380 (reopened) (edited)

nik 
[2 minutes ago] 
it's more than simply requiring that the second operand is prop-like ... which is in fact the case now, at least when Simplify steps are relevant (edited)

nik 
[2 minutes ago] 
since `/\` etc. are squashed

nik 
[1 minute ago] 
the maybe_simplify function needs to ensure that what it returns is also prop like (at least  when it does Simplify)

nik 
[< 1 minute ago] 
and this is violated in cases like: https://github.com/FStarLang/FStar/blob/master/src/typechecker/FStar.TypeChecker.Normalize.fs#L603

**Comment by kyoDralliam** [comment]
That's also what I meant : for the simplification of true or false to be sound the other operand needs to be a prop. One possible solution would be to "always" squash the result and to add another simplification step from `squash (squash a)` to `squash a`

**Comment by nikswamy** [comment]
yep, that's a possibility too.

But, if we can get the prop thing working, I think it would be more pleasing. 

After all, just forbidding people from writing strange things things `p /\ int` is also good.

**Comment by aseem** [comment]
I think you added the wrong aseem, adding @aseemr .

**Comment by nikswamy** [comment]
Sorry ... thanks!

**Comment by cpitclaudel** [comment]
@kyoDralliam just gave me a summary of the issue; here it is in code form:

```
let single_inhabitant t = 
  forall (x y: t). x == y

let single_inhabitant_and p q
    : Lemma (single_inhabitant (p /\ q)) = ()

let single_inhabitant_bool ()
    : Lemma (single_inhabitant bool) =
  assert (bool == (True /\ bool)); // Woops.  The normalizer simplifies `True /\ bool` into bool instead of `squash bool`
  single_inhabitant_and True bool

let falso () : Lemma False =
  single_inhabitant_bool ();
  assert (true == false)
```

**Comment by nikswamy** [comment]
The solution I chose was roughly what @kyod proposed. `p /\ True` is simplified to `Prims.auto_squash p`, where I added `private let auto_squash p = squash p` in Prims.

And when `p` is known to be a sub-singleton (its head constructor is`/\`, `==>`, `squash`, `auto_squash` etc.), then `auto_squash p = p`.

I resorted to introducing `auto_squash` after several failed attempts at just using `squash` directly. The trouble with just using `squash` was that this would then simplify away things like `squash (squash p)` even when the programmer really intended to write this for whatever reason. 

Using `auto_squash` and marking it private means that a programmer can't write this themselves, it can only be introduced automatically by the simplifier and its then free to eliminate it when it sees fit.

I still think the solution with `prop` would be cleaner and I hope we can get to that some day. But, meanwhile, I think this hole is now plugged. Would be happy to have someone review the changes in Normalizer.maybe_simplify, if anyone's interested in that.
