### ISSUE TITLE
Composability of the build-config special comments

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#402]
I'm cleaning up Abhishek's code -- among other things, I'm making sure all of the files have proper build-config commands. There are several problems.

- If my current file A.fst depends on B.fst, and B.fst needs C.fst, then A.fst must mention B.fst and C.fst; this is not composable.
- I'm effectively laying out the dependencies for the build in the comments; then, I will need to do that again for the Makefile which will also be cleaned up.
- I need to include a massive boilerplate every time (ext.fst set.fsi heap.fst st.fst all.fst)

Here's a proposal:
- the interactive mode should parse the build-config lines recursively, so that they are composable (i.e. if a has "other-files: b.fst" and b has "other-files: c.fst", then fstar --in a.fst should also read b.fst AND c.fst)
- this would allow me to define a "base.fst" file in my current directory that includes all the boilerplate; that way, I wouldn't cargo-cult the same five lines at the beginning of all the files
- fstar should be able to interpret these special comments in batch mode too so that we don't have to provide the list of files on the command-line, OR it should be able to generate a Makefile from these special comments -- that way, the dependencies are not duplicated twice.

Thoughts?

Cheers,

Jonathan

**Comment by msprotz** [comment]
Forgot to mention: it should be the default behavior to admit fsi's. I claim that it's up to the build system to properly check fst's again fsi's (just like in OCaml, for instance).

**Comment by s-zanella** [comment]
@mlr-msft asked for the same thing a while ago (#272). He actually worked on implementing it and pushed some code to his own fork, but I haven't tried it.

Personally, I think that even better than interpreting build-config options recursively, we are in urgent need of a standalone tool to compute dependencies (like ocamldep). One can use such a tool in a Makefile, and it isn't hard to integrate with Emacs interactive mode. For instance, in miTLS, we use an elisp snippet to call a target in a Makefile that generates a build-config block for every file. This is not too complicated to do because our dependencies are mostly linear, but it would be harder for projects with a more complex structure.

**Comment by mlr-msft** [comment]
After [SOSP 2015](http://www.ssrc.ucsc.edu/sosp15/) next week, I will be devoting more of my time to F\* contributions. 

First, I will finish up current work on transitive dependencies (i.e. interpreting `build-config` recursively) and submit that as a stop-gap. Afterwards, I have agreed to begin work on a standalone utility that works like *ocampdep* just as @s-zanella described.

**Comment by msprotz** [comment]
Yes. We probably need to change the module system of F* to have an easier mapping between file and module name; that way, we could get rid of the build-config thing altogether and have `fstar --in` automatically fetch the required file when hitting an `open` statement.

**Comment by s-zanella** [comment]
@mlr-msft Thanks. Looking forward to your implementation of dependency analysis. 
@msprotz mapping module names to files is a heuristic we can use, but I'm not sure if we want to impose it, e.g., at some point we may want to have first class modules.

**Comment by catalin-hritcu** [comment]
The rest of this is now discussed in #438, closing.
