### ISSUE TITLE
Dynamically checking refinements in extracted code

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#432]
I try to create template for mixed F#/F\* project. I have some ideas and questions and I want to discuss them.
- Code generation should be "per file", not "per module". If I want to generate code for Program.fst, then I should get one file with name Program.fs even more than one module are declared in fst file (default name should be equals to source fst file name). 
- For public functions (all functions are public by default) dynamic type checking should be generated.
  Example.
  F\* code:

```
module Program

let isDigit x = x >= 0 && x <= 9

type digit = x:int{isDigit x}

let makeNum d1 (d2 : digit) = 
    d1 * 10 + d2
```

Generated F# code:

```
#light "off"
module Program
open Prims
let isDigit : Prims.int  ->  Prims.bool = (fun ( x  :  Prims.int ) -> ((x >= (Prims.parse_int "0")) && (x <= (Prims.parse_int "9"))))

type digit =
Prims.int

let makeNum : Prims.int  ->  digit  ->  Prims.int = (fun ( d1  :  Prims.int ) ( d2  :  digit ) -> ((d1 * (Prims.parse_int "10")) + d2))
```

Type of the second argument of `makeNum` function is `digit`, but in F# code it is just alias for `int`. I think that should be generated something like this (dynamic checking for digit is added)

```
#light "off"
module Program
open Prims
let isDigit : Prims.int  ->  Prims.bool = (fun ( x  :  Prims.int ) -> ((x >= (Prims.parse_int "0")) && (x <= (Prims.parse_int "9"))))

type digit =
Prims.int

let makeNum : Prims.int  ->  digit  ->  Prims.int = 
   (fun ( d1  :  Prims.int ) ( d2  :  digit ) -> 
      if isDigit d2
      then ((d1 * (Prims.parse_int "10")) + d2)
      else failwith "Some information"
   )
```
- Why primitive types does not generated directly as native types? (why `Prims.int`, not just `int` or `System.int`. Or bigint if it is really critical). I clearly understand that own implementation of primitive types an operations in F\* is necessary for verification. But may be it is not necessary in generated code.

**Comment by nikswamy** [comment]
1. Regarding code gen per file rather than per module:
We will soon switch to enforcing as 1-1 correspondence between files and modules.

2. Adding dynamic checks on the boundaries is an interesting research problem. Not all F\* types can be enforced via dynamic checks. (Consider the type `f:(int -> Tot int){forall x y. x < y ==> f x < f y}`) One simple proposal that has been on the table for a while is to enforce that at the external interface the erasure of F\* types to F\# types must be the identity. That would mean that the user would have to wrap functions that receive arguments like digit with their own dynamic checks before making them available at the interface.

3. We emit `Prims.int` etc. to easily support code generation with multiple integer representations. The default is bigint. But, if you pass the '--use_native_int' flag, and link with `lib/fs/native_int/prims.fs`, then you'll get platform integers. However, beware, compiling with this flag is not sound since it ignores overflow.

**Comment by catalin-hritcu** [comment]
> Not all F* types can be enforced via dynamic checks. (Consider the type `f:(int -> Tot int){forall x y. x < y ==> f x < f y}`) 

Let me nitpick a bit, since this type is actually dynamically checkable. One just needs to wrap `f` with a contract that does the checking on each call, which is just standard higher-order contracts.

**Comment by catalin-hritcu** [comment]
Ah no, sorry, I'm an idiot, didn't see that the check was relational. You're right, this is hard to check dynamically without memoizing f completely.

**Comment by gsvgit** [comment]
We are playing with advanced data structures verification with F*. Seems that code generation is really interesting problem. In some cases a big number of dynamic checks can significantly decrease performance of target code. It may be critical for verified data structures: in this case we can not create only one public function with dynamic checks. All functions should be public.

Hm...  What do you think about code generation or F* and F# interaction as research topic for students? Could it be formulated as actual and not "F* only dependent" problem?

**Comment by nikswamy** [comment]
There are two kinds of dynamic checks that are necessary when compiling to F#. 

1. Checked casts within a verified program

2. Runtime checks at the interface between F* and F#

The first kind of check is guaranteed to always succeed, so it really is wasted work. However, to convince F# that an F* program is well-typed, these kinds of casts need to be inserted. In OCaml, these casts have zero cost, since we use Obj.magic there. However, F# has no such feature. It may be possible to minimize the cost of these casts by a combination of dropping into unsafe code in .NET and using a fancier translation to F# that relies on more features of the .NET type system to capture more of the F* type system within .NET. You might look at an old paper for some ideas there: http://research.microsoft.com/apps/pubs/?id=120933

The second kind of check at the boundaries is unavoidable for sound interop. Then again, as explained earlier, only certain kinds of properties can be checked dynamically. It would be interesting to formalize some dynamically checkable subset of F* and insist that the interface between F* and the rest of the world be at this type so that wrappers can be automatically generated. You could formulate this problem independently of F*. You might look at Cormac Flanagan's work on hybrid typing for this. Or, more recently, you could look at Eric Tanter's work on gradual typing in Coq.

**Comment by vkanne-msft** [comment]
Only 1 module per file now. 

Dynamic checks are not in our roadmap.

**Comment by A-Manning** [comment]
Would it be possible to add dynamic checks only for dependent types formulated in terms of booleans, as opposed to type? for example, through extracting to something like  
```
if (_boolean condition_) then (_function_) 
else ()
```

**Comment by nikswamy** [comment]
Yes, we would at least need some decidability condition like that.

**Comment by s-zanella** [comment]
@A-Manning what you suggest is essentially what @nikswamy suggested in 2. above (see https://pleiad.cl/papers/2015/tanterTabareau-dls2015.pdf Section 8 for an example of how this could work).

Note also that when you have a refinement type formulated in terms of booleans, F* inserts an implicit `b2t` coercion that casts the boolean as a `Type`.

**Comment by A-Manning** [comment]
That's a very interesting paper - is there interest in adding this into F*? vkanne-msft stated earlier that 'Dynamic checks are not in our roadmap.', but it seems like this is important if F* is to be usable as a general-purpose language. Should this be taken to mean that there are no immediate plans to implement dynamic checks, or that dynamic checks are intentionally disregarded? If it's the former, then perhaps this should be added to the list of project topics on F*. Regardless, type erasure should be made explicit in the wiki/tutorial.

**Comment by catalin-hritcu** [comment]
Since this was anyway marked as "discussion", I don't see any harm keeping this open.

**Comment by nikswamy** [comment]
If it's not on our roadmap then what's the point? With vkanne, protz and myself, we were closing issues that are not planned to be addressed.

**Comment by catalin-hritcu** [comment]
I guess it's our choice whether we want to allow this kind of open discussions to happen as GitHub issues or whether we want to kill/close them and say they have to happen ... on the public mailing list (which very few people use nowadays)? I wouldn't have a problem with that, but it should be made explicit.

**Comment by nikswamy** [comment]
Commenting on closed discussions is still possible, right? Anyway, I don't have a strong opinion one way or another, but we should have a consistent policy so that issues don't flip-flop between open and closed randomly.
