### ISSUE TITLE
Question on verifying an iterative version of factorial

### ISSUE THREAD

**Issue by stfairy** [FStarLang/FStar#436]
I wrote the following code

```ocaml
module Factorial

val factorial: x:int{x>=0} -> Tot (y:int{y>=1})
let rec factorial n = if n = 0 then 1 else n * factorial (n - 1)

(* How to use this? *)
val factorial_arg: i:nat -> Lemma (factorial i = factorial ((i+1)-1))
let rec factorial_arg i = admit()

val myfact_accum:
        i:int{i>=1} ->
        a:int{a=factorial (i-1)} ->
        Tot (accum_result:int{accum_result=factorial i})
let myfact_accum i a = a*i

val myfact_iter:
        n:int{n>=0} ->
        i:int{i>=1 && i<=n+1} ->
        accum:int{accum=factorial (i-1)} ->
        Tot (iter_result:int{iter_result=factorial n})
let rec myfact_iter n i accum =
        if i>n then accum
        (* else myfact_iter n (i+1) (accum*i) *)
        else myfact_iter n (i+1) (myfact_accum i accum)

val myfact: x:int{x>=0} -> Tot (y:int{y=factorial x})
let myfact n = myfact_iter n 1 1
```

But F* is complaining as follows.

```
$ fstar.exe factorial.fst 
factorial.fst(24,26-24,48): Subtyping check failed; expected type _6_1870:accum:int{(accum = (factorial ((i + 1) - 1)))}{(%[n; (i + 1); _6_1870] << %[n; i; accum])}; got type accum_result:int{(accum_result = (factorial i))}
Error: 1 errors were reported (see above)
```

I suspect I have to use the `factorial_arg` lemma, but not sure how to do that.

Thanks.

**Comment by s-zanella** [comment]
Your code is perfectly fine, you just need to give F* an extra hint so that it can check that the function `myfact_iter` is indeed total. That hint comes in the form of a `decreases` clause added to the `val` signature:

```OCaml
val myfact_iter:
        n:int{n>=0} ->
        i:int{i>=1 && i<=n+1} ->
        accum:int{accum=factorial (i-1)} ->
        Tot (iter_result:int{iter_result=factorial n})
        (decreases (n + 1 - i))
```
How does this work? The decreases clause provides a measure as a function of the arguments that acts as an argument for termination. In this case, we are using the order `<` on naturals to justify that every recursive call is done on *smaller* arguments. Since the `<` relation is well-founded, the measure cannot continue decreasing indefinitely and the function must terminate. 

Note that intuitively, the measure that one would like to use is simply `n - i`. However, it will not work because the value of the measure on the recursive call is -1 in case `n = i`, not a natural number. That measure would work if one *unfolds* that case with an extra `if`, returning `accum * n`.

See [Section 5 of the tutorial](https://www.fstar-lang.org/tutorial/tutorial.html#sec-termination) for a more in depth discussion of termination.

**Comment by stfairy** [comment]
This makes a lot more sense.  Thanks. :-)
