### ISSUE TITLE
Strange behavior of assertion checking

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#437]
We use current (01.12.2015) online F* interpreter from https://www.fstar-lang.org/tutorial/ . In order to investigate problems with some properties we try to check some asserts (full code is in attached file). Assertions checking demonstrate strange behavior. Is it a bug or code really incorrect? Detail provided below.

0) There are 3 identical asserts in the attached file (lines 27, 40 ,49)
1) Run attached file verification. Assert on line 40 failed with ```Ill-kinded type``` message.

log:    
```
ex1a-safe-read-write1(38,24-38,32): Subtyping check failed; expected type e1:nat{(e1 > 0)}; got type int
ex1a-safe-read-write1(40,10-40,54): Ill-kinded type
``` 
2) Comment out line 28

Code :
```
let cc = 
    assert(ld(Join(Unit 1) (Join (Unit 1) Nil ) ) < 7)
    //;1
```
  Run verification.
  Assert on line 40 failed with ```assertion failed``` message.

log:
```
ex1a-safe-read-write1(38,24-38,32): Subtyping check failed; expected type e1:nat{(e1 > 0)}; got type int
ex1a-safe-read-write1(40,4-40,55): assertion failed
Error: 2 errors were reported (see above)
```
3) Comment out line 50. Line 28 still commented out.

Code:
```
let staticChecking() =
    assert(ld(Join(Unit 1) (Join (Unit 1) Nil) ) < 7); 
	//let x = Nil in 
	let y = Join (Unit 2) (Unit 3) in 
	ld y
```
  Run verification.
  There are no any messages on assertions.

Log:
```
ex1a-safe-read-write1(38,24-38,32): Subtyping check failed; expected type e1:nat{(e1 > 0)}; got type int
ex1a-safe-read-write1(43,21-43,23): Subtyping check failed; expected type e1:nat{(e1 > 0)}; got type nat
Error: 2 errors were reported (see above)
```

Why checking of context independent assertions is dependent on removing of unused code?

[assertion_tests.txt](https://github.com/FStarLang/FStar/files/48349/assertion_tests.txt)

**Comment by catalin-hritcu** [comment]
Quick answer, probably others can answer this better: asserts simply become part of the large "weakest precondition" (a logical formula) associated to each top-level declaration. In general asserts cannot be checked independently from the rest of the code of a definition (e.g. `let x = e in assert (x > 42)` can't be checked without looking at `e`), and there is no special-casing when they are in fact independent from the rest. Also, when using an SMT solver to discharge logical obligations, error messages are nowhere as good as in a normal programming language. For once, you could see _spurious_ error messages because the SMT models are not always minimal (https://github.com/FStarLang/FStar/issues/45). Then, some errors could hide others, and only fixing the first will lead to the others being found.

All this being said, we should look more carefully at your code and see whether you're experience anything beyond the usual pain of programming with an SMT solver :)

**Comment by s-zanella** [comment]
I had a look at the code. The `assertion failed` message is definitely spurious, probably due to #45 as Catalin said.

I'm puzzled as to why modifying an unrelated definition (i.e. commenting line 28) results in a different second error message. My guess is that the change results in Z3 checking the mutually recursive definition in a different state, and thus returning different models as counterexamples.

Anyway, the only explicit assertion in the code is indeed context-independent and valid. The real errors are elsewhere and are correctly reported by F*. Namely, some calls in the mutually recursive definition of `walk` and `finish` are ill-typed. For example, the call `walk (e1 - 1) e2 (y::rights) x` at line 38 is only well typed if `e1-1` is a positive integer, but `e1` may be `1`, in which case `e1-1` isn't positive. Also both `walk` and `finish` are specified to be total but the decreasing measure, if there is any, is non-trivial and must be given explicitly.
