### ISSUE TITLE
Forbid (or allow?) self-references to the current module

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#451]
The module `Heap` (file `heap.fst`) references itself, i.e. the module `Heap`, at line 53.

```
  53 opaque logic type modifies (mods:set Heap.aref) (h:heap) (h':heap) =
```

This should be flagged and rejected by the type-checker.

**Comment by beurdouche** [comment]
This is not possible anymore because `auto-deps` considers it as a cyclic dependancy

**Comment by catalin-hritcu** [comment]
@beurdouche: What if one uses `--explicit_deps` though?

**Comment by beurdouche** [comment]
```
module Test

assume val res: nat -> Tot nat
let f a = Test.res a
```
```
fstar --explicit_deps Test.fst
Verifying module: Test
All verification conditions discharged successfully
```
Hum ...

**Comment by beurdouche** [comment]
Ok I wasn't testing the correct bug anyway...

**Comment by s-zanella** [comment]
Self-references are still allowed with `--universes` and `--explicit_deps`.

**Comment by nikswamy** [comment]
@tahina-pro revised the desugaring phase and name resolution. Is it still open?

**Comment by tahina-pro** [comment]
The name resolution mechanism assumes nothing about whether references to the current modules are allowed or not. So this is still left to the dependency mechanism.
I am currently trying to have this caught by name resolution.

**Comment by tahina-pro** [comment]
My attempt failed: I could not make sure that a name was never automatically qualified by the desugaring mechanism before being resolved. In particular, this was not true for top-level let definitions.
So, I have two questions:
1. Do we still want to forbid references to the current module? What was the reason why we did not want it at the first place?
2. If so, do we still want to have the desugaring phase enforce this restriction when the user circumvents the dependency resolution using `--explicit_deps` ?

**Comment by mtzguido** [comment]
We've discussed this today with @nikswamy and @tahina-pro. First I'd like to echo both of Tahina's questions: why do we want to forbid? and; should it be a parser or desugaring error, i.e. can it be allowed internally? (afaict, `--explicit_deps` does not exists anymore).

My vote is for allowing it, if nothing breaks. Maybe I'm just missing it, but I don't see what goes wrong with allowing it (forbidding it seems arbitrary). Also, it allows for two things:

1. A "field" named as the type:
```
module M
type job = | Mk : job:int -> M.job (* `job` is shadowed *)
```
this becomes more prominent if we allow dependent records (and want to desugar to the above, cf #1184)
```
type job = { job : int } (* would raise a mysterious shadowing error *)
```

2. Disambiguating local bindings. Consider:
```
module S

let return_squash = 1

open FStar.Squash

let x : int = return_squash
```
This fails because `return_squash` is resolved to `FStar.Squash.return_squash` (of course) with no way to work around it. The local `return_squash` is out of reach.

In low-prio mode, I'll try to remove the restriction. Please shout at me if I shouldn't!

**Comment by nikswamy** [comment]
ping @mtzguido  @protz @tahina-pro 

Any resolution on this? I'm fine with permitting these references. As Guido points out, it's useful to accessing otherwise shadowed names.

**Comment by mtzguido** [comment]
I've tried a couple of times to make this work and couldn't, but I'd really like to make it work. I'll revisit this soon.

**Comment by mtzguido** [comment]
Now allowed!
