### ISSUE TITLE
Fictional Purity: Pure function which uses ref only for internal state

### ISSUE THREAD

**Issue by artella-coding** [FStarLang/FStar#454]
Is it possible to have a pure function which employs mutation but only within an internal state [sort of like the haskell `runST` monad  (https://wiki.haskell.org/Monad/ST#A_few_simple_examples)]? 

For example the following works : 

```
val is_positive : int -> bool
let is_positive i = 
    let x = ref 0 in i > 0
```

but the following does not work : 

```
val is_positive : int -> Tot bool
let is_positive i = 
    let x = ref 0 in i > 0
```

even though the latter seems to me like a pure function, since it gives the same result for a given input every single time it is run.

**Comment by catalin-hritcu** [comment]
Unfortunately this is not possible at the moment, but we are considering supporting this in the future. For more details please look at

* Section "7 Fictional purity" here: http://prosecco.gforge.inria.fr/personal/hritcu/students/topics/2016/fstar.pdf

* Section "4.3 Forgetting effects, logically" in this old draft:
https://www.fstar-lang.org/papers/icfp2015/submission.pdf

**Comment by artella-coding** [comment]
@catalin-hritcu Ah that's extremely cool thanks.

**Comment by catalin-hritcu** [comment]
Keeping track of the mailing list answer:

This is still on our list, and we've been making good progress on
providing the main enabler, by deriving Dijkstra monads “for free”
from expression level monads, which will enable extrinsic reasoning
about effectful code, as needed for supporting forgetting effects /
fictional purity.

Dijkstra monads “for free” should be landing on F* master in the next
month or so, after which we can start thinking about forgetting
effects.

Thank you for your patience :)

Catalin

**Comment by artella-coding** [comment]
@catalin-hritcu What is the status of this now? Thanks.

**Comment by catalin-hritcu** [comment]
Dijkstra monads are in master for a long time, and while their implementation has been improving they are still not yet used by default. You can look in `examples/dm4free` though for how that works. The key construct for forgetting effects is `reify` that allows to break the effect's abstraction and obtain a pure monadic implementation of an effectful program. Please see `examples/printf/SimplePrintfReify` for an example of using `reify` to forget the exceptions effect. More work is needed to be able to forget state, but it might give you an idea about how that could work? :) 
Pinging @kyoDralliam and @nikswamy in case they have more advice.

**Comment by prosecco** [comment]
We are very keen to use “reify” in our HACL* and miTLS code, and our first
use case is to go from Total ST functions (StTot?) that manipulate buffers
to Tot functions that pass sequences of bytes. I’d love to see this use
case be supported soon.

-Karthik


On 16 January 2017 at 07:35:18, Catalin Hritcu (notifications@github.com)
wrote:

Dijkstra monads are in master for a long time, and while their
implementation has been improving they are still not yet used by default.
You can look in examples/dm4free though for how that works. The key
construct for forgetting effects is reify that allows to break the effect's
abstraction and obtain a pure monadic implementation of an effectful
program. Please see examples/printf/SimplePrintfReify for an example of
using reify to forget the exceptions effect. More work is needed to be able
to forget state, but it might give you an idea about how that could work? :)
Pinging @kyoDralliam <https://github.com/kyoDralliam> and @nikswamy
<https://github.com/nikswamy> in case they have more advice.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FStarLang/FStar/issues/454#issuecomment-272784177>, or mute
the thread

**Comment by nikswamy** [comment]
While `reify` is supported and used in the F* (notably in the tactics framework), we are still far from supporting fictional purity. This requires more research.
