### ISSUE TITLE
Question concerning "exists x. p x".

### ISSUE THREAD

**Issue by VincentCheval** [FStarLang/FStar#470]
Hello,

I have a question concerning the use of lemma that proves something like `exists x:A. p x`. For instance, imagine that I have a lemma that proves: `exists x:A. p x` (let's call it Lemma_1) and for a proof of an other lemma (let's call it Lemma_2), I want to "use" this x (the existential here is not necessarily constructive), how can I extract from Lemma 1 a ghost value `x` of type `A` that satisfy `p` ?

For a small example: 

```
type test_A
type test_B

assume val pred_A : test_A -> Tot bool
assume val pred_B : test_B -> Tot bool

assume val lemma_1 : unit -> Lemma (exists x. pred_A x)
assume val lemma_2 : x:test_A -> Lemma (exists y. pred_B y)

val lemma_3 : unit -> Lemma (exists y.pred_B y)
let lemma_3 () =
  lemma_1 ();
  let x = FStar.???????? (lemma_1 ()) in    // x would be a ghost value
  lemma_2 x
```

I put lot of `??????` because I don't really what to write. I checked into the library FStar.Ghost and Star.ErasedLogic but I did not manage to understand if I'm in the right direction or not. The only way I found so far to make it work is to work around the problem by changing `lemma_2` into a `forall` statement (or by using qintro)

```
type test_A
type test_B

assume val pred_A : test_A -> Tot bool
assume val pred_B : test_B -> Tot bool

assume val lemma_1 : unit -> Lemma (forall (x:test_A). (exists y. pred_B y))
assume val lemma_2 : unit -> Lemma (exists x. pred_A x)

val lemma_3 : unit -> Lemma (exists y.pred_B y)
let lemma_3 () =
  lemma_2 ();
  lemma_1 ()
```

Any suggestion ?

Thanks a lot
Vincent

**Comment by catalin-hritcu** [comment]
Can't do this now, but it could be something to try on the universes branch.

**Comment by msprotz** [comment]
Isn't it the purpose of the Squash module?

**Comment by catalin-hritcu** [comment]
One can try, but `Squash.get_proof` is inconsistent in an impredicative world.

**Comment by VincentCheval** [comment]
Thanks for the quick answer 😊

Since I opened a topic on lemmas, would you also know why I can't write:

```
assume val lemma_1 : Lemma (forall (x:test_A). (exists y. pred_B y))
```

It seems that the syntactic sugar for Lemma requires it to be a function. That's why I wrote earlier:
```
assume val lemma_1 : unit -> Lemma (forall (x:test_A). (exists y. pred_B y))
```

That would be fine with me but if I want to add an SMTPat for this lemma, I get a warning saying that `(Warning): Pattern misses at least one bound variables: unit`. For instance, if we take

```
type test_A

assume val constant_A : test_A
assume val pred_A : test_A -> Tot bool
```

then `assume val lemma_0 : Lemma (pred_A constant_A) [SMTPat (pred_A constant_A)]`  and 
`assume val lemma_0 : Lemma (requires True) (ensures (pred_A constant_A)) [SMTPat (pred_A constant_A)]` returns me an error message of the form `Expected type "bool"; got type "(list U6236)"`. 
If I remove the syntactic sugar of Lemma, such as `assume val lemma_0 : u:unit{ pred_A constant_A }[SMTPat (pred_A constant_A)]`, I get a syntax error (I'm guessing the `[SMTPat ...]` is also a syntactic sugar for something that I don't know ^^). If I write `assume val lemma_0 : unit -> Lemma (requires True) (ensures (pred_A constant_A)) [SMTPat (pred_A constant_A)]`, it works but I get the warning : `Test.fst(14,21-14,109) (Warning): Pattern misses at least one bound variables: unit`.

Thanks 😊

Vincent

**Comment by kyoDralliam** [comment]
The problem of `Lemma` vs `unit -> Lemma` is due to the fact that Lemma is a computational type which makes sense  only on the rhs of an arrow. Toplevel effect declarations are currently worked out but I don't think that's what you need anyway. 

I cannot reproduce the warning anymore, guess it has been fixed since then.

The problem you are having with `Expected type "bool"; got type "(list U6236)"` is due to the fact that  Lemma comes in 3 flavors : 
- `Lemma p` ensures the proposition `p`
- `Lemma pre post` ensures `post` under the precondition `pre`
- `Lemma pre post smtpat` adds a list of smt pattern wrt the previous form

The form that you want is the third one. The warning just tells you that since the unnamed variable of type unit is not in the pattern, it won't be able to instantiate this bound variable with the pattern. This should not be a problem since the SMT is able to prove that unit is uniquely inhabited by ().
