### ISSUE TITLE
Two issues about fancy ANSI codes in terminal output

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#474]
① I see this

```
\x1b[0;1mAll verification conditions discharged successfully\x1b[0m
```

in my terminal (Ocaml extraction). Extraction issue?

② Expose a new isatty function that returns `None` (F# backend) and `Some (Unix.isatty ())` (OCaml backend). Print ANSI codes iff `isatty() = Some true`.

**Comment by catalin-hritcu** [comment]
This used to work well on Linux. Are you on windows? In cygwin or cmd?

**Comment by msprotz** [comment]
Windows / cygwin terminal

**Comment by mlr-msft** [comment]
I just pushed a commit implementing @msprotz's suggestion (0d7e2f6698551ebd4d8655a25b028d40d090b88c) based on a conversation we were having yesterday  with @beurdouche. I didn't realize there was a conversation about it here too-- sorry about that.

Basically, the ANSI output breaks NuBuild integration and I needed to unblock myself.

**Comment by beurdouche** [comment]
@mlr-msft, thanks a lot for writing the patch. It seems to work properly on both the F# and OCaml version for OSX, so I just pushed your change in the OCaml snapshot.

**Comment by mlr-msft** [comment]
Glad i could help. :)

**Comment by beurdouche** [comment]
I just understood why it wasn't working for some people and was for others.
If you clean your repo from everything `git clean -xffd` and built F* using
`make -C src` -> Does not show ASCi codes properly
`make -C src/ocaml-output` -> Does not show ASCi codes properly

Only if in-between you made `make ocaml -C src` the codes will show up properly.
I think this is because we tend to commit the generated snapshot without cleaning our repos properly
I'll update the snapshot and you can confirm wether it is working again

**Comment by beurdouche** [comment]
Seems to work from a clean repo now `make -C src/ocaml-output` prints ASCI codes ;)

**Comment by beurdouche** [comment]
@mlr-msft improved a bit (https://github.com/FStarLang/FStar/commit/3789fea0b91345dc4f372965f32614f2e57ead71) upon your patch. Theoretically it should not break anything...

**Comment by beurdouche** [comment]
I will not add any colours anymore (I don't want F* to feel like a christmas tree ^^)
That said, if you think errors and warnings should be coloured in red and cyan respectively
you can simply use the new functions `Util.colorize_red`, `Util.colorize_cyan` (`Util.colorize_bold`) to which you simply pass any string. ;)
