### ISSUE TITLE
Tuple types in records are wrongly inferred as terms instead of type when the identifier is not in scope

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/FStar#499]
```
module Funny

type rt = {
  b: (a * a);
}
```

As type `a` is not in scope, this should fail with : `Identifier not found: [a]`

Instead it fails with : `The operator "*" is resolved here as multiplication since "a" is a term, although a type was expected`

It's an error message issue but I think F\* could recognise that `(a * a)` is a type.

**Comment by beurdouche** [comment]
Note that this is not happening with `--universes`

**Comment by msprotz** [comment]
Nik and I had a discussion about it, and this is fixed in `--universes` as follows:
- * is always resolved as the tuple operator
- if you want to use the multiplication, use × (the unicode multiplication character)

This is pending a lexer switch for the ocaml part, because ocamllex has no utf8 support and we probably want to switch to sedlex (no ulex because camlp4 is going away). @beurdouche if you want to take a stab at it, I think that'd be helpful! ☺

**Comment by mlr-msft** [comment]
Will there be a means to specify multiplication without requiring unicode characters?

**Comment by msprotz** [comment]
I think the problem only happens in types IIRC, and you can always get multiplication by using a fully qualified name.

**Comment by aseemr** [comment]
@msprotz, can we close this issue? I guess now `*` is by default the tuple type, for multiplication, one should open `FStar.Mul` in context?

**Comment by mtzguido** [comment]
I agree with Aseem, this is fixed.
