### ISSUE TITLE
Problem with simple arithmetic.

### ISSUE THREAD

**Issue by gsvgit** [FStarLang/FStar#500]
I use https://www.fstar-lang.org/tutorial/

The next code works fine.
```
module M 

type t = d: int {exists (w:int).(w + 1 = d )}

val f : t -> Tot t
let f x = x

val g: (int) -> Tot t
let g x = f 4
```

But if I replace '+' with '-' in type refinement, then I get an error.
```
module M 

type t = d: int {exists (w:int).(w - 1 = d )}

val f : t -> Tot t
let f x = x

val g: (int) -> Tot t
let g x = f 4
```

Error:
```
M(9,12-9,13): Subtyping check failed; expected type t; got type int
Error: 1 errors were reported (see above)
```

Such behavior is a bit strange for me.

**Comment by jkzinzindohoue** [comment]
The issue is related to the way the proposition under the quantifier is instantiated: the solver needs a trigger to instantiate it.
Here, because no trigger has been provided in the code, the behavior is a bit unpredictable. In practice it seems that the trigger is something like `w-1`:
```
module M

type t = d: int {exists (w:int). (w - 1 = d )}

val f : t -> Tot t
let f x = x

val g: int -> Tot t
let g x = 
    assert((4+1)-1 = 4);
    f 4
```
works. Now in your specific example it is not obvious what the appropriate trigger should be. 
It could be inserted in the type definition like `type t = d: int {exists (w:int). {:pattern (trigger(w))} (w - 1 = d )}`. Hope this helps.

**Comment by gsvgit** [comment]
Thanks.
