### ISSUE TITLE
Spurious dependencies for `.fsti` files 

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#532]
If both `A.fst` and `A.fsti` are present, then F\* identifies `A.fst` as a dependency of `A.fsti` while it shouldn't.

Transitively, if `A` is a dependency of `B.fsti`, then F\* identifies `A.fst` and `A.fsti` as dependencies, when it should pick only `A.fsti`.

**Comment by msprotz** [comment]
For the second point: I don't think it matters if both `A.fsti` and `A.fst` are identified as dependencies of `B.fst`; because, if you want to verify `B.fst`, then `fstar` will drop the environment after lax-checking `A.fst` and use only the contents of `A.fsti`; the only caveat is that `A.fst` may be an invalid file, but in that case it should probably be renamed `A.fst.draft`

**Comment by msprotz** [comment]
For the first point, I agree that you may want to run `fstar A.fsti` without picking up `fstar A.fst`; this should be fixed.

**Comment by nikswamy** [comment]
Is it still open?

**Comment by nikswamy** [comment]
@protz

**Comment by msprotz** [comment]
Fixed that during my last visit to Cambridge. Thanks.
