### ISSUE TITLE
robot2.fst has bitrotted

### ISSUE THREAD

**Issue by infidel** [FStarLang/FStar#537]
When I try to verify Exercise 11a (question or answer) online, I get:

```
/var/fstar/lib/FStar.HyperHeap.fsti(21,0-22,4) (Warning): Adding an implicit 'new' qualifier on rid
/var/fstar/lib/FStar.HyperHeap.fsti(25,0-26,3) (Warning): Adding an implicit 'new' qualifier on rref
Robot(69,10-69,20) : Error
Identifier not found: [new_region]
```

From the command line after compiling F\* I get a different error:

```
$ fstar.exe doc/tutorial/code/exercises/robot2.fst
Warning: the module declaration "module Robot" found in file doc/tutorial/code/exercises/robot2.fst does not match its filename. Dependencies will be incorrect.
/home/luked/fstar/FStar/lib/FStar.Util.fsti(37,4-37,4) : Error
Syntax error: Parsing.Parse_error
```

If I delete lib/FStar.Util.fsti then I get the same error as the online tutorial. Do you have any suggestions on how I might fix it myself? For example, which one is wrong: fst or fsti, or both, or neither?

I noticed that FStar.Util.fst is commented out in lib/Makefile due to bug #359 that was since fixed, but this doesn't seem to be related to my problem.

**Comment by catalin-hritcu** [comment]
@infidel Thanks a lot for reporting, and sorry, but this seems a bit of a mess.

From the command line you get automatic dependency tracking but that seems to get confused because `FStar.Util.fsti` is given the `fsti` extension although as far as I can tell it's not at all a valid `fsti` file.

If you pass dependencies manually from the command line (and thus use `FStar.Util.fst`) you can get the same error as on the fstar-lang.org server.
```
[hritcu@detained exercises]$ fstar.exe --explicit_deps FStar.FunctionalExtensionality.fst FStar.Set.fst FStar.Heap.fst FStar.Map.fst FStar.List.Tot.fst FStar.HyperHeap.fst FStar.Util.fst FStar.ST.fst robot2.fst
/home/hritcu/Projects/fstar/pub/lib/FStar.HyperHeap.fst(190,4-190,22): Warning: Admitting lemma_include_cons without a definition
/home/hritcu/Projects/fstar/pub/doc/tutorial/code/exercises/robot2.fst(69,10-69,20) : Error
Identifier not found: [new_region] 
```
By using `stHyperHeap.fst` instead of `FStar.ST.fst` I can get a bit further and get a typing error (instead of a name resolution error):
```
[hritcu@detained exercises]$ fstar.exe --explicit_deps FStar.FunctionalExtensionality.fst FStar.Set.fst FStar.Heap.fst FStar.Map.fst FStar.List.Tot.fst FStar.HyperHeap.fst FStar.Util.fst stHyperHeap.fst  robot2.fst 
/home/hritcu/Projects/fstar/pub/lib/FStar.HyperHeap.fst(190,4-190,22): Warning: Admitting lemma_include_cons without a definition
/home/hritcu/Projects/fstar/pub/doc/tutorial/code/exercises/robot2.fst(32,4-32,31) : Error
Unresolved implicit argument
```
Still the code in `robot2.fst` was not part of any Makefile, so it seems bit rotten. @nikswamy should be able to revive it though.

**Comment by catalin-hritcu** [comment]
> From the command line you get automatic dependency tracking but that seems to get confused because `FStar.Util.fsti` is given the `fsti` extension although as far as I can tell it's not at all a valid `fsti` file.

Digging a bit deeper into this part, `FStar.Util.fsti` is **almost** a valid `fsti`, and there is a special flag to make F\* parse this stuff. It's called `--fs_typ_app` and normally it's used only when bootstrapping F\* itself, just that keeping these almost valid, automatically generated files around seems silly, since automatic dependency checking will use them and then F\* will choke on them. Anyway, using `--fs_typ_app` and automatic dependency tracking is one more way to get to the `Identifier not found: [new_region]` problem:
```
[hritcu@detained exercises]$ fstar.exe --fs_typ_app robot2.fst
/home/hritcu/Projects/fstar/pub/lib/FStar.HyperHeap.fsti(18,15-21,8) (Warning): Adding an implicit 'new' qualifier on rid
/home/hritcu/Projects/fstar/pub/lib/FStar.HyperHeap.fsti(23,14-25,31) (Warning): Adding an implicit 'new' qualifier on rref
Warning: the module declaration "module Robot" found in file robot2.fst does not match its filename. Dependencies will be incorrect.
Warning: no modules in namespace FStar.Mul and no file with that name either
Warning: no modules in namespace FStar.Mul and no file with that name either
Warning: no modules in namespace FStar.Mul and no file with that name either
Warning: no modules in namespace FStar.Mul and no file with that name either
/home/hritcu/Projects/fstar/pub/doc/tutorial/code/exercises/robot2.fst(69,10-69,20) : Error
Identifier not found: [new_region]
```

**Comment by catalin-hritcu** [comment]
> Digging a bit deeper into this part, FStar.Util.fsti is almost a valid fsti, and there is a special flag to make F* parse this stuff.

Actually, I'm even a bit unsure about this stuff, since I tried adding `fstar.exe --fs_typ_app FStar.Util.fst` to `lib/Makefile` to prevent bitrot but that causes two `Patterns are incomplete` errors:
```
[hritcu@detained lib]$ /home/hritcu/Projects/fstar/pub/bin/fstar.exe  --fs_typ_app FStar.Util.fst
/home/hritcu/Projects/fstar/pub/lib/FStar.HyperHeap.fsti(18,15-21,8) (Warning): Adding an implicit 'new' qualifier on rid
/home/hritcu/Projects/fstar/pub/lib/FStar.HyperHeap.fsti(23,14-25,31) (Warning): Adding an implicit 'new' qualifier on rref
/home/hritcu/Projects/fstar/pub/lib/FStar.Util.fsti(23,10-23,13): Patterns are incomplete
/home/hritcu/Projects/fstar/pub/lib/FStar.Util.fsti(24,10-24,17): Patterns are incomplete
Warning: no modules in namespace FStar.Mul and no file with that name either
Warning: no modules in namespace FStar.Mul and no file with that name either
Warning: no modules in namespace FStar.Mul and no file with that name either
Warning: no modules in namespace FStar.Mul and no file with that name either
Error: 2 errors were reported (see above)
```
Looking at `FStar.Util.fsti` it still has exceptions declared in ML syntax, which AFAIK is not valid F\*:
```
exception Impos
exception NYI of string
exception Failure of string
```
No clue why/how `fstar.exe --fs_typ_app robot2.fst` managed to get that far without choking on this, the invocation is exactly the same, but there might be some special casing for checking files against their own interface? Anyway, seems a bit of a mess.

**Comment by msprotz** [comment]
For the record, you can debug what happens with auto-deps with `--debug Low`, IIRC.

**Comment by nikswamy** [comment]
This has nothing to do with --fs_typ_app. That's only for enabling `t<s>` and it's only used for boostrapping from the shared subset of F* and F\#. We shouldn't really use it anywhere else. I would even vote for removing that option from the --help message and reserving it for internal use for bootstrapping only.

The 'of' syntax for data constructors is valid syntax by default in F*. We just don't use it very much.

**Comment by beurdouche** [comment]
Strange, looking at that in `--universes` I have this:

```
fstar --universes --explicit_deps FStar.FunctionalExtensionality.fst FStar.Set.fst FStar.Heap.fst FStar.Map.fst FStar.List.Tot.fst FStar.HyperHeap.fst FStar.Util.fst hyperheap/FStar.ST.fst robot2.fst 
/opt/fstar/doc/tutorial/code/solutions/robot2.fst(193,0-193,48) (Warning): The 'opaque' qualifier is deprecated; use 'unfoldable', which is also the default
/opt/fstar/doc/tutorial/code/solutions/robot2.fst(208,5-208,11): failed to prove a pre-condition
Error: 1 errors were reported (see above)
`

**Comment by aseemr** [comment]
Closing this issue, since the robots example is part of the F* CI and kept up-to-date now.
