### ISSUE TITLE
Inference fails on an unannotated let rec

### ISSUE THREAD

**Issue by mtzguido** [FStarLang/FStar#554]
The following code

```
let index f l =
  let rec index i f l =
    match l with
    | [] ->
        0
    | hd :: tl ->
        if f hd then
          i
        else
          index (i + 1) f tl
  in
  index 0 f l
```

Fails to verify with: `Subtyping check failed; expected type (_:(?14386 (Prims.op_Addition i 1)) -> Prims.bool); got type (_:(?14386 i) -> Prims.bool)`. Seems like an incorrect dependency on `i` being forced. With `--lax`, it goes through.

This also goes through in the stratified branch (it is part of [u]lib/FStar.List.fst).

Moving the `i` argument to be last also fixes it.

**Comment by jkzinzindohoue** [comment]
I think it is just a matter of extra annotations being required by the typechecker.
With those it works:
```F#
let rec length: #a:Type -> l:list a -> Tot nat = fun #a l -> match l with | [] -> 0 | hd::tl -> 1+length tl

let index (f:'a -> Tot bool) (l:list 'a) =
  let rec index (i:nat) (f:'a -> Tot bool) (l:list 'a) : Tot nat (decreases (length l)) =
    match l with
    | [] ->
        0
    | hd :: tl ->
        if f hd then
          i
        else
          index (i + 1) f tl
  in
  index 0 f l
```

**Comment by mtzguido** [comment]
Yes, but note the original code is not Tot, but in ALL, so there's no termination check. The `0` in the `[]` case was actually a `failwith`, but I removed it to show that it's not related to that.

 I should have made that clear, this is not (necessarily) related to termination.

**Comment by jkzinzindohoue** [comment]
You can remove the effects though.
```
let rec length: #a:Type -> l:list a -> Tot nat = fun #a l -> match l with | [] -> 0 | hd::tl -> 1+length tl

let index (f:'a -> bool) (l:list 'a) =
  let rec index (i:nat) (f:'a -> bool) (l:list 'a) : ML nat =
    match l with
    | [] ->
        0
    | hd :: tl ->
        if f hd then
          i
        else
          index (i + 1) f tl
  in
  index 0 f l
```
I think that the subtyping algorithm is just not smart enough, extra annotations fix it.

**Comment by jkzinzindohoue** [comment]
As far as I have experienced, annotating non-top-level `let rec` is usually required for the code to typecheck, modulo trivial cases.

**Comment by nikswamy** [comment]
The algorithm indeed isn't smart enough to resort to breaking the dependence on `i` when the proof of `i = i + 1` fails. Notice, that the reason this succeeds in --lax mode is that there the proof of `i = i + 1` is just admitted.

As for this succeeding in --stratified: that's ancient. Can't really explain that, and not really worth explaining that behavior, IMO.

I'm marking this an enhancement and leaving it open. Although maybe it should be closed?

**Comment by nikswamy** [comment]
Actually, maybe a relatively small tweak of the unification/subtyping algorithm can support this. 

Currently, when comparing `(t a =?= t b)` we check that `a=b`. In case the head symbol of either `a` or `b` is marked "Delta_equational", then this check of `a=b` is dispatched to the SMT solver. This works well most of the time, except, as this example demonstrates, in the case where `t` is a meta-variable `?x`. In that case, requiring to prove `a=b` is needlessly restrictive, since even if `a<>b` the equation may be solvable, e.g., by picking `?x = fun _ -> c`. 

I'm thinking of tweaking the unification algorithm so that it does not dispatch `a=b` to SMT in case the `t` is a meta-variable, and instead resorting to what would normally happen to solve the equation with projections and imitations. 

That will probably handle this example well. But, will require some investigation of our existing code base to understand if it really is an improvement.

**Comment by aseemr** [comment]
@mtzguido, the original example fails now because by default F* checks for `Tot` effect, and fails to prove that the inner `index` terminates. Once I add a decreases clause:

```
let rec index i f l :Tot nat (decreases l) =
```

The code goes through. This looks reasonable to me. Closing it, please reopen if required.
