### ISSUE TITLE
An example illustrating the need for variance and structural subtyping on inductives (+ a related possible bug that needs to be factored into a separate issue)

### ISSUE THREAD

**Issue by MallabaevAzamat** [FStarLang/FStar#590]
Why failed assumption:

```
module Test
open FStar.List.Tot
assume Flatten: forall (a:Type) (ss:list (s:list a {is_Cons s}) {is_Cons ss}) .
    is_Cons (flatten ss)
```

when didn't fail assumption:

```
module Test
open FStar.List.Tot
assume Flatten: forall (a:Type) (ss:list (s:list a)) .
    for_all is_Cons ss /\ is_Cons ss ==> is_Cons (flatten ss)
```

**Comment by catalin-hritcu** [comment]
I think this fails because F\* is too stupid to figure out that the inner type of ss is also a list, because the inner refinement gets in the way:
```
/examples/bug-reports/bug590.fst(6,21-6,23): Subtyping check failed; expected type (Prims.list (Prims.list a)); got type (ss#19:(Prims.list (s#22:(Prims.list a){(Prims.b2t (Prims.is_Cons s@0))})){(Prims.b2t (Prims.is_Cons ss@0))})
```
If this is indeed the problem then the real fix requires implementing polarities and structural subtyping for inductives (https://github.com/FStarLang/FStar/issues/65#issuecomment-65823677). Wouldn't hold my breath on that one though, so in the meanwhile here are some workaround:
- Just turn the `s:list a {is_Cons s}` into list a, if possible
- If not write an explicit coercion:
```
let rec coerce (#a:Type) (ss:list (s:(list a){is_Cons s}))
  : Pure (list (list a)) (requires True)
                         (ensures (fun ss' -> ss === ss')) = admit()
  (* match ss with *)
  (* | [] -> [] *)
  (* | h::t -> h :: (coerce t) *)

let flatten_lemma (a:Type) (ss:list (s:list a {is_Cons s}) {is_Cons ss}) :
  Lemma (requires True) (ensures (is_Cons (flatten (coerce ss)))) = ()
```
For some reason F\* cannot type `coerce` now:
```
./examples/bug-reports/bug590.fst(6,4-10,27): could not prove post-condition
./examples/bug-reports/bug590.fst(6,4-10,27): could not prove post-condition
```

**Comment by catalin-hritcu** [comment]
> Wouldn't hold my breath on that one though

Although it seems that @aseemr-msr  might be up to something: https://github.com/FStarLang/FStar/issues/319#issuecomment-229926382

**Comment by catalin-hritcu** [comment]
> For some reason F* cannot type coerce now:

It seems that F* has troubles proving that two `Nil`s of different types are `===`. It does prove that the conses are equal though, so something is fishy here.

**Comment by catalin-hritcu** [comment]
@beurdouche  I don't think @nikswamy will agree calling the original problem a bug, since it seems just a missing feature we already know about https://github.com/FStarLang/FStar/issues/65#issuecomment-65823677. As for my workaround failing, we should first figure out what's going on and once we do that maybe file a separate issue for that. Finally, I thought of `needinput` a label for issues where we're waiting for information (say precise reproduction steps) from the original poster ... which is not the case here. I can already very well reproduce this.

**Comment by beurdouche** [comment]
@catalin-hritcu @nikswamy: I labelled it a bug because it is in a file named bug590 ... Be my guest in changing it to "question" or something else. Also if you can add a label when opening the issue it will prevent me from mislabelling it ;)

**Comment by catalin-hritcu** [comment]
Did a few more experiments on this with Kenji and we think there is no bug here. The type I was trying to give to `coerce` is wrong because the type indices of `Nil` and `Cons` do affect equality. In particular, it's expected that `Nil #(list a)` is different from `Nil #(s:(list a){Cons? s})` in the current system.

Now the reason the `Cons` case of `coercion` was succeeding is maybe a bit surprising, but still correct. Because of the recursive call to `coerce t` F* can prove that `coerce t === t` from which it can show `eq2 (list (list a)) (list (s:(list a){Cons? s}))`, which is enough to type-check the rest of the term. In fact, `eq2 (list (list a)) (list (s:(list a){Cons? s}))` makes the environment inconsistent, just that F* needs a tiny bit of help to prove it.
