### ISSUE TITLE
Got compiler exception in Tutorial: "map2: Different_list_size"

### ISSUE THREAD

**Issue by smondet** [FStarLang/FStar#639]
The tutorial asked me to report an issue: https://www.fstar-lang.org/tutorial/

Input:

```ocaml
exception Bouh
val f: int -> Exn int
let f x =
    if x > 0
    then 2 + x
    else raise Bouh
    
```

Output:

```
Welcome(21,18-21,21): Expected type "Effect";
got type "(pre:Prims.ex_pre -> post:(Prims.ex_post Prims.int) -> Tot Effect)"
Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Invalid_argument("map2: Different_list_size")
Error: 1 errors were reported (see above)
```

**Comment by ad-l** [comment]
I suspect I may have caused this. Investigating now.

**Comment by ad-l** [comment]
Upon investigating, the problem is that the `Exn` effect expects a pre and post-condition as argument; the error message you get is particularly unhelpful. `Ex` is the exception effect with trivial pre and post condition, the following code does what you expect:

```ocaml
exception Bouh
val f: int -> Ex int
let f x =
    if x > 0
    then 2 + x
    else raise Bouh
```

I'll see if I can improve the error message for insufficient effect arguments.

**Comment by s-zanella** [comment]
This keeps confusing users. Simpler example:

```F#
module M

val f: unit -> ST unit
let f x = ()
```

**Comment by nikswamy** [comment]
Sorry, this is a crash. Will fix asap
