### ISSUE TITLE
The parser is different between the F# and OCaml versions

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#672]
In particular:
- the ocamlyacc-generate parser has six shift/reduce conflicts, while for the same grammar fsyacc claims there are seven
- the F# build cannot parse Squash.fsti while the OCaml build can.

**Comment by nikswamy** [comment]
Does anyone understand why this fails to parse in the F# version of F* but works just fine in the OCaml version?

```val f : (a:Type0 & a) -> Tot unit
```

the dependent pair is to blame for some reason that I cannot fathom

**Comment by catalin-hritcu** [comment]
@nikswamy That's the same problem as for #404 and has the same workaround (I just tried). So could it be that this problem is related to #252 and #404?

**Comment by kyoDralliam** [comment]
Another discrepancy (introduced by the (future) change to the menhir parser) is that the F# version of F* does not parse brackets type application (e.g. list<int>) in the first term/type of the file. This prevent bootstrapping the Ocaml F* from the F# one. There is a hack which allow to do the bootstrap if necessary : add an unused definition at the beginning of the module (or reorder the module so that the first definition does not contain any bracket).

**Comment by catalin-hritcu** [comment]
from https://github.com/FStarLang/FStar/issues/746#issuecomment-263400624
> The additional shift-reduce conflict is a known bug in fsyacc (fsprojects/FsLexYacc#39) due to a bad handling of non-associative-ness.

**Comment by nikswamy** [comment]
We no longer have an F# parser.
