### ISSUE TITLE
Failure("Impossible: Violation of locally nameless convention: v@3")

### ISSUE THREAD

**Issue by rpollack0** [FStarLang/FStar#677]
I'm a total Fstar newbie.  I got this error using fstar_0.9.3.0-beta1_Linux_x86_64.tar.gz 

Error: Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: Violation of locally nameless convention: v@3")

I'm attaching the source file.  (Note that I had to add a .txt extension to the filename for GitHub to accept the upload.  Remove the .txt extension to trigger the error.)

[bug.fst.txt](https://github.com/FStarLang/FStar/files/466280/bug.fst.txt)

--Randy Pollack

**Comment by catalin-hritcu** [comment]
@rpollack0 Hi Randy, thank you very much for the report. When it blows up like this it's definitely a bug, so we will  look at it.

It's great to see you trying F*. Let us know if you have any questions or other trouble.

**Comment by nikswamy** [comment]
Thanks for the bug report, Randy. 

Marking the crash a Priority 1. For the record, I've minimized it to:

```
module Bug677
assume type pp
assume type exp
assume val eSize: exp -> Tot nat
assume val avclosed: e:exp -> p:pp -> Tot bool (decreases (eSize e))
val aVclosed_alpha:  e:exp -> p:pp -> Lemma (avclosed e = avclosed e)
```

It seems like the problem is related to the partial application of `avclosed` on the last line and some unexpected interaction with the decreases clause. 

In case you need a workaround, you might instead write something like what's below  (though not sure if that was what you really intended):

```
val aVclosed_alpha: 
  e:exp -> p:pp -> v:vv -> q:pp ->
     GTot (u:unit {avclosed (vsbstp v p e) p = avclosed (vsbstp v q e) q})
```

**Comment by nikswamy** [comment]
ended up being a really easy fix. sorry to let this sit for as long as it has.
