### ISSUE TITLE
better inline support

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#717]
Proposed shuffling of qualifier names (by @nikswamy)

In various places, esp. in Kremlin, we need some definitions to be
inlined only during extraction, not during type-checking. F\* does not
yet support such a feature: the 'inline' qualifier inlines a
definition during unification and VC generation, which is too early
for this use case.

So, I propose:
1. Remove the current 'unfoldable' keyword. It is the default
   qualifier anyway and never needs to be explicitly denoted in the
   source program. Let's refer to it during discussions as 'visible'.
2. Rename the current 'inline' keyword to 'unfold', preserving its
   meaning, i.e., the type-checker will aggressively unfold the
   definition during unification and VC generation.
3. Use 'inline' to signify that a definition must be inlined during
   compilation only. For unification/VC generation purposes, the 'inline'
   qualifier has no significance.

Note, ﻿⁠⁠⁠⁠inline﻿⁠⁠⁠⁠ is compatible with the other visibility qualifiers. So,
you can write

```
     ﻿⁠⁠⁠⁠inline irreducible let f x = 0﻿⁠⁠⁠⁠
or       ﻿⁠⁠⁠⁠inline abstract let f x = 0﻿⁠⁠⁠⁠
or       ﻿⁠⁠⁠⁠inline unfold let f x = 0﻿⁠⁠⁠⁠
```

which means that for type-checking purposes, f's definition is
irreducible/abstract/unfold, but during compilation, the definition
will be definitely be inlined. (edited)

**Comment by nikswamy** [comment]
Following our discussion: 

I will implement this gradually. 

First, the 'inline' keyword will temporarily be made illegal. You will have to change all uses of 'inline' in your code to 'unfold'

Second, I will add a new temporary keyword 'inline_for_extraction' which you can start using to control inlining in compiled code.

Finally, in about a week, I will add support for the 'inline' keyword, replacing 'inline_for_extraction'

This convoluted path is to prevent existing code from breaking mysteriously due to renaming inline to unfold. It will instead break immediately and obviously.

**Comment by nikswamy** [comment]
I think the ship has sailed on this one. We have `inline_for_extraction`  and `unfold` and we use it extensively. It is verbose but explicit and arguably better than ``inline`. Closing this issue.
