### ISSUE TITLE
bad error message when typo in the name of a module

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#718]
see Cédric's message on slack

**Comment by sishtiaq** [comment]
`Error: let-open only supported for modules, not namespaces` gives no context. (name, file, line,...). This error seems to trigger whenever that is a typo in the opened module name.

**Comment by wintersteiger** [comment]
I just got this error because a `--include` was missing (actually via kremlin, because of missing a `-I`). Very annoying, but I got there in the end, by probing single files to see which one throws the error and then by going through the file to see which modules it refers to. I was lucky and the file was small, so I found the problem quickly.

**Comment by aseemr** [comment]
When I try `open Foo`, where `Foo` is not the path, I get an error saying "Namespace Foo cannot be found, No modules in namespace Foo and no files with that name either", which seems reasonable.

Also since we lost history on slack, hard to find out the original bug report : ). Closing, please reopen/file a new issue if required.
