### ISSUE TITLE
What is the meaning of "requires True" in lemmata? 

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#741]
F* code seems to often include `requires True` in a lemma - what is this for? This clause appears several times even in the tutorial, without an explanation.

**Comment by jkzinzindohoue** [comment]
On explanation could be that while F* supports some abbreviations for lemmas (e.g. `Lemma (ensures (P))` or `Lemma (P)` instead of `Lemma (requires (True)) (ensures (P))`, it does not work when you add extra clauses (typically a `decrease` clause or a `SMTPat` clause)
To use one of those you may need to add a trivial precondition.
