### ISSUE TITLE
Removing a refinement causes verification to fail

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#763]
In /examples/data_structures/BinarySearchTree.fst, we have the following function, representing the typical binary search tree insertion operation. 

```
val insert : x:int -> t:tree{is_bst t} ->
  Tot (r:tree{is_bst r /\ (forall y. in_tree y r <==> (in_tree y t \/ x = y))})
let rec insert x t =
  match t with
  | Leaf -> Node x Leaf Leaf
  | Node n t1 t2 -> if x = n then      t
                    else if x < n then Node n (insert x t1) t2
                    else               Node n t1 (insert x t2)
```

Removing the second condition from the return value causes the verification to fail.

`val insert : x:int -> t:tree{is_bst t} -> Tot (r:tree{is_bst r})`

The error message is `Subtyping check failed; expected type (r#18535:BinarySearchTree.tree{(Prims.b2t (BinarySearchTree.is_bst r@0))}); got type BinarySearchTree.tree`.

Why does this happen?

**Comment by catalin-hritcu** [comment]
It's because that's probably a crucial part of the invariant required to prove this recursive function correct. The specification of a _recursive_ function is akin to an the inductive hypothesis of a proof by induction, and as you probably know too well, the hardest part of interesting inductive proofs is finding a strong enough inductive hypothesis. So apparently removing that conjunct leaves you not only with less to prove, but also leaves you with a too weak inductive hypothesis to be able to prove what's left.
