### ISSUE TITLE
UInt32 type check mysteriously failed

### ISSUE THREAD

**Issue by izgzhen** [FStarLang/FStar#811]
Example:
```
module Test
open FStar.UInt32

val k: UInt32.t
let k = 0x99ul

val k2: UInt32.t
let k2 = 0x100ul
```

You will get:

```
 (Error) Subtyping check failed; expected type (uint_t n); got type int (see /var/fstar/ulib/FStar.UInt.fst(24,28-24,36))
Verified module: Test (4212 milliseconds)
1 error was reported (see above)
```

**Comment by izgzhen** [comment]
i.e. The `0x100ul` will fail to check while `0x99ul` or below is fine.

**Comment by jkzinzindohoue** [comment]
Hi,
This is a very annoying limitation that should be addressed quickly.
Part of the explanation is the following: bounds on machine integers are defined in terms of powers of 2. And powers of 2 are defined recursively. In some cased F* might be do the computation, in some others it might not (if it is too big).
One way to work around it is to add a lemma such as 
```F#
val pow2_values: x:nat -> Lemma
  (requires True)
  (ensures (let p = pow2 x in
   match x with
   | 0  -> p=1
   | 1  -> p=2
   | 8  -> p=256
   | 16 -> p=65536
   | 31 -> p=2147483648
   | 32 -> p=4294967296
   | 63 -> p=9223372036854775808
   | 64 -> p=18446744073709551616
   | _  -> True))
  [SMTPat (pow2 x)]
let pow2_values x =
   match x with
   | 0  -> assert_norm (pow2 0 == 1)
   | 1  -> assert_norm (pow2 1 == 2)
   | 8  -> assert_norm (pow2 8 == 256)
   | 16 -> assert_norm (pow2 16 == 65536)
   | 31 -> assert_norm (pow2 31 == 2147483648)
   | 32 -> assert_norm (pow2 32 == 4294967296)
   | 63 -> assert_norm (pow2 63 == 9223372036854775808)
   | 64 -> assert_norm (pow2 64 == 18446744073709551616)
   | _  -> ()
``` 
which is currently in `ulib/FStar.Int.fst`.
For some reason this lemma is not in `FStar.UInt.fst` (which would solve your problem). It may be because it would hinder verification, or it may be that we forgot.

While we discuss what can be done to solve it, note the `assert_norm` feature: if calls the F* normalizer which means that F* does not call Z3 here. This works for integer computations and is very useful in some cases. It can also be used for computation on list literals for instance.

**Comment by s-zanella** [comment]
To complement @jkzinzindohoue answer, you can use `assert_norm`in the definition of `k2` itself to convince F* that `0x100ul` fits in 32 bits :
```F#
val k2: UInt32.t
let k2 = 
  assert_norm (0x100 < pow2 32);
  0x100ul
```

**Comment by izgzhen** [comment]
Okay I see, thanks a lot :)

**Comment by mtzguido** [comment]
This now works. Machine integer literals are now checked specially by the desugarer, so they involve no SMT queries.
