### ISSUE TITLE
Better/proper support for IO effect

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#85]
The tutorial uses `IO` effect as an example, but `prims.fst` doesn't really define an IO effect. What exactly is the status of the `IO` effect ... and where do we want to go with that?

**Comment by nikswamy** [comment]
We have several directions that we have explored, ranging from DM4All, to monotonic logs in miTLS, to channel types in Steel.

If anyone is motivated to summarize I think this issue is better promoted to a design document wiki page. 

This particular open issue doesn't add much. I suggest closing it. 

@catalin-hritcu @mtzguido @aseemr
