### ISSUE TITLE
(Error) assertion failed (see ~/fstar/ulib/FStar.ST.fst(37,44-37,49))

### ISSUE THREAD

**Issue by olleharstedt** [FStarLang/FStar#853]
I get the error in title when running this code:

```F#
module Ex

open FStar.Heap
open FStar.ST

type state = 
  | Open
  | Closed

type file = {name: string; state: ref state}

type isClosed file heap = (sel heap file.state) == Closed
type isOpen file heap = (sel heap file.state) == Open

val openHelper : file:file -> ST unit
    (requires (isClosed file))
    (ensures (fun heap s heap' -> isOpen file heap'))
let openHelper file =
    file.state := Open

let file1 = {
    name = "file1";
    state = alloc Closed;
}

(** EDIT: computeBase should have access to file1 *)
let computeBase () =
    12

(** EDIT: Missing precondition - should only be able to read open files *)
let read file =
    13

val readFromFile : file:file -> ST unit
    (requires (isClosed file))
    (ensures (fun heap s heap' -> isClosed file heap'))
let readFromFile file =
    openHelper file;
    let x = computeBase () + read file in
    file.state := Closed

let nil =
    readFromFile file1
```

Sorry I couldn't make the example shorter. The error disappears if I place `file1` in local scope, but the point was exactly to experiment around variables and state in a wider scope, especially if function `computeBase` has a reference to `file1`.

My version of F*:

```
~/kod/fstar$ ./bin/fstar.exe --version
F* 0.9.4.0
platform=Linux_x86_64
compiler=OCaml 4.03.0
date=2017-02-02T11:54:08+01:00
commit=9fc07cf
```

Any more info I need to provide?

**Comment by kyoDralliam** [comment]
Before that error you should have got a warning saying that toplevel effects are not supported and that top-level let binding should be total (which is exactly what you seems to be trying to achieve). Just modifying slightly your last toplevel declaration makes it verify  
``` F#
let nil () =
    readFromFile file1
```

**Comment by olleharstedt** [comment]
That change will make F* ignore the Closed/Open pre-conditions - the status of `file1` does not longer matter for `readFromFile`.

**Comment by catalin-hritcu** [comment]
I find the behavior of F* here indeed counterintuitive.

First, what exactly is the restriction on top-level effects, and why does Olle's original example fail? The error message provides little explanation, and the example seems intuitively fine. What's probably happening is that F* forces the precondition of `nil` (and other `top-level effects`) to be trivial, but in this case it's not. For a start, the error message should make this clear.

Second, when thunking `nil` not only `readFromFile file1` works, but also `readFromFile file2` where `file2` did `state = alloc Open` instead of `state = alloc Closed`, which seems to be inconsistent. [Pollack inconsistent](https://pdfs.semanticscholar.org/0aba/4e4000988d8563c2e64b343f876efa77767b.pdf), since if one digs a bit deeper one realizes that what's actually happening here is that F* is computing and accepting a non-trivial precondition for `nil` that is nowhere seen in the program. Adding an annotation on `nil`:
`val nil : unit -> St unit`
makes the `(Error) assertion failed` return though, but that irrespective whether one uses `file1` or `file2`. The problem here is that not only are `top-level effects` required to have trivial preconditions, but also they are given trivial postconditions, so the fact that `file1/2` is open or close is completely forgotten. The solution here is to also thunk `file1`:
```
let file1 () = {
    name = "file1";
    state = alloc Closed;
}
```
which will make the last warning go away and F* keep the strong postcondition it computed for `file1` and use it when verifying `nil`:
```
val nil : unit -> St unit
let nil () =
    readFromFile (file1 ())
```
So this finally works! Hope it explains things a bit :)

PS: Another was to see the original trivial type of `file1` and the non-trivial precondition on `nil ()` without an annotation is  by using the `--log_types --print_effect_args` flags.
```
let file1 : file
...
let nil : (uu___:unit -> ST (unit) (isClosed file1), (fun heap s heap' -> (isClosed file1 heap'@0)) (attributes ))
```

**Comment by olleharstedt** [comment]
Hi @catalin-hritcu, thanks for your extensive answer!

Changing `file1` into a function destroys again part of the purpose of this test - that function `computeBase` has access to `file1` (meaning that we don't know if `file1` is closed or open after the call to `computeBase`).

**Comment by catalin-hritcu** [comment]
It seems that what you need for this example is this enhancement:
https://github.com/FStarLang/FStar/wiki/Top-level-effects
https://github.com/FStarLang/FStar/issues/143
While this was discussed about 1 year ago, I'm not aware on progress on that since then.

Until this better solution is implemented one thing you can try is move all your effectful top level definitions and all things that depend on them within your main() function. It ain't pretty, but it might work.

**Comment by olleharstedt** [comment]
I will try that, thank you.

**Comment by olleharstedt** [comment]
@catalin-hritcu What's the correct syntax to define both `val` and `let` within function scope?

**Comment by kyoDralliam** [comment]
You cannot define a `val` in function scope, these are declarations which only makes sense at toplevel (and  are not needed unless you are writing a signature file). if you want to be precise about your type you can always annotate the `let` directly, e.g.
```F#
let f (x:t1) (y:t2) : tresult = ...```

**Comment by olleharstedt** [comment]
@kyoDralliam Thanks!

**Comment by aseemr** [comment]
This is related to top-level effects for which we have discussed a design (https://github.com/FStarLang/FStar/wiki/Top-level-effects), but since this is not on the roadmap right now, closing it as wontfix.
