### ISSUE TITLE
Can't prove lemma over a list longer than length 7 

### ISSUE THREAD

**Issue by jldodds** [FStarLang/FStar#879]
In the following example, I am only able to get the lemma `x` at the bottom to prove if I comment out the 8 from the end of `lst`, making it length 7. Any longer and the proof fails.

```
module Problem_example 

let lst = [1;2;3;4;5;6;7;8]
		     
val next_state : list int -> int -> Tot (option int)
let rec next_state is i =
  match is with
  | [] -> None
  | h :: t -> if h = i then match t with
			   | h2 :: t2 -> Some h2
			   | _ -> None
		      else next_state t i

val x : (i : int) ->  (i':int) -> Lemma (requires (i <> 1 /\ 
			 next_state lst i == Some i'))
		     (ensures i' <> 2)
let x i i' = ()
```

**Comment by kyoDralliam** [comment]
In order to prove the lemma, the smt has to do computations with a recursive function `next_state`. In order to prevent arbitrary resource consumption, there is a parameter limiting the number of unfolding of recursive definitions that the SMT can do called the fuel. By default the maximum fuel is set to 8, you can set it higher with `--max_fuel 9` for example which makes the file verify.
