### ISSUE TITLE
Minimal example: hints that don't replay

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/FStar#900]
Here's a minimal example of recorded hints that don't replay.
This seem to happen a lot in larger examples (see e.g. #893).
```
$ cat M.fst
module M
let n = 1ul
```
```
$ bin/fstar.exe M.fst --hint_info --record_hints
(./M.fst(2,0-2,11))
	Query (M.n, 1)	succeeded in 674 milliseconds with fuel 2 and ifuel 1
Verified module: M (790 milliseconds)
All verification conditions discharged successfully
```
```
$ bin/fstar.exe M.fst --hint_info --use_hints
(/Users/anonymous/fstar/M.fst) digest is valid; using hints db.
(./M.fst(2,0-2,11))
	Query (M.n, 1)	failed (with hint) in 61 milliseconds with fuel 2 and ifuel 1
(./M.fst(2,0-2,11))
	Query (M.n, 1)	succeeded in 651 milliseconds with fuel 2 and ifuel 1
Hint-info (./M.fst(2,0-2,11)): Replay failed in 61 milliseconds
Verified module: M (881 milliseconds)
All verification conditions discharged successfully
```
```
$ cat M.fst.hints
[
  "69Qǎ\u0010Q????7?\u001d?",
  [
    [
      "M.n",
      1,
      2,
      1,
      [
        "@query", "b2t_def", "equation_FStar.UInt.fits",
        "equation_FStar.UInt.max_int", "equation_FStar.UInt.min_int",
        "equation_FStar.UInt.size", "equation_FStar.UInt32.n",
        "equation_Prims.nat", "function_token_typing_FStar.UInt32.n",
        "lemma_FStar.UInt.pow2_values", "primitive_Prims.op_AmpAmp",
        "primitive_Prims.op_LessThanOrEqual",
        "primitive_Prims.op_Subtraction",
        "projection_inverse_BoxBool_proj_0",
        "projection_inverse_BoxInt_proj_0",
        "refinement_interpretation_Tm_refine_ba523126f67e00e7cd55f0b92f16681d"
      ],
      0
    ]
  ]
]
```
```
$ z3 --version
Z3 version 4.5.0 - 64 bit
```
Looking at the Z3 queries using `--log_queries` I didn't notice anything odd. Looks like everything in the computed unsat core is in the query used to replay the hint. 

@wintersteiger Do you mind having a look to see if this is an issue with the F* encoding or internal to Z3?
[queries.zip](https://github.com/FStarLang/FStar/files/862306/queries.zip)

**Comment by wintersteiger** [comment]
Sweet! Thanks for the small example! I'm back from vacation and will take a look at this immediately.

**Comment by s-zanella** [comment]
Discussed this briefly with Christoph, who has been working on a long-term solution in the `cwinter_checked_hints` branch.

An easy work around that already works with F* master and the Z3 nightly build (https://github.com/Z3Prover/bin/tree/master/nightly) is to pass `--z3cliopt "smt.core.extend_patterns=true smt.core.extend_patterns.max_distance=1"` to F*, which will in turn pass these options to Z3 and will result in a larger unsat-core and a replayable hint.

**Comment by nikswamy** [comment]
I don't think this is a bug.

**Comment by wintersteiger** [comment]
"Performance bug" :-)

**Comment by nikswamy** [comment]
So, it seems that Z3 is not reported two important assertions in the unsat core.

If I add these two assertions back in manually:

```
;;;;;;;;;;;;;;;;Correspondence of recursive function to instrumented version
(assert (! (forall ((@x0 Term))
                   (! (= (Prims.pow2 @x0)
                         (Prims.pow2.fuel_instrumented MaxFuel
                                                       @x0))
                      

                      :pattern ((Prims.pow2 @x0))
                      :qid fuel_correspondence_Prims.pow2.fuel_instrumented))
           :named fuel_correspondence_Prims.pow2.fuel_instrumented))

;;;;;;;;;;;;;;;;Fuel irrelevance
(assert (! (forall ((@u0 Fuel) (@x1 Term))
                   (! (= (Prims.pow2.fuel_instrumented (SFuel @u0)
                                                       @x1)
                         (Prims.pow2.fuel_instrumented ZFuel
                                                       @x1))
                      

                      :pattern ((Prims.pow2.fuel_instrumented (SFuel @u0)
                                                              @x1))
                      :qid fuel_irrelevance_Prims.pow2.fuel_instrumented))
           :named fuel_irrelevance_Prims.pow2.fuel_instrumented))
```

then the proof is easily replayed.

**Comment by nikswamy** [comment]
Here's a rough sketch of what's going on:

We need to prove:

```
                         (Prims.op_LessThanOrEqual (BoxInt 0)
                                                   (FStar.UInt.max_int (BoxInt 32))
```

We have:

```
;;;;;;;;;;;;;;;;Equation for FStar.UInt.max_int
(assert (! (forall ((@x0 Term))
                   (! (= (FStar.UInt.max_int @x0)
                         (Prims.op_Subtraction (Prims.pow2 @x0)
                                               (BoxInt 1)))
                      

                      :pattern ((FStar.UInt.max_int @x0))
                      :qid equation_FStar.UInt.max_int))
           :named equation_FStar.UInt.max_int))
```

So, this crucially involves reasoning about `(Prims.pow2 (BoxInt 32))`

Which is provided by this lemma:

```
;;;;;;;;;;;;;;;;Lemma: FStar.UInt.pow2_values
(assert (! (forall ((@x0 Term))
                   (! (implies (HasType @x0
                                        Prims.nat)
                               (let ((@lb1 @x0)) (ite (= @lb1
                                                         (BoxInt 0))

                                                      ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(11,11-11,14); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                      (= (Prims.pow2 @x0)
                                                         (BoxInt 1))

                                                      (ite (= @lb1
                                                              (BoxInt 1))

                                                           ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(12,11-12,14); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                           (= (Prims.pow2 @x0)
                                                              (BoxInt 2))

                                                           (ite (= @lb1
                                                                   (BoxInt 8))

                                                                ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(13,11-13,16); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                (= (Prims.pow2 @x0)
                                                                   (BoxInt 256))

                                                                (ite (= @lb1
                                                                        (BoxInt 16))

                                                                     ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(14,11-14,18); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                     (= (Prims.pow2 @x0)
                                                                        (BoxInt 65536))

                                                                     (ite (= @lb1
                                                                             (BoxInt 31))

                                                                          ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(15,11-15,23); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                          (= (Prims.pow2 @x0)
                                                                             (BoxInt 2147483648))

                                                                          (ite (= @lb1
                                                                                  (BoxInt 32))

                                                                               ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(16,11-16,23); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                               (= (Prims.pow2 @x0)
                                                                                  (BoxInt 4294967296))

                                                                               (ite (= @lb1
                                                                                       (BoxInt 63))

                                                                                    ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(17,11-17,32); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                                    (= (Prims.pow2 @x0)
                                                                                       (BoxInt 9223372036854775808))

                                                                                    (ite (= @lb1
                                                                                            (BoxInt 64))

                                                                                         ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(18,11-18,33); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                                         (= (Prims.pow2 @x0)
                                                                                            (BoxInt 18446744073709551616))

                                                                                         (implies (= @lb1
                                                                                                     (BoxInt 128))

                                                                                                  ;; def=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(19,12-19,49); use=D:\workspace\everest\FStar\ulib\FStar.UInt.fst(22,4-22,15)
                                                                                                  (= (Prims.pow2 @x0)
                                                                                                     (BoxInt 340282366920938463463374607431768211456))
                                                                                                  )))))))))))
                      

                      :pattern ((Prims.pow2.fuel_instrumented ZFuel
                                                              @x0))
                      :qid lemma_FStar.UInt.pow2_values))
           :named lemma_FStar.UInt.pow2_values))
```

But notice that its pattern has a ```(Prims.pow2.fuel_instrumented ZFuel
                                                              @x0)```

Not `(Prims.pow2 @x0)`

So, the only way to complete this proof from here is to rely first on `fuel_correspondence_Prims.pow2.fuel_instrumented` and then on `fuel_irrelevance_Prims.pow2.fuel_instrumented`, which provides the term needed to trigger `lemma_FStar.UInt.pow2_values`.

Now, I can apply various ad hoc patches on the the F* side, e.g., always including the fuel_correspondence and fuel_irrelevance assertions when replaying a hint. Tweaking the encoding of the lemma so that the pattern uses `pow2` rather than  `pow2.fuel_instrumented`. But, that feels a bit random.

@wintersteiger : Do you have an explanation for why Z3 is not reporting those two crucial assertions in the unsat core?

**Comment by s-zanella** [comment]
I believe this is exactly the situation the option`smt.core.extend_patterns=true` attempts to address: extend the unsat core with terms that may trigger quantifier instances. This is often too brutal as even when setting `smt.core.extend_patterns.max_distance=1` you get a core that is substantially larger than the unsat core without this option.

**Comment by wintersteiger** [comment]
As @s-zanella says, this is one of those situations where the term/quantifier instance dependencies aren't tracked. Your analysis matches what I have so far; I can get the proof go through if I magically (recorded) know the right terms, otherwise it needs the additional quantifiers. I'm currently digging into the code base to see whether we can track at least simple dependencies efficiently.

**Comment by nikswamy** [comment]
To me, this is not the canonical situation of an assertion only contributing patterns and hence not included in the unsat core.

This seems to me a possible bug in z3 reporting an unsat core that's really not unsat. How can you prove unsat without the fuel irrelevance and fuel correspondence assertions?

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by wintersteiger** [comment]
Aah, I see what you mean! I have a (small) example set of quantifier instantiations that does result in unsat without those quantifiers; I'll go through them manually to check whether it actually is unsat or not.

**Comment by wintersteiger** [comment]
So, I think I need to clear up this misconception about unsat cores (again): An unsat core is a (non-minimal) subset of the original formula which is unsatisfiable. It's no more and no less than that and the definition is in no way, shape, or form related to Z3 and how it solves problems.

In this particular example, the core that Z3 returns is fully compliant with that specification; it's unsatisfiable (I've gone through it by hand). That's the only thing that Z3 claims; it does not make any claims about whether Z3 or other solvers will in the future be able to solve this or similar problems by using E-matching or any other technique. This is completely sound, correct, and "in spec". (In fact Z3 doesn't even guarantee that it will use the same or a similar solver on the smaller problem; for instance when the core is a ground bit-vector problem, it will eagerly bit-blast the smaller problem into the SAT solver, not involving the SMT solver, E-matching, or MBQI in any way.) I consider this as a performance and usability bug and I agree that we should try to solve this problem as it would make the unsat cores more useful. 

Note that the "crucial" assertion in this particular example can easily be replaced. We only need the term `(Prims.pow2 (BoxInt 32))` and not the rest of the terms in the quantifier. But, we can also replace that with a similar term, e.g., `(Prims.pow2 (BoxInt 33))`. Where this term comes from is completely irrelevant to soundness or correctness. Z3 is free to chose any terms that it wants and it doesn't even have to chose any terms at all, if it thinks it can solve the problem without them. In the worst case, the pattern annotations on quantifiers are essentially no more than "hints" that provide good ideas to Z3's heuristics. In practice, they are needed because without them, Z3 would not find enough useful terms as quickly or reliably. If I remember my data correctly though, it still solves about half of all uregressions queries after I strip all pattern annotations (entirely by making up it's own terms if and where necessary). 

If we need a _hard_ guarantee about results being efficiently replayable, then we need a proof, not an unsat core (mathematically theoretically and practically from Z3). And, Z3 is happy to provide such a proof in short time (for this and many other problems -- see implementation in the `cwinter_smt_proofs` branch). This is inconvenient because Z3 will take more time to solve problems when proof production is enabled, and the files holding the proofs are considerably larger than the current hints files (~200MB for all uregressions is what I saw in test runs some time ago). There's also human effort involved in developing a suitable proof checker, either in FStar or Z3.

If we are ok with a _soft_ guarantee, we have multiple options:

1. (My least favored solution:) Work around it in FStar, so that Z3 never gets into trouble. This is obviously a lot of effort and it will be unreliable, e.g. when FStar is used to verify programs that it hasn't seen before. The most extreme thing we can do on that end, is to implement our own instantiation strategy inside of FStar. We could continue to use Z3 as a ground decision procedure, which it is good and fairly predictable for, but that would still only be a soft guarantee as the runtime that it takes on the ground problem may still be vary in either direction on similar problems, depending on various factors and heuristics. A less extreme type of FStar-level workaround is to simply check the hints after they are produced and to modify them if they are not replayable. This is of course relative expensive, but it works (e.g. `smt.core.extend_patterns=true` we can grow the core pattern horizon in steps -- see implementation in the `cwinter_checked_hints` branch.)

2. Work around it in Z3 by tracking additional dependencies of all sub-terms. To make this work, we would have to track a lot of information; in theory this is essentially the same type and amount of information that is kept when proof logging is enabled and thus comes with all the implications of setting proof=true. I think we can do better than that, to eliminate a small set of particular problems (like instances of patterns on non-nested top-level quantifiers but not on any others). I'm fairly optimistic about that (but @NikolajBjorner isn't). In any case, it will take some effort and experimentation to get this right (further complicated by this being in the "least readable" part of the Z3 code base). 

3. (My most favored solution:) Instead of asking Z3 to save a lot of dependency/proof data, simply dump all relevant information that it uses/produces during the search and then figure out the dependencies in a post-processing step. This is the strategy I've been pursuing in the `quant-exp` branch of Z3 (on my fork at  https://github.com/wintersteiger/z3/tree/quant-exp). The idea is to log quantifier instantiations, decisions, and lemmas in a readable (human-modifiable) but fully replayable log format, so that they can be minimized and adjusted by hand if necessary. This is essentially a new proof format that leaves Z3 free to perform clever (and non-poly time) search on the ground level, but during proof replay all quantifier handling is disabled (E-matching and MBQI are actually disable in the replay code). The current stage of the implementation is that it works for "flat" problems that don't contain nested quantifiers, and it isn't tested with MBQI on at the same time as E-matching. With the new QIDs, this can be super realiable as it is able to match recorded quantifier instances with quantifiers even after their definitions and orders have changed in the input. I think this solution is the best of both worlds as it allows us to use Z3's heuristics (without re-inventing them in FStar), but meeting FStar's replayability requirements. There's a little bit of a boot-strapping problem as it will take some computation time to come up with an initial set of replayable proof files and minimizing them to get best possible performance out of them. 

4. Your suggestion here!

I'm planning to look at the performance of checking the (pattern-extended) hints later today. I have a good idea how to do that and I think that's the shortest path to relative success here, without requiring custom `--z3cli` options on every tricky query.

**Comment by nikswamy** [comment]
How can I get Z3 to display a proof. 

I used to be able to do `z3 foo.smt2 PROOF_MODE=2 DISPLAY_PROOF=true` in older versions of z3

With 4.5.0, I've tried `$ z3 foo.smt2 proof=true pp.pretty_proof=true` but it doesn't show me anything.

To be honest, I'm still skeptical of the unsat core in this case really being unsat. I'll try to work on minimizing the example to a point where manual inspection is not too painful.

**Comment by wintersteiger** [comment]
That's a good idea in any case! I have it simplified and much less verbose, happy to share if you think it would help. 

You should get the proofs by adding `proof=true` on the command line and then `(get-proof)` instead of `(get-unsat-core)` in the SMT2 file. The code I have in the `cwinter_smt_proofs` branch does exactly that (but isn't quite up to date with master) and it will record the proofs to files when you add `--record_proofs` to the fstar.exe call.

**Comment by nikswamy** [comment]
For the record, Christoph cleared up my confusion. This example is exactly the case where fuel correspondence/fuel irrelevance contribute only triggers and are not needed semantically for the proof of unsat.

**Comment by nikswamy** [comment]
Now, the fuel correspondence and fuel irrelevance axiom are unconditionally retained during a hint-replay run.

We used to have 152 failing hints in the `make uregressions`. 

Now:

```
$ grep "Query-stats" fstar-ci-ae313393-7097.all  | grep hint | grep failed | wc -l
46

$ grep "Query-stats" fstar-ci-ae313393-7097.all  | grep hint | grep succeeded | wc -l
10230
```

FWIW the `1ul` program now succeeds in replaying its hint.

**Comment by wintersteiger** [comment]
@nikswamy Awesome! Those numbers are great, I did not think it would have this much of an impact! 

I also added an option to Z3 (`core.extend_nonlocal_patterns`) which adds all those labels that contain patterns which contain symbols that are not referred to in the body. That way I got it down to a similarly low number of failures, but the hints files grew too big. So, for now just including the fuel_* labels is definitely the best choice. Looking at "46", I feel I should push hard for a 0. 


```
$ grep "Query-stats" `find . -name *.out`  | grep "failed (with" | wc -l
59

$ grep "Query-stats" `find . -name *.out`  | grep "succeeded (with" | wc -l
9555

grep "Query-stats" `find . -name *.out`  | wc -l
9690
```

and with --z3refresh:

```
$ grep "Query-stats" `find . -name *.out`  | grep "failed (with" | wc -l 
38

$ grep "Query-stats" `find . -name *.out`  | grep "succeeded (with" | wc -l
8220

$ grep "Query-stats" `find . -name *.out`  | wc -l
9674
```

So, there is still a significant difference between default and --z3refresh. I'll take a look around to see why that is. (Also, --check_hints will soon land in master and I'm cautiously optimistic that we can get many of the remaining 38 too succeed as well.)

**Comment by nikswamy** [comment]
Yes, going for zero is irresistible : )

**Comment by wintersteiger** [comment]
Out of time for today, but I'm super close:

```
$ grep assertion `find . -name *.err` | wc -l
0
$ grep "succeeded (with" `find . -name *.out` | wc -l
10465
$ grep "failed (with" `find . -name *.out` | wc -l
1
```

(with --check_hints --z3refresh and a couple rlimit tweaks to make the latest Z3 happy).

**Comment by nikswamy** [comment]
!!

**Comment by wintersteiger** [comment]
That last one was caused by faulty Makefile rule. My latest results are as such:

Default hints:
```
$ grep assertion `find . -name *.err` | wc -l
0                                                
$ grep "succeeded (with" `find . -name *.out` | wc -l
9255                                             
$ grep "failed (with" `find . -name *.out` | wc -l
47                                               
$ grep "Query-stats" `find . -name *.out` | wc -l
9794
```

Hints generated with --check_hints:
```
$ grep assertion `find . -name *.err` | wc -l
0
$ grep "succeeded (with" `find . -name *.out` | wc -l
9118
$ grep "failed (with" `find . -name *.out` | wc -l
0
$ grep "Query-stats" `find . -name *.out` | wc -l
9731
```

For both I slightly tweaked z3rlimits and fuels (using z3 master): [tweaks.txt](https://github.com/FStarLang/FStar/files/959279/tweaks.txt) Not sure whether tighter tweaks reduced the overall number of queries (less than 10k when yesterday I saw more than 10k)

Replaying the checked hints is also a little bit faster: All replays of default hints take 3837s while the checked ones take 3698s. There's still room for improvement on the replay time; further analysis pending. The size of the hint files is larger, but well within reason: 4.1MB default and 8.5MB checked. 

So, I'll now merge the --check_hints code into master; it also comes with re-usable Z3 statistics, e.g. to report the actual consumption of rlimit-counts and it asks Z3 for the reason of unknown results so we can distinguish between resources being exhausted and Z3 giving up because of quantifiers. 

I still have one head-scratcher: the bufferq target in ulib throws out-of-memory exceptions, but I can't replay them locally. Most likely the Azure VMs I use to run stuff come with less memory than expected.

**Comment by nikswamy** [comment]
Very cool! Congratulations : )

I'd like (at some point) to see if we can zero in on which specific additional assertions are needed to make hints replay. In particular, I wonder if there are other systematic tweaks to F*'s smt encoding (e.g., like retaining the fuel_* assertions) that can improve hint replay besides the use of checked_hints

**Comment by wintersteiger** [comment]
Thanks!

Absolutely, we should definitely take a look around to see what else we can do systematically, both on the FStar and the Z3 level. I'm also planning to take a look at @dwoos filter/slicer soon; it may help but it's too slow for production code at the moment.
