### ISSUE TITLE
Spurious abstraction violation error?

### ISSUE THREAD

**Issue by aseemr** [FStarLang/FStar#907]
```
module Test

abstract noeq type t' = {
  f1: nat;
  f2: nat -> nat
}

abstract type t = x:t'{x.f1 >= 1}

abstract let equal (x:t) (y:t) = x.f1 = y.f1 /\ FStar.FunctionalExtensionality.feq x.f2 y.f2
```

```
$ fstar.exe Test.fst
.\Test.fst(10,20-10,21) : (Error) Interface of Test violates its abstraction (add a 'private' qualifier to 'equal'?): Expected expression of type "t'"; got expression "x" of type "t"
```

**Comment by nikswamy** [comment]
I have noticed this before. Here's how I diagnose it:

`$ fstar a.fst  --print_effect_args --debug A --debug_level LogTypes `

It shows `visible logic abstract let  equal  : (x:t -> y:t -> Type) = (fun x y -> (l_and (b2t (op_Equality (__proj__Mkt'__item__f1 x@1) (__proj__Mkt'__item__f1 y@0))) (feq (__proj__Mkt'__item__f2 x@1) (__proj__Mkt'__item__f2 y@0))))`

So, the inferred type of `equal` contains a WP that violates the abstraction. 

We should: 
1. Fix the error message, so that it doesn't just suggest adding `private`
2. Figure out if it's possible in this case for the default effect behavior to kick in at the top-level and turn this into `Tot`

Meanwhile, this works:

```
module A

abstract noeq type t' = {
  f1: nat;
  f2: nat -> nat
}

abstract type t = x:t'{x.f1 >= 1}

abstract let equal (x:t) (y:t) : Tot Type0 = x.f1 = y.f1 /\ FStar.FunctionalExtensionality.feq x.f2 y.f2
```
