### ISSUE TITLE
The path to removing low-level/crypto

### ISSUE THREAD

**Issue by msprotz** [FStarLang/FStar#928]
Possibly more steps to be discussed with @ad-l ...

- https://github.com/project-everest/everest/blob/master/everest#L611 "moving the Spartan assemblies to the F* repository" → move them to HACL*
- https://github.com/project-everest/everest/blob/master/everest#L723 checking that we can still compile krml-test.exe and test-perf.exe → replace by the compilation of these two targets in HACL*, including the two variants of krml-test
- moving stuff from Crypto.Test to Crypto.KrmlTest
- merge the mitls branch

... anything else?

**Comment by nikswamy** [comment]
I'd like to spend some time writing a Crypto.AEAD.fsti in hacl-star, motivated by my dependence cutting experiments in mitls.

But, this will have no impact on mitls until we switch it to hacl. (stating the obvious)

So, all the more reason to remove low-level/crypto, so that our day-to-day working style in TLS can improve.

**Comment by aseemr** [comment]
This is outdated, closing.
